// Typed by hand so class names are checked at the call sites; keep in sync with Nav.module.css.
declare const classes: {
  readonly shell: string;
  readonly publicShell: string;
  readonly adminMain: string;
  readonly adminNavbar: string;
  readonly bar: string;
  readonly links: string;
  readonly link: string;
  readonly marker: string;
  readonly actions: string;
  readonly menuLink: string;
  readonly menuIcon: string;
  readonly cart: string;
  readonly tabBar: string;
  readonly tab: string;
  readonly tabIcon: string;
  readonly tabMarker: string;
  readonly tabBadge: string;
  readonly sheetContent: string;
  readonly bottom: string;
  readonly sheetBackdrop: string;
  readonly sheetBody: string;
  readonly sheetViewport: string;
  readonly identityLink: string;
  readonly identityText: string;
  readonly identityBadges: string;
  readonly identityName: string;
  readonly grabber: string;
  readonly guest: string;
  readonly group: string;
  readonly groupTitle: string;
  readonly row: string;
  readonly rowIcon: string;
  readonly rowText: string;
  readonly rowLabel: string;
  readonly rowHint: string;
  readonly tasks: string;
  readonly sidebar: string;
  readonly sidebarScroll: string;
  readonly groupRow: string;
  readonly groupChevron: string;
  readonly groupChildren: string;
  readonly sidebarHead: string;
};

export default classes;
