/* eslint-disable prettier/prettier */
import type { AdonisEndpoint } from '@tuyau/core/types'
import type { Registry } from './schema.d.ts'
import type { ApiDefinition } from './tree.d.ts'

const placeholder: any = {}

const routes = {
  'tokens.refresh': {
    methods: ["POST"],
    pattern: '/auth/token',
    tokens: [{"old":"/auth/token","type":0,"val":"auth","end":""},{"old":"/auth/token","type":0,"val":"token","end":""}],
    types: placeholder as Registry['tokens.refresh']['types'],
  },
  'vipps.redirect': {
    methods: ["GET","HEAD"],
    pattern: '/auth/vipps/redirect',
    tokens: [{"old":"/auth/vipps/redirect","type":0,"val":"auth","end":""},{"old":"/auth/vipps/redirect","type":0,"val":"vipps","end":""},{"old":"/auth/vipps/redirect","type":0,"val":"redirect","end":""}],
    types: placeholder as Registry['vipps.redirect']['types'],
  },
  'vipps.callback': {
    methods: ["GET","HEAD"],
    pattern: '/auth/vipps/callback',
    tokens: [{"old":"/auth/vipps/callback","type":0,"val":"auth","end":""},{"old":"/auth/vipps/callback","type":0,"val":"vipps","end":""},{"old":"/auth/vipps/callback","type":0,"val":"callback","end":""}],
    types: placeholder as Registry['vipps.callback']['types'],
  },
  'local.login': {
    methods: ["POST"],
    pattern: '/auth/local/login',
    tokens: [{"old":"/auth/local/login","type":0,"val":"auth","end":""},{"old":"/auth/local/login","type":0,"val":"local","end":""},{"old":"/auth/local/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['local.login']['types'],
  },
  'local.register': {
    methods: ["POST"],
    pattern: '/auth/local/register',
    tokens: [{"old":"/auth/local/register","type":0,"val":"auth","end":""},{"old":"/auth/local/register","type":0,"val":"local","end":""},{"old":"/auth/local/register","type":0,"val":"register","end":""}],
    types: placeholder as Registry['local.register']['types'],
  },
  'password_reset.request': {
    methods: ["POST"],
    pattern: '/auth/password_reset',
    tokens: [{"old":"/auth/password_reset","type":0,"val":"auth","end":""},{"old":"/auth/password_reset","type":0,"val":"password_reset","end":""}],
    types: placeholder as Registry['password_reset.request']['types'],
  },
  'password_reset.validate': {
    methods: ["GET","HEAD"],
    pattern: '/auth/password_reset/:id/:token',
    tokens: [{"old":"/auth/password_reset/:id/:token","type":0,"val":"auth","end":""},{"old":"/auth/password_reset/:id/:token","type":0,"val":"password_reset","end":""},{"old":"/auth/password_reset/:id/:token","type":1,"val":"id","end":""},{"old":"/auth/password_reset/:id/:token","type":1,"val":"token","end":""}],
    types: placeholder as Registry['password_reset.validate']['types'],
  },
  'password_reset.reset': {
    methods: ["POST"],
    pattern: '/auth/password_reset/:id',
    tokens: [{"old":"/auth/password_reset/:id","type":0,"val":"auth","end":""},{"old":"/auth/password_reset/:id","type":0,"val":"password_reset","end":""},{"old":"/auth/password_reset/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['password_reset.reset']['types'],
  },
  'email_verification.verify': {
    methods: ["GET","HEAD"],
    pattern: '/email_verification/:id',
    tokens: [{"old":"/email_verification/:id","type":0,"val":"email_verification","end":""},{"old":"/email_verification/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['email_verification.verify']['types'],
  },
  'email_validation.validate': {
    methods: ["POST"],
    pattern: '/email_validation',
    tokens: [{"old":"/email_validation","type":0,"val":"email_validation","end":""}],
    types: placeholder as Registry['email_validation.validate']['types'],
  },
  'postal_codes.show': {
    methods: ["GET","HEAD"],
    pattern: '/postal_codes/:postalCode',
    tokens: [{"old":"/postal_codes/:postalCode","type":0,"val":"postal_codes","end":""},{"old":"/postal_codes/:postalCode","type":1,"val":"postalCode","end":""}],
    types: placeholder as Registry['postal_codes.show']['types'],
  },
  'bokflyt.contact': {
    methods: ["POST"],
    pattern: '/bokflyt/contact',
    tokens: [{"old":"/bokflyt/contact","type":0,"val":"bokflyt","end":""},{"old":"/bokflyt/contact","type":0,"val":"contact","end":""}],
    types: placeholder as Registry['bokflyt.contact']['types'],
  },
  'branches.index': {
    methods: ["GET","HEAD"],
    pattern: '/branches',
    tokens: [{"old":"/branches","type":0,"val":"branches","end":""}],
    types: placeholder as Registry['branches.index']['types'],
  },
  'branches.index_public': {
    methods: ["GET","HEAD"],
    pattern: '/branches/public',
    tokens: [{"old":"/branches/public","type":0,"val":"branches","end":""},{"old":"/branches/public","type":0,"val":"public","end":""}],
    types: placeholder as Registry['branches.index_public']['types'],
  },
  'branches.show': {
    methods: ["GET","HEAD"],
    pattern: '/branches/:branchId',
    tokens: [{"old":"/branches/:branchId","type":0,"val":"branches","end":""},{"old":"/branches/:branchId","type":1,"val":"branchId","end":""}],
    types: placeholder as Registry['branches.show']['types'],
  },
  'branch_catalog.show': {
    methods: ["GET","HEAD"],
    pattern: '/branches/:branchId/catalog',
    tokens: [{"old":"/branches/:branchId/catalog","type":0,"val":"branches","end":""},{"old":"/branches/:branchId/catalog","type":1,"val":"branchId","end":""},{"old":"/branches/:branchId/catalog","type":0,"val":"catalog","end":""}],
    types: placeholder as Registry['branch_catalog.show']['types'],
  },
  'opening_hours.index': {
    methods: ["GET","HEAD"],
    pattern: '/branches/:branchId/opening_hours',
    tokens: [{"old":"/branches/:branchId/opening_hours","type":0,"val":"branches","end":""},{"old":"/branches/:branchId/opening_hours","type":1,"val":"branchId","end":""},{"old":"/branches/:branchId/opening_hours","type":0,"val":"opening_hours","end":""}],
    types: placeholder as Registry['opening_hours.index']['types'],
  },
  'items.buyback': {
    methods: ["GET","HEAD"],
    pattern: '/items/buyback',
    tokens: [{"old":"/items/buyback","type":0,"val":"items","end":""},{"old":"/items/buyback","type":0,"val":"buyback","end":""}],
    types: placeholder as Registry['items.buyback']['types'],
  },
  'editable_texts.show': {
    methods: ["GET","HEAD"],
    pattern: '/editable_texts/:id',
    tokens: [{"old":"/editable_texts/:id","type":0,"val":"editable_texts","end":""},{"old":"/editable_texts/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['editable_texts.show']['types'],
  },
  'questions_and_answers.index': {
    methods: ["GET","HEAD"],
    pattern: '/questions_and_answers',
    tokens: [{"old":"/questions_and_answers","type":0,"val":"questions_and_answers","end":""}],
    types: placeholder as Registry['questions_and_answers.index']['types'],
  },
  'signatures.valid': {
    methods: ["GET","HEAD"],
    pattern: '/signatures/:detailsId/valid',
    tokens: [{"old":"/signatures/:detailsId/valid","type":0,"val":"signatures","end":""},{"old":"/signatures/:detailsId/valid","type":1,"val":"detailsId","end":""},{"old":"/signatures/:detailsId/valid","type":0,"val":"valid","end":""}],
    types: placeholder as Registry['signatures.valid']['types'],
  },
  'signatures.sign': {
    methods: ["POST"],
    pattern: '/signatures/:detailsId/sign',
    tokens: [{"old":"/signatures/:detailsId/sign","type":0,"val":"signatures","end":""},{"old":"/signatures/:detailsId/sign","type":1,"val":"detailsId","end":""},{"old":"/signatures/:detailsId/sign","type":0,"val":"sign","end":""}],
    types: placeholder as Registry['signatures.sign']['types'],
  },
  'unique_ids.pdf': {
    methods: ["GET","HEAD"],
    pattern: '/unique_ids/pdf/:token',
    tokens: [{"old":"/unique_ids/pdf/:token","type":0,"val":"unique_ids","end":""},{"old":"/unique_ids/pdf/:token","type":0,"val":"pdf","end":""},{"old":"/unique_ids/pdf/:token","type":1,"val":"token","end":""}],
    types: placeholder as Registry['unique_ids.pdf']['types'],
  },
  'checkout.vipps_callback': {
    methods: ["POST"],
    pattern: '/checkout/vipps/callback',
    tokens: [{"old":"/checkout/vipps/callback","type":0,"val":"checkout","end":""},{"old":"/checkout/vipps/callback","type":0,"val":"vipps","end":""},{"old":"/checkout/vipps/callback","type":0,"val":"callback","end":""}],
    types: placeholder as Registry['checkout.vipps_callback']['types'],
  },
  'webhooks.sendgrid_events': {
    methods: ["POST"],
    pattern: '/webhooks/sendgrid',
    tokens: [{"old":"/webhooks/sendgrid","type":0,"val":"webhooks","end":""},{"old":"/webhooks/sendgrid","type":0,"val":"sendgrid","end":""}],
    types: placeholder as Registry['webhooks.sendgrid_events']['types'],
  },
  'webhooks.twilio_sms_event': {
    methods: ["POST"],
    pattern: '/webhooks/twilio/:messageId',
    tokens: [{"old":"/webhooks/twilio/:messageId","type":0,"val":"webhooks","end":""},{"old":"/webhooks/twilio/:messageId","type":0,"val":"twilio","end":""},{"old":"/webhooks/twilio/:messageId","type":1,"val":"messageId","end":""}],
    types: placeholder as Registry['webhooks.twilio_sms_event']['types'],
  },
  'email_verification.send': {
    methods: ["POST"],
    pattern: '/email_verification',
    tokens: [{"old":"/email_verification","type":0,"val":"email_verification","end":""}],
    types: placeholder as Registry['email_verification.send']['types'],
  },
  'public_blid_lookup.show': {
    methods: ["GET","HEAD"],
    pattern: '/public_blid_lookup/:blid',
    tokens: [{"old":"/public_blid_lookup/:blid","type":0,"val":"public_blid_lookup","end":""},{"old":"/public_blid_lookup/:blid","type":1,"val":"blid","end":""}],
    types: placeholder as Registry['public_blid_lookup.show']['types'],
  },
  'users.me': {
    methods: ["GET","HEAD"],
    pattern: '/users/me',
    tokens: [{"old":"/users/me","type":0,"val":"users","end":""},{"old":"/users/me","type":0,"val":"me","end":""}],
    types: placeholder as Registry['users.me']['types'],
  },
  'users.update_me': {
    methods: ["PATCH"],
    pattern: '/users/me',
    tokens: [{"old":"/users/me","type":0,"val":"users","end":""},{"old":"/users/me","type":0,"val":"me","end":""}],
    types: placeholder as Registry['users.update_me']['types'],
  },
  'customer_items.me': {
    methods: ["GET","HEAD"],
    pattern: '/customer_items/me',
    tokens: [{"old":"/customer_items/me","type":0,"val":"customer_items","end":""},{"old":"/customer_items/me","type":0,"val":"me","end":""}],
    types: placeholder as Registry['customer_items.me']['types'],
  },
  'signatures.me': {
    methods: ["GET","HEAD"],
    pattern: '/signatures/me',
    tokens: [{"old":"/signatures/me","type":0,"val":"signatures","end":""},{"old":"/signatures/me","type":0,"val":"me","end":""}],
    types: placeholder as Registry['signatures.me']['types'],
  },
  'signatures.send_link_me': {
    methods: ["POST"],
    pattern: '/signatures/me/send',
    tokens: [{"old":"/signatures/me/send","type":0,"val":"signatures","end":""},{"old":"/signatures/me/send","type":0,"val":"me","end":""},{"old":"/signatures/me/send","type":0,"val":"send","end":""}],
    types: placeholder as Registry['signatures.send_link_me']['types'],
  },
  'orders.index_me': {
    methods: ["GET","HEAD"],
    pattern: '/orders/me',
    tokens: [{"old":"/orders/me","type":0,"val":"orders","end":""},{"old":"/orders/me","type":0,"val":"me","end":""}],
    types: placeholder as Registry['orders.index_me']['types'],
  },
  'orders.open_items_me': {
    methods: ["GET","HEAD"],
    pattern: '/orders/me/open_items',
    tokens: [{"old":"/orders/me/open_items","type":0,"val":"orders","end":""},{"old":"/orders/me/open_items","type":0,"val":"me","end":""},{"old":"/orders/me/open_items","type":0,"val":"open_items","end":""}],
    types: placeholder as Registry['orders.open_items_me']['types'],
  },
  'orders.cancel_item_me': {
    methods: ["POST"],
    pattern: '/orders/me/cancel_item',
    tokens: [{"old":"/orders/me/cancel_item","type":0,"val":"orders","end":""},{"old":"/orders/me/cancel_item","type":0,"val":"me","end":""},{"old":"/orders/me/cancel_item","type":0,"val":"cancel_item","end":""}],
    types: placeholder as Registry['orders.cancel_item_me']['types'],
  },
  'orders.show_me': {
    methods: ["GET","HEAD"],
    pattern: '/orders/me/:orderId',
    tokens: [{"old":"/orders/me/:orderId","type":0,"val":"orders","end":""},{"old":"/orders/me/:orderId","type":0,"val":"me","end":""},{"old":"/orders/me/:orderId","type":1,"val":"orderId","end":""}],
    types: placeholder as Registry['orders.show_me']['types'],
  },
  'checkout.initialize': {
    methods: ["POST"],
    pattern: '/checkout',
    tokens: [{"old":"/checkout","type":0,"val":"checkout","end":""}],
    types: placeholder as Registry['checkout.initialize']['types'],
  },
  'checkout.confirm': {
    methods: ["POST"],
    pattern: '/checkout/:orderId/confirm',
    tokens: [{"old":"/checkout/:orderId/confirm","type":0,"val":"checkout","end":""},{"old":"/checkout/:orderId/confirm","type":1,"val":"orderId","end":""},{"old":"/checkout/:orderId/confirm","type":0,"val":"confirm","end":""}],
    types: placeholder as Registry['checkout.confirm']['types'],
  },
  'checkout.status': {
    methods: ["GET","HEAD"],
    pattern: '/checkout/:orderId/status',
    tokens: [{"old":"/checkout/:orderId/status","type":0,"val":"checkout","end":""},{"old":"/checkout/:orderId/status","type":1,"val":"orderId","end":""},{"old":"/checkout/:orderId/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['checkout.status']['types'],
  },
  'matches.me': {
    methods: ["GET","HEAD"],
    pattern: '/matches/me',
    tokens: [{"old":"/matches/me","type":0,"val":"matches","end":""},{"old":"/matches/me","type":0,"val":"me","end":""}],
    types: placeholder as Registry['matches.me']['types'],
  },
  'matches.transfer_item': {
    methods: ["POST"],
    pattern: '/matches/transfer_item',
    tokens: [{"old":"/matches/transfer_item","type":0,"val":"matches","end":""},{"old":"/matches/transfer_item","type":0,"val":"transfer_item","end":""}],
    types: placeholder as Registry['matches.transfer_item']['types'],
  },
  'branches.store': {
    methods: ["POST"],
    pattern: '/branches',
    tokens: [{"old":"/branches","type":0,"val":"branches","end":""}],
    types: placeholder as Registry['branches.store']['types'],
  },
  'branch_relationships.update': {
    methods: ["PATCH"],
    pattern: '/branches/relationships',
    tokens: [{"old":"/branches/relationships","type":0,"val":"branches","end":""},{"old":"/branches/relationships","type":0,"val":"relationships","end":""}],
    types: placeholder as Registry['branch_relationships.update']['types'],
  },
  'branch_members.update': {
    methods: ["PATCH"],
    pattern: '/branches/members',
    tokens: [{"old":"/branches/members","type":0,"val":"branches","end":""},{"old":"/branches/members","type":0,"val":"members","end":""}],
    types: placeholder as Registry['branch_members.update']['types'],
  },
  'branches.update': {
    methods: ["PATCH"],
    pattern: '/branches/:branchId',
    tokens: [{"old":"/branches/:branchId","type":0,"val":"branches","end":""},{"old":"/branches/:branchId","type":1,"val":"branchId","end":""}],
    types: placeholder as Registry['branches.update']['types'],
  },
  'branch_items.index': {
    methods: ["GET","HEAD"],
    pattern: '/branches/:branchId/items',
    tokens: [{"old":"/branches/:branchId/items","type":0,"val":"branches","end":""},{"old":"/branches/:branchId/items","type":1,"val":"branchId","end":""},{"old":"/branches/:branchId/items","type":0,"val":"items","end":""}],
    types: placeholder as Registry['branch_items.index']['types'],
  },
  'branch_items.update': {
    methods: ["PUT"],
    pattern: '/branches/:branchId/items',
    tokens: [{"old":"/branches/:branchId/items","type":0,"val":"branches","end":""},{"old":"/branches/:branchId/items","type":1,"val":"branchId","end":""},{"old":"/branches/:branchId/items","type":0,"val":"items","end":""}],
    types: placeholder as Registry['branch_items.update']['types'],
  },
  'opening_hours.store': {
    methods: ["POST"],
    pattern: '/opening_hours',
    tokens: [{"old":"/opening_hours","type":0,"val":"opening_hours","end":""}],
    types: placeholder as Registry['opening_hours.store']['types'],
  },
  'opening_hours.destroy': {
    methods: ["DELETE"],
    pattern: '/opening_hours/:id',
    tokens: [{"old":"/opening_hours/:id","type":0,"val":"opening_hours","end":""},{"old":"/opening_hours/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['opening_hours.destroy']['types'],
  },
  'branch_members.index': {
    methods: ["GET","HEAD"],
    pattern: '/branches/:branchId/members',
    tokens: [{"old":"/branches/:branchId/members","type":0,"val":"branches","end":""},{"old":"/branches/:branchId/members","type":1,"val":"branchId","end":""},{"old":"/branches/:branchId/members","type":0,"val":"members","end":""}],
    types: placeholder as Registry['branch_members.index']['types'],
  },
  'branch_members.destroy_direct': {
    methods: ["DELETE"],
    pattern: '/branches/:branchId/members/direct',
    tokens: [{"old":"/branches/:branchId/members/direct","type":0,"val":"branches","end":""},{"old":"/branches/:branchId/members/direct","type":1,"val":"branchId","end":""},{"old":"/branches/:branchId/members/direct","type":0,"val":"members","end":""},{"old":"/branches/:branchId/members/direct","type":0,"val":"direct","end":""}],
    types: placeholder as Registry['branch_members.destroy_direct']['types'],
  },
  'branch_members.destroy_indirect': {
    methods: ["DELETE"],
    pattern: '/branches/:branchId/members/indirect',
    tokens: [{"old":"/branches/:branchId/members/indirect","type":0,"val":"branches","end":""},{"old":"/branches/:branchId/members/indirect","type":1,"val":"branchId","end":""},{"old":"/branches/:branchId/members/indirect","type":0,"val":"members","end":""},{"old":"/branches/:branchId/members/indirect","type":0,"val":"indirect","end":""}],
    types: placeholder as Registry['branch_members.destroy_indirect']['types'],
  },
  'branch_subjects.index': {
    methods: ["GET","HEAD"],
    pattern: '/branches/:branchId/subjects',
    tokens: [{"old":"/branches/:branchId/subjects","type":0,"val":"branches","end":""},{"old":"/branches/:branchId/subjects","type":1,"val":"branchId","end":""},{"old":"/branches/:branchId/subjects","type":0,"val":"subjects","end":""}],
    types: placeholder as Registry['branch_subjects.index']['types'],
  },
  'branch_subjects.store': {
    methods: ["POST"],
    pattern: '/branches/:branchId/subjects',
    tokens: [{"old":"/branches/:branchId/subjects","type":0,"val":"branches","end":""},{"old":"/branches/:branchId/subjects","type":1,"val":"branchId","end":""},{"old":"/branches/:branchId/subjects","type":0,"val":"subjects","end":""}],
    types: placeholder as Registry['branch_subjects.store']['types'],
  },
  'branch_subjects.import': {
    methods: ["POST"],
    pattern: '/branches/:branchId/subjects/import',
    tokens: [{"old":"/branches/:branchId/subjects/import","type":0,"val":"branches","end":""},{"old":"/branches/:branchId/subjects/import","type":1,"val":"branchId","end":""},{"old":"/branches/:branchId/subjects/import","type":0,"val":"subjects","end":""},{"old":"/branches/:branchId/subjects/import","type":0,"val":"import","end":""}],
    types: placeholder as Registry['branch_subjects.import']['types'],
  },
  'branch_subjects.update': {
    methods: ["PUT"],
    pattern: '/branches/:branchId/subjects/:subjectId',
    tokens: [{"old":"/branches/:branchId/subjects/:subjectId","type":0,"val":"branches","end":""},{"old":"/branches/:branchId/subjects/:subjectId","type":1,"val":"branchId","end":""},{"old":"/branches/:branchId/subjects/:subjectId","type":0,"val":"subjects","end":""},{"old":"/branches/:branchId/subjects/:subjectId","type":1,"val":"subjectId","end":""}],
    types: placeholder as Registry['branch_subjects.update']['types'],
  },
  'branch_subjects.destroy': {
    methods: ["DELETE"],
    pattern: '/branches/:branchId/subjects/:subjectId',
    tokens: [{"old":"/branches/:branchId/subjects/:subjectId","type":0,"val":"branches","end":""},{"old":"/branches/:branchId/subjects/:subjectId","type":1,"val":"branchId","end":""},{"old":"/branches/:branchId/subjects/:subjectId","type":0,"val":"subjects","end":""},{"old":"/branches/:branchId/subjects/:subjectId","type":1,"val":"subjectId","end":""}],
    types: placeholder as Registry['branch_subjects.destroy']['types'],
  },
  'branch_subject_choices.evaluate': {
    methods: ["POST"],
    pattern: '/branches/:branchId/subject_choices/evaluate',
    tokens: [{"old":"/branches/:branchId/subject_choices/evaluate","type":0,"val":"branches","end":""},{"old":"/branches/:branchId/subject_choices/evaluate","type":1,"val":"branchId","end":""},{"old":"/branches/:branchId/subject_choices/evaluate","type":0,"val":"subject_choices","end":""},{"old":"/branches/:branchId/subject_choices/evaluate","type":0,"val":"evaluate","end":""}],
    types: placeholder as Registry['branch_subject_choices.evaluate']['types'],
  },
  'branch_subject_choices.upload': {
    methods: ["POST"],
    pattern: '/branches/:branchId/subject_choices/upload',
    tokens: [{"old":"/branches/:branchId/subject_choices/upload","type":0,"val":"branches","end":""},{"old":"/branches/:branchId/subject_choices/upload","type":1,"val":"branchId","end":""},{"old":"/branches/:branchId/subject_choices/upload","type":0,"val":"subject_choices","end":""},{"old":"/branches/:branchId/subject_choices/upload","type":0,"val":"upload","end":""}],
    types: placeholder as Registry['branch_subject_choices.upload']['types'],
  },
  'branch_signature_status.show': {
    methods: ["GET","HEAD"],
    pattern: '/branches/:branchId/signature_status',
    tokens: [{"old":"/branches/:branchId/signature_status","type":0,"val":"branches","end":""},{"old":"/branches/:branchId/signature_status","type":1,"val":"branchId","end":""},{"old":"/branches/:branchId/signature_status","type":0,"val":"signature_status","end":""}],
    types: placeholder as Registry['branch_signature_status.show']['types'],
  },
  'branch_insights.get_book_movements': {
    methods: ["GET","HEAD"],
    pattern: '/branches/:branchId/insights/book_movements',
    tokens: [{"old":"/branches/:branchId/insights/book_movements","type":0,"val":"branches","end":""},{"old":"/branches/:branchId/insights/book_movements","type":1,"val":"branchId","end":""},{"old":"/branches/:branchId/insights/book_movements","type":0,"val":"insights","end":""},{"old":"/branches/:branchId/insights/book_movements","type":0,"val":"book_movements","end":""}],
    types: placeholder as Registry['branch_insights.get_book_movements']['types'],
  },
  'branch_books.get_active_books': {
    methods: ["GET","HEAD"],
    pattern: '/branches/:branchId/active_books',
    tokens: [{"old":"/branches/:branchId/active_books","type":0,"val":"branches","end":""},{"old":"/branches/:branchId/active_books","type":1,"val":"branchId","end":""},{"old":"/branches/:branchId/active_books","type":0,"val":"active_books","end":""}],
    types: placeholder as Registry['branch_books.get_active_books']['types'],
  },
  'branch_books.get_active_book_details': {
    methods: ["GET","HEAD"],
    pattern: '/branches/:branchId/active_books/details',
    tokens: [{"old":"/branches/:branchId/active_books/details","type":0,"val":"branches","end":""},{"old":"/branches/:branchId/active_books/details","type":1,"val":"branchId","end":""},{"old":"/branches/:branchId/active_books/details","type":0,"val":"active_books","end":""},{"old":"/branches/:branchId/active_books/details","type":0,"val":"details","end":""}],
    types: placeholder as Registry['branch_books.get_active_book_details']['types'],
  },
  'branch_books.bulk_update_active_books': {
    methods: ["PATCH"],
    pattern: '/branches/:branchId/active_books',
    tokens: [{"old":"/branches/:branchId/active_books","type":0,"val":"branches","end":""},{"old":"/branches/:branchId/active_books","type":1,"val":"branchId","end":""},{"old":"/branches/:branchId/active_books","type":0,"val":"active_books","end":""}],
    types: placeholder as Registry['branch_books.bulk_update_active_books']['types'],
  },
  'branch_books.get_ordered_books': {
    methods: ["GET","HEAD"],
    pattern: '/branches/:branchId/ordered_books',
    tokens: [{"old":"/branches/:branchId/ordered_books","type":0,"val":"branches","end":""},{"old":"/branches/:branchId/ordered_books","type":1,"val":"branchId","end":""},{"old":"/branches/:branchId/ordered_books","type":0,"val":"ordered_books","end":""}],
    types: placeholder as Registry['branch_books.get_ordered_books']['types'],
  },
  'branch_books.get_ordered_book_details': {
    methods: ["GET","HEAD"],
    pattern: '/branches/:branchId/ordered_books/details',
    tokens: [{"old":"/branches/:branchId/ordered_books/details","type":0,"val":"branches","end":""},{"old":"/branches/:branchId/ordered_books/details","type":1,"val":"branchId","end":""},{"old":"/branches/:branchId/ordered_books/details","type":0,"val":"ordered_books","end":""},{"old":"/branches/:branchId/ordered_books/details","type":0,"val":"details","end":""}],
    types: placeholder as Registry['branch_books.get_ordered_book_details']['types'],
  },
  'branch_books.bulk_update_ordered_books': {
    methods: ["PATCH"],
    pattern: '/branches/:branchId/ordered_books',
    tokens: [{"old":"/branches/:branchId/ordered_books","type":0,"val":"branches","end":""},{"old":"/branches/:branchId/ordered_books","type":1,"val":"branchId","end":""},{"old":"/branches/:branchId/ordered_books","type":0,"val":"ordered_books","end":""}],
    types: placeholder as Registry['branch_books.bulk_update_ordered_books']['types'],
  },
  'branch_books.cancel_ordered_books': {
    methods: ["POST"],
    pattern: '/branches/:branchId/ordered_books/cancel',
    tokens: [{"old":"/branches/:branchId/ordered_books/cancel","type":0,"val":"branches","end":""},{"old":"/branches/:branchId/ordered_books/cancel","type":1,"val":"branchId","end":""},{"old":"/branches/:branchId/ordered_books/cancel","type":0,"val":"ordered_books","end":""},{"old":"/branches/:branchId/ordered_books/cancel","type":0,"val":"cancel","end":""}],
    types: placeholder as Registry['branch_books.cancel_ordered_books']['types'],
  },
  'user_provisioning.evaluate': {
    methods: ["POST"],
    pattern: '/branches/:branchId/users/evaluate',
    tokens: [{"old":"/branches/:branchId/users/evaluate","type":0,"val":"branches","end":""},{"old":"/branches/:branchId/users/evaluate","type":1,"val":"branchId","end":""},{"old":"/branches/:branchId/users/evaluate","type":0,"val":"users","end":""},{"old":"/branches/:branchId/users/evaluate","type":0,"val":"evaluate","end":""}],
    types: placeholder as Registry['user_provisioning.evaluate']['types'],
  },
  'user_provisioning.provision': {
    methods: ["POST"],
    pattern: '/branches/:branchId/users/provision',
    tokens: [{"old":"/branches/:branchId/users/provision","type":0,"val":"branches","end":""},{"old":"/branches/:branchId/users/provision","type":1,"val":"branchId","end":""},{"old":"/branches/:branchId/users/provision","type":0,"val":"users","end":""},{"old":"/branches/:branchId/users/provision","type":0,"val":"provision","end":""}],
    types: placeholder as Registry['user_provisioning.provision']['types'],
  },
  'users.metrics': {
    methods: ["GET","HEAD"],
    pattern: '/users/metrics',
    tokens: [{"old":"/users/metrics","type":0,"val":"users","end":""},{"old":"/users/metrics","type":0,"val":"metrics","end":""}],
    types: placeholder as Registry['users.metrics']['types'],
  },
  'users.duplicates': {
    methods: ["GET","HEAD"],
    pattern: '/users/duplicates',
    tokens: [{"old":"/users/duplicates","type":0,"val":"users","end":""},{"old":"/users/duplicates","type":0,"val":"duplicates","end":""}],
    types: placeholder as Registry['users.duplicates']['types'],
  },
  'users.employees': {
    methods: ["GET","HEAD"],
    pattern: '/users/employees',
    tokens: [{"old":"/users/employees","type":0,"val":"users","end":""},{"old":"/users/employees","type":0,"val":"employees","end":""}],
    types: placeholder as Registry['users.employees']['types'],
  },
  'users.merge_preview': {
    methods: ["GET","HEAD"],
    pattern: '/users/merge_preview/:fromDetailsId/:toDetailsId',
    tokens: [{"old":"/users/merge_preview/:fromDetailsId/:toDetailsId","type":0,"val":"users","end":""},{"old":"/users/merge_preview/:fromDetailsId/:toDetailsId","type":0,"val":"merge_preview","end":""},{"old":"/users/merge_preview/:fromDetailsId/:toDetailsId","type":1,"val":"fromDetailsId","end":""},{"old":"/users/merge_preview/:fromDetailsId/:toDetailsId","type":1,"val":"toDetailsId","end":""}],
    types: placeholder as Registry['users.merge_preview']['types'],
  },
  'users.merge': {
    methods: ["POST"],
    pattern: '/users/merge',
    tokens: [{"old":"/users/merge","type":0,"val":"users","end":""},{"old":"/users/merge","type":0,"val":"merge","end":""}],
    types: placeholder as Registry['users.merge']['types'],
  },
  'users.set_permission': {
    methods: ["PUT"],
    pattern: '/users/permission',
    tokens: [{"old":"/users/permission","type":0,"val":"users","end":""},{"old":"/users/permission","type":0,"val":"permission","end":""}],
    types: placeholder as Registry['users.set_permission']['types'],
  },
  'users.destroy': {
    methods: ["DELETE"],
    pattern: '/users/:detailsId',
    tokens: [{"old":"/users/:detailsId","type":0,"val":"users","end":""},{"old":"/users/:detailsId","type":1,"val":"detailsId","end":""}],
    types: placeholder as Registry['users.destroy']['types'],
  },
  'signatures.gallery': {
    methods: ["GET","HEAD"],
    pattern: '/signatures/gallery',
    tokens: [{"old":"/signatures/gallery","type":0,"val":"signatures","end":""},{"old":"/signatures/gallery","type":0,"val":"gallery","end":""}],
    types: placeholder as Registry['signatures.gallery']['types'],
  },
  'matches.notify': {
    methods: ["POST"],
    pattern: '/matches/notify',
    tokens: [{"old":"/matches/notify","type":0,"val":"matches","end":""},{"old":"/matches/notify","type":0,"val":"notify","end":""}],
    types: placeholder as Registry['matches.notify']['types'],
  },
  'matches.send_to_stand': {
    methods: ["POST"],
    pattern: '/matches/:matchId/send_to_stand',
    tokens: [{"old":"/matches/:matchId/send_to_stand","type":0,"val":"matches","end":""},{"old":"/matches/:matchId/send_to_stand","type":1,"val":"matchId","end":""},{"old":"/matches/:matchId/send_to_stand","type":0,"val":"send_to_stand","end":""}],
    types: placeholder as Registry['matches.send_to_stand']['types'],
  },
  'match_rounds.store': {
    methods: ["POST"],
    pattern: '/match_rounds',
    tokens: [{"old":"/match_rounds","type":0,"val":"match_rounds","end":""}],
    types: placeholder as Registry['match_rounds.store']['types'],
  },
  'match_rounds.update': {
    methods: ["PATCH"],
    pattern: '/match_rounds/:id',
    tokens: [{"old":"/match_rounds/:id","type":0,"val":"match_rounds","end":""},{"old":"/match_rounds/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['match_rounds.update']['types'],
  },
  'match_rounds.generate': {
    methods: ["POST"],
    pattern: '/match_rounds/:id/generate',
    tokens: [{"old":"/match_rounds/:id/generate","type":0,"val":"match_rounds","end":""},{"old":"/match_rounds/:id/generate","type":1,"val":"id","end":""},{"old":"/match_rounds/:id/generate","type":0,"val":"generate","end":""}],
    types: placeholder as Registry['match_rounds.generate']['types'],
  },
  'match_rounds.destroy_matches': {
    methods: ["DELETE"],
    pattern: '/match_rounds/:id/matches',
    tokens: [{"old":"/match_rounds/:id/matches","type":0,"val":"match_rounds","end":""},{"old":"/match_rounds/:id/matches","type":1,"val":"id","end":""},{"old":"/match_rounds/:id/matches","type":0,"val":"matches","end":""}],
    types: placeholder as Registry['match_rounds.destroy_matches']['types'],
  },
  'match_rounds.destroy': {
    methods: ["DELETE"],
    pattern: '/match_rounds/:id',
    tokens: [{"old":"/match_rounds/:id","type":0,"val":"match_rounds","end":""},{"old":"/match_rounds/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['match_rounds.destroy']['types'],
  },
  'items.all': {
    methods: ["GET","HEAD"],
    pattern: '/items/all',
    tokens: [{"old":"/items/all","type":0,"val":"items","end":""},{"old":"/items/all","type":0,"val":"all","end":""}],
    types: placeholder as Registry['items.all']['types'],
  },
  'items.store': {
    methods: ["POST"],
    pattern: '/items',
    tokens: [{"old":"/items","type":0,"val":"items","end":""}],
    types: placeholder as Registry['items.store']['types'],
  },
  'items.bulk_upsert': {
    methods: ["POST"],
    pattern: '/items/bulk',
    tokens: [{"old":"/items/bulk","type":0,"val":"items","end":""},{"old":"/items/bulk","type":0,"val":"bulk","end":""}],
    types: placeholder as Registry['items.bulk_upsert']['types'],
  },
  'items.update': {
    methods: ["PATCH"],
    pattern: '/items/:id',
    tokens: [{"old":"/items/:id","type":0,"val":"items","end":""},{"old":"/items/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['items.update']['types'],
  },
  'invoices.index': {
    methods: ["GET","HEAD"],
    pattern: '/invoices',
    tokens: [{"old":"/invoices","type":0,"val":"invoices","end":""}],
    types: placeholder as Registry['invoices.index']['types'],
  },
  'invoices.generation_defaults': {
    methods: ["GET","HEAD"],
    pattern: '/invoices/generation_defaults',
    tokens: [{"old":"/invoices/generation_defaults","type":0,"val":"invoices","end":""},{"old":"/invoices/generation_defaults","type":0,"val":"generation_defaults","end":""}],
    types: placeholder as Registry['invoices.generation_defaults']['types'],
  },
  'invoices.generate': {
    methods: ["POST"],
    pattern: '/invoices/generate',
    tokens: [{"old":"/invoices/generate","type":0,"val":"invoices","end":""},{"old":"/invoices/generate","type":0,"val":"generate","end":""}],
    types: placeholder as Registry['invoices.generate']['types'],
  },
  'invoices.create_company_invoice': {
    methods: ["POST"],
    pattern: '/invoices/company',
    tokens: [{"old":"/invoices/company","type":0,"val":"invoices","end":""},{"old":"/invoices/company","type":0,"val":"company","end":""}],
    types: placeholder as Registry['invoices.create_company_invoice']['types'],
  },
  'invoices.export': {
    methods: ["POST"],
    pattern: '/invoices/export',
    tokens: [{"old":"/invoices/export","type":0,"val":"invoices","end":""},{"old":"/invoices/export","type":0,"val":"export","end":""}],
    types: placeholder as Registry['invoices.export']['types'],
  },
  'invoices.set_statuses': {
    methods: ["PATCH"],
    pattern: '/invoices/status',
    tokens: [{"old":"/invoices/status","type":0,"val":"invoices","end":""},{"old":"/invoices/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['invoices.set_statuses']['types'],
  },
  'invoices.show': {
    methods: ["GET","HEAD"],
    pattern: '/invoices/:invoiceId',
    tokens: [{"old":"/invoices/:invoiceId","type":0,"val":"invoices","end":""},{"old":"/invoices/:invoiceId","type":1,"val":"invoiceId","end":""}],
    types: placeholder as Registry['invoices.show']['types'],
  },
  'invoices.destroy': {
    methods: ["DELETE"],
    pattern: '/invoices/:invoiceId',
    tokens: [{"old":"/invoices/:invoiceId","type":0,"val":"invoices","end":""},{"old":"/invoices/:invoiceId","type":1,"val":"invoiceId","end":""}],
    types: placeholder as Registry['invoices.destroy']['types'],
  },
  'invoices.set_status': {
    methods: ["PATCH"],
    pattern: '/invoices/:invoiceId/status',
    tokens: [{"old":"/invoices/:invoiceId/status","type":0,"val":"invoices","end":""},{"old":"/invoices/:invoiceId/status","type":1,"val":"invoiceId","end":""},{"old":"/invoices/:invoiceId/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['invoices.set_status']['types'],
  },
  'invoices.set_line_cancelled': {
    methods: ["PATCH"],
    pattern: '/invoices/:invoiceId/lines/:lineIndex',
    tokens: [{"old":"/invoices/:invoiceId/lines/:lineIndex","type":0,"val":"invoices","end":""},{"old":"/invoices/:invoiceId/lines/:lineIndex","type":1,"val":"invoiceId","end":""},{"old":"/invoices/:invoiceId/lines/:lineIndex","type":0,"val":"lines","end":""},{"old":"/invoices/:invoiceId/lines/:lineIndex","type":1,"val":"lineIndex","end":""}],
    types: placeholder as Registry['invoices.set_line_cancelled']['types'],
  },
  'editable_texts.index': {
    methods: ["GET","HEAD"],
    pattern: '/editable_texts',
    tokens: [{"old":"/editable_texts","type":0,"val":"editable_texts","end":""}],
    types: placeholder as Registry['editable_texts.index']['types'],
  },
  'editable_texts.upsert': {
    methods: ["PUT"],
    pattern: '/editable_texts/:id',
    tokens: [{"old":"/editable_texts/:id","type":0,"val":"editable_texts","end":""},{"old":"/editable_texts/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['editable_texts.upsert']['types'],
  },
  'editable_texts.destroy': {
    methods: ["DELETE"],
    pattern: '/editable_texts/:id',
    tokens: [{"old":"/editable_texts/:id","type":0,"val":"editable_texts","end":""},{"old":"/editable_texts/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['editable_texts.destroy']['types'],
  },
  'questions_and_answers.store': {
    methods: ["POST"],
    pattern: '/questions_and_answers',
    tokens: [{"old":"/questions_and_answers","type":0,"val":"questions_and_answers","end":""}],
    types: placeholder as Registry['questions_and_answers.store']['types'],
  },
  'questions_and_answers.update_order': {
    methods: ["PATCH"],
    pattern: '/questions_and_answers/order',
    tokens: [{"old":"/questions_and_answers/order","type":0,"val":"questions_and_answers","end":""},{"old":"/questions_and_answers/order","type":0,"val":"order","end":""}],
    types: placeholder as Registry['questions_and_answers.update_order']['types'],
  },
  'questions_and_answers.update': {
    methods: ["PATCH"],
    pattern: '/questions_and_answers/:id',
    tokens: [{"old":"/questions_and_answers/:id","type":0,"val":"questions_and_answers","end":""},{"old":"/questions_and_answers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['questions_and_answers.update']['types'],
  },
  'questions_and_answers.destroy': {
    methods: ["DELETE"],
    pattern: '/questions_and_answers/:id',
    tokens: [{"old":"/questions_and_answers/:id","type":0,"val":"questions_and_answers","end":""},{"old":"/questions_and_answers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['questions_and_answers.destroy']['types'],
  },
  'companies.index': {
    methods: ["GET","HEAD"],
    pattern: '/companies',
    tokens: [{"old":"/companies","type":0,"val":"companies","end":""}],
    types: placeholder as Registry['companies.index']['types'],
  },
  'companies.store': {
    methods: ["POST"],
    pattern: '/companies',
    tokens: [{"old":"/companies","type":0,"val":"companies","end":""}],
    types: placeholder as Registry['companies.store']['types'],
  },
  'companies.destroy': {
    methods: ["DELETE"],
    pattern: '/companies/:companyId',
    tokens: [{"old":"/companies/:companyId","type":0,"val":"companies","end":""},{"old":"/companies/:companyId","type":1,"val":"companyId","end":""}],
    types: placeholder as Registry['companies.destroy']['types'],
  },
  'reminders.count_recipients': {
    methods: ["POST"],
    pattern: '/reminders/count_recipients',
    tokens: [{"old":"/reminders/count_recipients","type":0,"val":"reminders","end":""},{"old":"/reminders/count_recipients","type":0,"val":"count_recipients","end":""}],
    types: placeholder as Registry['reminders.count_recipients']['types'],
  },
  'reminders.send': {
    methods: ["POST"],
    pattern: '/reminders/send',
    tokens: [{"old":"/reminders/send","type":0,"val":"reminders","end":""},{"old":"/reminders/send","type":0,"val":"send","end":""}],
    types: placeholder as Registry['reminders.send']['types'],
  },
  'dispatch.email_templates': {
    methods: ["GET","HEAD"],
    pattern: '/dispatch/email_templates',
    tokens: [{"old":"/dispatch/email_templates","type":0,"val":"dispatch","end":""},{"old":"/dispatch/email_templates","type":0,"val":"email_templates","end":""}],
    types: placeholder as Registry['dispatch.email_templates']['types'],
  },
  'dispatch.store': {
    methods: ["POST"],
    pattern: '/dispatch',
    tokens: [{"old":"/dispatch","type":0,"val":"dispatch","end":""}],
    types: placeholder as Registry['dispatch.store']['types'],
  },
  'reports.customer_items': {
    methods: ["GET","HEAD"],
    pattern: '/reports/customer_items',
    tokens: [{"old":"/reports/customer_items","type":0,"val":"reports","end":""},{"old":"/reports/customer_items","type":0,"val":"customer_items","end":""}],
    types: placeholder as Registry['reports.customer_items']['types'],
  },
  'reports.orders': {
    methods: ["GET","HEAD"],
    pattern: '/reports/orders',
    tokens: [{"old":"/reports/orders","type":0,"val":"reports","end":""},{"old":"/reports/orders","type":0,"val":"orders","end":""}],
    types: placeholder as Registry['reports.orders']['types'],
  },
  'reports.payments': {
    methods: ["GET","HEAD"],
    pattern: '/reports/payments',
    tokens: [{"old":"/reports/payments","type":0,"val":"reports","end":""},{"old":"/reports/payments","type":0,"val":"payments","end":""}],
    types: placeholder as Registry['reports.payments']['types'],
  },
  'reports.users': {
    methods: ["GET","HEAD"],
    pattern: '/reports/users',
    tokens: [{"old":"/reports/users","type":0,"val":"reports","end":""},{"old":"/reports/users","type":0,"val":"users","end":""}],
    types: placeholder as Registry['reports.users']['types'],
  },
  'unique_ids.token': {
    methods: ["GET","HEAD"],
    pattern: '/unique_ids/token',
    tokens: [{"old":"/unique_ids/token","type":0,"val":"unique_ids","end":""},{"old":"/unique_ids/token","type":0,"val":"token","end":""}],
    types: placeholder as Registry['unique_ids.token']['types'],
  },
  'users.search': {
    methods: ["GET","HEAD"],
    pattern: '/users/search',
    tokens: [{"old":"/users/search","type":0,"val":"users","end":""},{"old":"/users/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['users.search']['types'],
  },
  'users.show': {
    methods: ["GET","HEAD"],
    pattern: '/users/:detailsId',
    tokens: [{"old":"/users/:detailsId","type":0,"val":"users","end":""},{"old":"/users/:detailsId","type":1,"val":"detailsId","end":""}],
    types: placeholder as Registry['users.show']['types'],
  },
  'users.update': {
    methods: ["PATCH"],
    pattern: '/users/:detailsId',
    tokens: [{"old":"/users/:detailsId","type":0,"val":"users","end":""},{"old":"/users/:detailsId","type":1,"val":"detailsId","end":""}],
    types: placeholder as Registry['users.update']['types'],
  },
  'users.confirm_email': {
    methods: ["POST"],
    pattern: '/users/:detailsId/confirm_email',
    tokens: [{"old":"/users/:detailsId/confirm_email","type":0,"val":"users","end":""},{"old":"/users/:detailsId/confirm_email","type":1,"val":"detailsId","end":""},{"old":"/users/:detailsId/confirm_email","type":0,"val":"confirm_email","end":""}],
    types: placeholder as Registry['users.confirm_email']['types'],
  },
  'customer_items.for_customer': {
    methods: ["GET","HEAD"],
    pattern: '/users/:detailsId/customer_items',
    tokens: [{"old":"/users/:detailsId/customer_items","type":0,"val":"users","end":""},{"old":"/users/:detailsId/customer_items","type":1,"val":"detailsId","end":""},{"old":"/users/:detailsId/customer_items","type":0,"val":"customer_items","end":""}],
    types: placeholder as Registry['customer_items.for_customer']['types'],
  },
  'orders.for_customer': {
    methods: ["GET","HEAD"],
    pattern: '/users/:detailsId/orders',
    tokens: [{"old":"/users/:detailsId/orders","type":0,"val":"users","end":""},{"old":"/users/:detailsId/orders","type":1,"val":"detailsId","end":""},{"old":"/users/:detailsId/orders","type":0,"val":"orders","end":""}],
    types: placeholder as Registry['orders.for_customer']['types'],
  },
  'orders.placed_for_customer': {
    methods: ["GET","HEAD"],
    pattern: '/users/:detailsId/placed_orders',
    tokens: [{"old":"/users/:detailsId/placed_orders","type":0,"val":"users","end":""},{"old":"/users/:detailsId/placed_orders","type":1,"val":"detailsId","end":""},{"old":"/users/:detailsId/placed_orders","type":0,"val":"placed_orders","end":""}],
    types: placeholder as Registry['orders.placed_for_customer']['types'],
  },
  'matches.for_customer': {
    methods: ["GET","HEAD"],
    pattern: '/users/:detailsId/matches',
    tokens: [{"old":"/users/:detailsId/matches","type":0,"val":"users","end":""},{"old":"/users/:detailsId/matches","type":1,"val":"detailsId","end":""},{"old":"/users/:detailsId/matches","type":0,"val":"matches","end":""}],
    types: placeholder as Registry['matches.for_customer']['types'],
  },
  'message_logs.for_customer': {
    methods: ["GET","HEAD"],
    pattern: '/users/:detailsId/message_logs',
    tokens: [{"old":"/users/:detailsId/message_logs","type":0,"val":"users","end":""},{"old":"/users/:detailsId/message_logs","type":1,"val":"detailsId","end":""},{"old":"/users/:detailsId/message_logs","type":0,"val":"message_logs","end":""}],
    types: placeholder as Registry['message_logs.for_customer']['types'],
  },
  'signatures.show': {
    methods: ["GET","HEAD"],
    pattern: '/signatures/:detailsId',
    tokens: [{"old":"/signatures/:detailsId","type":0,"val":"signatures","end":""},{"old":"/signatures/:detailsId","type":1,"val":"detailsId","end":""}],
    types: placeholder as Registry['signatures.show']['types'],
  },
  'signatures.send_link': {
    methods: ["POST"],
    pattern: '/signatures/:detailsId/send',
    tokens: [{"old":"/signatures/:detailsId/send","type":0,"val":"signatures","end":""},{"old":"/signatures/:detailsId/send","type":1,"val":"detailsId","end":""},{"old":"/signatures/:detailsId/send","type":0,"val":"send","end":""}],
    types: placeholder as Registry['signatures.send_link']['types'],
  },
  'orders.index': {
    methods: ["GET","HEAD"],
    pattern: '/orders',
    tokens: [{"old":"/orders","type":0,"val":"orders","end":""}],
    types: placeholder as Registry['orders.index']['types'],
  },
  'orders.export': {
    methods: ["GET","HEAD"],
    pattern: '/orders/export',
    tokens: [{"old":"/orders/export","type":0,"val":"orders","end":""},{"old":"/orders/export","type":0,"val":"export","end":""}],
    types: placeholder as Registry['orders.export']['types'],
  },
  'orders.export_bring': {
    methods: ["GET","HEAD"],
    pattern: '/orders/export/bring',
    tokens: [{"old":"/orders/export/bring","type":0,"val":"orders","end":""},{"old":"/orders/export/bring","type":0,"val":"export","end":""},{"old":"/orders/export/bring","type":0,"val":"bring","end":""}],
    types: placeholder as Registry['orders.export_bring']['types'],
  },
  'orders.show': {
    methods: ["GET","HEAD"],
    pattern: '/orders/:orderId',
    tokens: [{"old":"/orders/:orderId","type":0,"val":"orders","end":""},{"old":"/orders/:orderId","type":1,"val":"orderId","end":""}],
    types: placeholder as Registry['orders.show']['types'],
  },
  'orders.update_branch': {
    methods: ["PATCH"],
    pattern: '/orders/:orderId/branch',
    tokens: [{"old":"/orders/:orderId/branch","type":0,"val":"orders","end":""},{"old":"/orders/:orderId/branch","type":1,"val":"orderId","end":""},{"old":"/orders/:orderId/branch","type":0,"val":"branch","end":""}],
    types: placeholder as Registry['orders.update_branch']['types'],
  },
  'orders.update_item_deadline': {
    methods: ["PATCH"],
    pattern: '/orders/:orderId/item_deadline',
    tokens: [{"old":"/orders/:orderId/item_deadline","type":0,"val":"orders","end":""},{"old":"/orders/:orderId/item_deadline","type":1,"val":"orderId","end":""},{"old":"/orders/:orderId/item_deadline","type":0,"val":"item_deadline","end":""}],
    types: placeholder as Registry['orders.update_item_deadline']['types'],
  },
  'orders.destroy': {
    methods: ["DELETE"],
    pattern: '/orders/:orderId',
    tokens: [{"old":"/orders/:orderId","type":0,"val":"orders","end":""},{"old":"/orders/:orderId","type":1,"val":"orderId","end":""}],
    types: placeholder as Registry['orders.destroy']['types'],
  },
  'stand_cart.resolve_line': {
    methods: ["POST"],
    pattern: '/stand_cart/lines',
    tokens: [{"old":"/stand_cart/lines","type":0,"val":"stand_cart","end":""},{"old":"/stand_cart/lines","type":0,"val":"lines","end":""}],
    types: placeholder as Registry['stand_cart.resolve_line']['types'],
  },
  'stand_cart.refund_plan': {
    methods: ["POST"],
    pattern: '/stand_cart/refund_plan',
    tokens: [{"old":"/stand_cart/refund_plan","type":0,"val":"stand_cart","end":""},{"old":"/stand_cart/refund_plan","type":0,"val":"refund_plan","end":""}],
    types: placeholder as Registry['stand_cart.refund_plan']['types'],
  },
  'stand_cart.checkout': {
    methods: ["POST"],
    pattern: '/stand_cart/checkout',
    tokens: [{"old":"/stand_cart/checkout","type":0,"val":"stand_cart","end":""},{"old":"/stand_cart/checkout","type":0,"val":"checkout","end":""}],
    types: placeholder as Registry['stand_cart.checkout']['types'],
  },
  'stand_cart.status': {
    methods: ["GET","HEAD"],
    pattern: '/stand_cart/:orderId/status',
    tokens: [{"old":"/stand_cart/:orderId/status","type":0,"val":"stand_cart","end":""},{"old":"/stand_cart/:orderId/status","type":1,"val":"orderId","end":""},{"old":"/stand_cart/:orderId/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['stand_cart.status']['types'],
  },
  'stand_cart.cancel': {
    methods: ["POST"],
    pattern: '/stand_cart/:orderId/cancel',
    tokens: [{"old":"/stand_cart/:orderId/cancel","type":0,"val":"stand_cart","end":""},{"old":"/stand_cart/:orderId/cancel","type":1,"val":"orderId","end":""},{"old":"/stand_cart/:orderId/cancel","type":0,"val":"cancel","end":""}],
    types: placeholder as Registry['stand_cart.cancel']['types'],
  },
  'bulk_collection.collect': {
    methods: ["POST"],
    pattern: '/bulk_collection',
    tokens: [{"old":"/bulk_collection","type":0,"val":"bulk_collection","end":""}],
    types: placeholder as Registry['bulk_collection.collect']['types'],
  },
  'bulk_collection.show': {
    methods: ["GET","HEAD"],
    pattern: '/bulk_collection/:blid',
    tokens: [{"old":"/bulk_collection/:blid","type":0,"val":"bulk_collection","end":""},{"old":"/bulk_collection/:blid","type":1,"val":"blid","end":""}],
    types: placeholder as Registry['bulk_collection.show']['types'],
  },
  'blids.index': {
    methods: ["GET","HEAD"],
    pattern: '/blids',
    tokens: [{"old":"/blids","type":0,"val":"blids","end":""}],
    types: placeholder as Registry['blids.index']['types'],
  },
  'blids.register': {
    methods: ["POST"],
    pattern: '/blids/register',
    tokens: [{"old":"/blids/register","type":0,"val":"blids","end":""},{"old":"/blids/register","type":0,"val":"register","end":""}],
    types: placeholder as Registry['blids.register']['types'],
  },
  'blids.register_one': {
    methods: ["POST"],
    pattern: '/blids/register_one',
    tokens: [{"old":"/blids/register_one","type":0,"val":"blids","end":""},{"old":"/blids/register_one","type":0,"val":"register_one","end":""}],
    types: placeholder as Registry['blids.register_one']['types'],
  },
  'blids.update_active_item': {
    methods: ["PATCH"],
    pattern: '/blids/active_item',
    tokens: [{"old":"/blids/active_item","type":0,"val":"blids","end":""},{"old":"/blids/active_item","type":0,"val":"active_item","end":""}],
    types: placeholder as Registry['blids.update_active_item']['types'],
  },
  'blids.show': {
    methods: ["GET","HEAD"],
    pattern: '/blids/:blid',
    tokens: [{"old":"/blids/:blid","type":0,"val":"blids","end":""},{"old":"/blids/:blid","type":1,"val":"blid","end":""}],
    types: placeholder as Registry['blids.show']['types'],
  },
  'blids.show_link': {
    methods: ["GET","HEAD"],
    pattern: '/blids/:blid/link',
    tokens: [{"old":"/blids/:blid/link","type":0,"val":"blids","end":""},{"old":"/blids/:blid/link","type":1,"val":"blid","end":""},{"old":"/blids/:blid/link","type":0,"val":"link","end":""}],
    types: placeholder as Registry['blids.show_link']['types'],
  },
  'blids.relink': {
    methods: ["PATCH"],
    pattern: '/blids/:blid/item',
    tokens: [{"old":"/blids/:blid/item","type":0,"val":"blids","end":""},{"old":"/blids/:blid/item","type":1,"val":"blid","end":""},{"old":"/blids/:blid/item","type":0,"val":"item","end":""}],
    types: placeholder as Registry['blids.relink']['types'],
  },
  'blids.destroy': {
    methods: ["DELETE"],
    pattern: '/blids/:blid',
    tokens: [{"old":"/blids/:blid","type":0,"val":"blids","end":""},{"old":"/blids/:blid","type":1,"val":"blid","end":""}],
    types: placeholder as Registry['blids.destroy']['types'],
  },
  'unique_ids.label': {
    methods: ["GET","HEAD"],
    pattern: '/unique_ids/:blid/label',
    tokens: [{"old":"/unique_ids/:blid/label","type":0,"val":"unique_ids","end":""},{"old":"/unique_ids/:blid/label","type":1,"val":"blid","end":""},{"old":"/unique_ids/:blid/label","type":0,"val":"label","end":""}],
    types: placeholder as Registry['unique_ids.label']['types'],
  },
  'matches.show': {
    methods: ["GET","HEAD"],
    pattern: '/matches/:matchId',
    tokens: [{"old":"/matches/:matchId","type":0,"val":"matches","end":""},{"old":"/matches/:matchId","type":1,"val":"matchId","end":""}],
    types: placeholder as Registry['matches.show']['types'],
  },
  'match_rounds.index': {
    methods: ["GET","HEAD"],
    pattern: '/match_rounds',
    tokens: [{"old":"/match_rounds","type":0,"val":"match_rounds","end":""}],
    types: placeholder as Registry['match_rounds.index']['types'],
  },
  'match_rounds.matches': {
    methods: ["GET","HEAD"],
    pattern: '/match_rounds/:id/matches',
    tokens: [{"old":"/match_rounds/:id/matches","type":0,"val":"match_rounds","end":""},{"old":"/match_rounds/:id/matches","type":1,"val":"id","end":""},{"old":"/match_rounds/:id/matches","type":0,"val":"matches","end":""}],
    types: placeholder as Registry['match_rounds.matches']['types'],
  },
  'match_rounds.statistics': {
    methods: ["GET","HEAD"],
    pattern: '/match_rounds/:id/statistics',
    tokens: [{"old":"/match_rounds/:id/statistics","type":0,"val":"match_rounds","end":""},{"old":"/match_rounds/:id/statistics","type":1,"val":"id","end":""},{"old":"/match_rounds/:id/statistics","type":0,"val":"statistics","end":""}],
    types: placeholder as Registry['match_rounds.statistics']['types'],
  },
  'match_rounds.plan_metrics': {
    methods: ["GET","HEAD"],
    pattern: '/match_rounds/:id/plan_metrics',
    tokens: [{"old":"/match_rounds/:id/plan_metrics","type":0,"val":"match_rounds","end":""},{"old":"/match_rounds/:id/plan_metrics","type":1,"val":"id","end":""},{"old":"/match_rounds/:id/plan_metrics","type":0,"val":"plan_metrics","end":""}],
    types: placeholder as Registry['match_rounds.plan_metrics']['types'],
  },
  'items.index': {
    methods: ["GET","HEAD"],
    pattern: '/items',
    tokens: [{"old":"/items","type":0,"val":"items","end":""}],
    types: placeholder as Registry['items.index']['types'],
  },
  'items.show_by_isbn': {
    methods: ["GET","HEAD"],
    pattern: '/items/by_isbn/:isbn',
    tokens: [{"old":"/items/by_isbn/:isbn","type":0,"val":"items","end":""},{"old":"/items/by_isbn/:isbn","type":0,"val":"by_isbn","end":""},{"old":"/items/by_isbn/:isbn","type":1,"val":"isbn","end":""}],
    types: placeholder as Registry['items.show_by_isbn']['types'],
  },
  'waiting_list_customers.index': {
    methods: ["GET","HEAD"],
    pattern: '/waiting_list_customers',
    tokens: [{"old":"/waiting_list_customers","type":0,"val":"waiting_list_customers","end":""}],
    types: placeholder as Registry['waiting_list_customers.index']['types'],
  },
  'waiting_list_customers.store': {
    methods: ["POST"],
    pattern: '/waiting_list_customers',
    tokens: [{"old":"/waiting_list_customers","type":0,"val":"waiting_list_customers","end":""}],
    types: placeholder as Registry['waiting_list_customers.store']['types'],
  },
  'waiting_list_customers.destroy': {
    methods: ["DELETE"],
    pattern: '/waiting_list_customers/:id',
    tokens: [{"old":"/waiting_list_customers/:id","type":0,"val":"waiting_list_customers","end":""},{"old":"/waiting_list_customers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['waiting_list_customers.destroy']['types'],
  },
  'message_logs.feed': {
    methods: ["GET","HEAD"],
    pattern: '/message_logs/feed',
    tokens: [{"old":"/message_logs/feed","type":0,"val":"message_logs","end":""},{"old":"/message_logs/feed","type":0,"val":"feed","end":""}],
    types: placeholder as Registry['message_logs.feed']['types'],
  },
  'message_logs.metrics': {
    methods: ["GET","HEAD"],
    pattern: '/message_logs/metrics',
    tokens: [{"old":"/message_logs/metrics","type":0,"val":"message_logs","end":""},{"old":"/message_logs/metrics","type":0,"val":"metrics","end":""}],
    types: placeholder as Registry['message_logs.metrics']['types'],
  },
  'message_logs.sendouts': {
    methods: ["GET","HEAD"],
    pattern: '/message_logs/sendouts',
    tokens: [{"old":"/message_logs/sendouts","type":0,"val":"message_logs","end":""},{"old":"/message_logs/sendouts","type":0,"val":"sendouts","end":""}],
    types: placeholder as Registry['message_logs.sendouts']['types'],
  },
} as const satisfies Record<string, AdonisEndpoint>

export { routes }

export const registry = {
  routes,
  $tree: {} as ApiDefinition,
}

declare module '@tuyau/core/types' {
  export interface UserRegistry {
    routes: typeof routes
    $tree: ApiDefinition
  }
}
