/* eslint-disable prettier/prettier */
import type { AdonisEndpoint } from '@tuyau/core/types'
import type { Registry } from './schema.d.ts'
import type { ApiDefinition } from './tree.d.ts'

const placeholder: any = {}

const routes = {
  'tokens.legacy_token': {
    methods: ["POST"],
    pattern: '/token',
    tokens: [{"old":"/token","type":0,"val":"token","end":""}],
    types: placeholder as Registry['tokens.legacy_token']['types'],
  },
  'tokens.token': {
    methods: ["POST"],
    pattern: '/v2/token',
    tokens: [{"old":"/v2/token","type":0,"val":"v2","end":""},{"old":"/v2/token","type":0,"val":"token","end":""}],
    types: placeholder as Registry['tokens.token']['types'],
  },
  'vipps.redirect': {
    methods: ["GET","HEAD"],
    pattern: '/auth/vipps/redirect',
    tokens: [{"old":"/auth/vipps/redirect","type":0,"val":"auth","end":""},{"old":"/auth/vipps/redirect","type":0,"val":"vipps","end":""},{"old":"/auth/vipps/redirect","type":0,"val":"redirect","end":""}],
    types: placeholder as Registry['vipps.redirect']['types'],
  },
  'vipps.callback': {
    methods: ["GET","HEAD"],
    pattern: '/auth/vipps/callback',
    tokens: [{"old":"/auth/vipps/callback","type":0,"val":"auth","end":""},{"old":"/auth/vipps/callback","type":0,"val":"vipps","end":""},{"old":"/auth/vipps/callback","type":0,"val":"callback","end":""}],
    types: placeholder as Registry['vipps.callback']['types'],
  },
  'local.login': {
    methods: ["POST"],
    pattern: '/auth/local/login',
    tokens: [{"old":"/auth/local/login","type":0,"val":"auth","end":""},{"old":"/auth/local/login","type":0,"val":"local","end":""},{"old":"/auth/local/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['local.login']['types'],
  },
  'local.register': {
    methods: ["POST"],
    pattern: '/auth/local/register',
    tokens: [{"old":"/auth/local/register","type":0,"val":"auth","end":""},{"old":"/auth/local/register","type":0,"val":"local","end":""},{"old":"/auth/local/register","type":0,"val":"register","end":""}],
    types: placeholder as Registry['local.register']['types'],
  },
  'password_reset.request_password_reset': {
    methods: ["POST"],
    pattern: '/forgot_password',
    tokens: [{"old":"/forgot_password","type":0,"val":"forgot_password","end":""}],
    types: placeholder as Registry['password_reset.request_password_reset']['types'],
  },
  'password_reset.validate_password_reset': {
    methods: ["GET","HEAD"],
    pattern: '/password_reset/validate/:id/:token',
    tokens: [{"old":"/password_reset/validate/:id/:token","type":0,"val":"password_reset","end":""},{"old":"/password_reset/validate/:id/:token","type":0,"val":"validate","end":""},{"old":"/password_reset/validate/:id/:token","type":1,"val":"id","end":""},{"old":"/password_reset/validate/:id/:token","type":1,"val":"token","end":""}],
    types: placeholder as Registry['password_reset.validate_password_reset']['types'],
  },
  'password_reset.reset_password': {
    methods: ["POST"],
    pattern: '/password_reset/:id',
    tokens: [{"old":"/password_reset/:id","type":0,"val":"password_reset","end":""},{"old":"/password_reset/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['password_reset.reset_password']['types'],
  },
  'waiting_list_customer.get_all': {
    methods: ["GET","HEAD"],
    pattern: '/waiting_list_customer',
    tokens: [{"old":"/waiting_list_customer","type":0,"val":"waiting_list_customer","end":""}],
    types: placeholder as Registry['waiting_list_customer.get_all']['types'],
  },
  'waiting_list_customer.create': {
    methods: ["POST"],
    pattern: '/waiting_list_customer',
    tokens: [{"old":"/waiting_list_customer","type":0,"val":"waiting_list_customer","end":""}],
    types: placeholder as Registry['waiting_list_customer.create']['types'],
  },
  'waiting_list_customer.destroy': {
    methods: ["DELETE"],
    pattern: '/waiting_list_customer/:id',
    tokens: [{"old":"/waiting_list_customer/:id","type":0,"val":"waiting_list_customer","end":""},{"old":"/waiting_list_customer/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['waiting_list_customer.destroy']['types'],
  },
  'reminders.count_recipients': {
    methods: ["POST"],
    pattern: '/reminders/count_recipients',
    tokens: [{"old":"/reminders/count_recipients","type":0,"val":"reminders","end":""},{"old":"/reminders/count_recipients","type":0,"val":"count_recipients","end":""}],
    types: placeholder as Registry['reminders.count_recipients']['types'],
  },
  'reminders.remind': {
    methods: ["POST"],
    pattern: '/reminders/send',
    tokens: [{"old":"/reminders/send","type":0,"val":"reminders","end":""},{"old":"/reminders/send","type":0,"val":"send","end":""}],
    types: placeholder as Registry['reminders.remind']['types'],
  },
  'branches.get_public': {
    methods: ["GET","HEAD"],
    pattern: '/v2/branches/public',
    tokens: [{"old":"/v2/branches/public","type":0,"val":"v2","end":""},{"old":"/v2/branches/public","type":0,"val":"branches","end":""},{"old":"/v2/branches/public","type":0,"val":"public","end":""}],
    types: placeholder as Registry['branches.get_public']['types'],
  },
  'branches.get_all': {
    methods: ["GET","HEAD"],
    pattern: '/v2/branches',
    tokens: [{"old":"/v2/branches","type":0,"val":"v2","end":""},{"old":"/v2/branches","type":0,"val":"branches","end":""}],
    types: placeholder as Registry['branches.get_all']['types'],
  },
  'branches.get_by_id': {
    methods: ["GET","HEAD"],
    pattern: '/v2/branches/:branchId',
    tokens: [{"old":"/v2/branches/:branchId","type":0,"val":"v2","end":""},{"old":"/v2/branches/:branchId","type":0,"val":"branches","end":""},{"old":"/v2/branches/:branchId","type":1,"val":"branchId","end":""}],
    types: placeholder as Registry['branches.get_by_id']['types'],
  },
  'branches.add': {
    methods: ["POST"],
    pattern: '/v2/branches',
    tokens: [{"old":"/v2/branches","type":0,"val":"v2","end":""},{"old":"/v2/branches","type":0,"val":"branches","end":""}],
    types: placeholder as Registry['branches.add']['types'],
  },
  'branches.update': {
    methods: ["PATCH"],
    pattern: '/v2/branches',
    tokens: [{"old":"/v2/branches","type":0,"val":"v2","end":""},{"old":"/v2/branches","type":0,"val":"branches","end":""}],
    types: placeholder as Registry['branches.update']['types'],
  },
  'branch_upload.upload_memberships': {
    methods: ["POST"],
    pattern: '/v2/branches/memberships',
    tokens: [{"old":"/v2/branches/memberships","type":0,"val":"v2","end":""},{"old":"/v2/branches/memberships","type":0,"val":"branches","end":""},{"old":"/v2/branches/memberships","type":0,"val":"memberships","end":""}],
    types: placeholder as Registry['branch_upload.upload_memberships']['types'],
  },
  'branch_upload.upload_subject_choices': {
    methods: ["POST"],
    pattern: '/v2/branches/subject_choices',
    tokens: [{"old":"/v2/branches/subject_choices","type":0,"val":"v2","end":""},{"old":"/v2/branches/subject_choices","type":0,"val":"branches","end":""},{"old":"/v2/branches/subject_choices","type":0,"val":"subject_choices","end":""}],
    types: placeholder as Registry['branch_upload.upload_subject_choices']['types'],
  },
  'branch_relationship.update': {
    methods: ["PATCH"],
    pattern: '/v2/branches/relationships',
    tokens: [{"old":"/v2/branches/relationships","type":0,"val":"v2","end":""},{"old":"/v2/branches/relationships","type":0,"val":"branches","end":""},{"old":"/v2/branches/relationships","type":0,"val":"relationships","end":""}],
    types: placeholder as Registry['branch_relationship.update']['types'],
  },
  'branch_membership.get_members': {
    methods: ["GET","HEAD"],
    pattern: '/v2/branches/memberships/:branchId',
    tokens: [{"old":"/v2/branches/memberships/:branchId","type":0,"val":"v2","end":""},{"old":"/v2/branches/memberships/:branchId","type":0,"val":"branches","end":""},{"old":"/v2/branches/memberships/:branchId","type":0,"val":"memberships","end":""},{"old":"/v2/branches/memberships/:branchId","type":1,"val":"branchId","end":""}],
    types: placeholder as Registry['branch_membership.get_members']['types'],
  },
  'branch_membership.update_membership': {
    methods: ["PATCH"],
    pattern: '/branches/memberships',
    tokens: [{"old":"/branches/memberships","type":0,"val":"branches","end":""},{"old":"/branches/memberships","type":0,"val":"memberships","end":""}],
    types: placeholder as Registry['branch_membership.update_membership']['types'],
  },
  'branch_membership.remove_direct_members': {
    methods: ["DELETE"],
    pattern: '/branches/memberships/direct/:branchId',
    tokens: [{"old":"/branches/memberships/direct/:branchId","type":0,"val":"branches","end":""},{"old":"/branches/memberships/direct/:branchId","type":0,"val":"memberships","end":""},{"old":"/branches/memberships/direct/:branchId","type":0,"val":"direct","end":""},{"old":"/branches/memberships/direct/:branchId","type":1,"val":"branchId","end":""}],
    types: placeholder as Registry['branch_membership.remove_direct_members']['types'],
  },
  'branch_membership.remove_indirect_members': {
    methods: ["DELETE"],
    pattern: '/branches/memberships/indirect/:branchId',
    tokens: [{"old":"/branches/memberships/indirect/:branchId","type":0,"val":"branches","end":""},{"old":"/branches/memberships/indirect/:branchId","type":0,"val":"memberships","end":""},{"old":"/branches/memberships/indirect/:branchId","type":0,"val":"indirect","end":""},{"old":"/branches/memberships/indirect/:branchId","type":1,"val":"branchId","end":""}],
    types: placeholder as Registry['branch_membership.remove_indirect_members']['types'],
  },
  'orders.get_open_orders': {
    methods: ["GET","HEAD"],
    pattern: '/v2/orders/open_orders',
    tokens: [{"old":"/v2/orders/open_orders","type":0,"val":"v2","end":""},{"old":"/v2/orders/open_orders","type":0,"val":"orders","end":""},{"old":"/v2/orders/open_orders","type":0,"val":"open_orders","end":""}],
    types: placeholder as Registry['orders.get_open_orders']['types'],
  },
  'orders.get_placed_orders': {
    methods: ["GET","HEAD"],
    pattern: '/v2/orders/placed_orders/:detailsId',
    tokens: [{"old":"/v2/orders/placed_orders/:detailsId","type":0,"val":"v2","end":""},{"old":"/v2/orders/placed_orders/:detailsId","type":0,"val":"orders","end":""},{"old":"/v2/orders/placed_orders/:detailsId","type":0,"val":"placed_orders","end":""},{"old":"/v2/orders/placed_orders/:detailsId","type":1,"val":"detailsId","end":""}],
    types: placeholder as Registry['orders.get_placed_orders']['types'],
  },
  'orders.cancel_order_item': {
    methods: ["POST"],
    pattern: '/v2/orders/cancel_order_item',
    tokens: [{"old":"/v2/orders/cancel_order_item","type":0,"val":"v2","end":""},{"old":"/v2/orders/cancel_order_item","type":0,"val":"orders","end":""},{"old":"/v2/orders/cancel_order_item","type":0,"val":"cancel_order_item","end":""}],
    types: placeholder as Registry['orders.cancel_order_item']['types'],
  },
  'editable_texts.get': {
    methods: ["GET","HEAD"],
    pattern: '/editable_texts/:id',
    tokens: [{"old":"/editable_texts/:id","type":0,"val":"editable_texts","end":""},{"old":"/editable_texts/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['editable_texts.get']['types'],
  },
  'editable_texts.get_all': {
    methods: ["GET","HEAD"],
    pattern: '/editable_texts',
    tokens: [{"old":"/editable_texts","type":0,"val":"editable_texts","end":""}],
    types: placeholder as Registry['editable_texts.get_all']['types'],
  },
  'editable_texts.upsert': {
    methods: ["PUT"],
    pattern: '/editable_texts/:id',
    tokens: [{"old":"/editable_texts/:id","type":0,"val":"editable_texts","end":""},{"old":"/editable_texts/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['editable_texts.upsert']['types'],
  },
  'editable_texts.destroy': {
    methods: ["DELETE"],
    pattern: '/editable_texts/:id',
    tokens: [{"old":"/editable_texts/:id","type":0,"val":"editable_texts","end":""},{"old":"/editable_texts/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['editable_texts.destroy']['types'],
  },
  'questions_and_answers.get_all': {
    methods: ["GET","HEAD"],
    pattern: '/questions_and_answers',
    tokens: [{"old":"/questions_and_answers","type":0,"val":"questions_and_answers","end":""}],
    types: placeholder as Registry['questions_and_answers.get_all']['types'],
  },
  'questions_and_answers.store': {
    methods: ["POST"],
    pattern: '/questions_and_answers',
    tokens: [{"old":"/questions_and_answers","type":0,"val":"questions_and_answers","end":""}],
    types: placeholder as Registry['questions_and_answers.store']['types'],
  },
  'questions_and_answers.update': {
    methods: ["PATCH"],
    pattern: '/questions_and_answers/:id',
    tokens: [{"old":"/questions_and_answers/:id","type":0,"val":"questions_and_answers","end":""},{"old":"/questions_and_answers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['questions_and_answers.update']['types'],
  },
  'questions_and_answers.destroy': {
    methods: ["DELETE"],
    pattern: '/questions_and_answers/:id',
    tokens: [{"old":"/questions_and_answers/:id","type":0,"val":"questions_and_answers","end":""},{"old":"/questions_and_answers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['questions_and_answers.destroy']['types'],
  },
  'email_verification.send': {
    methods: ["POST"],
    pattern: '/email_verification',
    tokens: [{"old":"/email_verification","type":0,"val":"email_verification","end":""}],
    types: placeholder as Registry['email_verification.send']['types'],
  },
  'email_verification.verify': {
    methods: ["GET","HEAD"],
    pattern: '/email_verification/:id',
    tokens: [{"old":"/email_verification/:id","type":0,"val":"email_verification","end":""},{"old":"/email_verification/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['email_verification.verify']['types'],
  },
  'public_blid_lookup.lookup': {
    methods: ["GET","HEAD"],
    pattern: '/public_blid_lookup/:blid',
    tokens: [{"old":"/public_blid_lookup/:blid","type":0,"val":"public_blid_lookup","end":""},{"old":"/public_blid_lookup/:blid","type":1,"val":"blid","end":""}],
    types: placeholder as Registry['public_blid_lookup.lookup']['types'],
  },
  'matches.generate': {
    methods: ["POST"],
    pattern: '/matches/generate',
    tokens: [{"old":"/matches/generate","type":0,"val":"matches","end":""},{"old":"/matches/generate","type":0,"val":"generate","end":""}],
    types: placeholder as Registry['matches.generate']['types'],
  },
  'matches.notify': {
    methods: ["POST"],
    pattern: '/matches/notify',
    tokens: [{"old":"/matches/notify","type":0,"val":"matches","end":""},{"old":"/matches/notify","type":0,"val":"notify","end":""}],
    types: placeholder as Registry['matches.notify']['types'],
  },
  'matches.lock': {
    methods: ["POST"],
    pattern: '/user_matches/lock',
    tokens: [{"old":"/user_matches/lock","type":0,"val":"user_matches","end":""},{"old":"/user_matches/lock","type":0,"val":"lock","end":""}],
    types: placeholder as Registry['matches.lock']['types'],
  },
  'matches.get_my_matches': {
    methods: ["GET","HEAD"],
    pattern: '/matches/me',
    tokens: [{"old":"/matches/me","type":0,"val":"matches","end":""},{"old":"/matches/me","type":0,"val":"me","end":""}],
    types: placeholder as Registry['matches.get_my_matches']['types'],
  },
  'matches.transfer_item': {
    methods: ["POST"],
    pattern: '/matches/transfer_item',
    tokens: [{"old":"/matches/transfer_item","type":0,"val":"matches","end":""},{"old":"/matches/transfer_item","type":0,"val":"transfer_item","end":""}],
    types: placeholder as Registry['matches.transfer_item']['types'],
  },
  'user_detail.get_by_id': {
    methods: ["GET","HEAD"],
    pattern: '/v2/user_details/id/:detailsId',
    tokens: [{"old":"/v2/user_details/id/:detailsId","type":0,"val":"v2","end":""},{"old":"/v2/user_details/id/:detailsId","type":0,"val":"user_details","end":""},{"old":"/v2/user_details/id/:detailsId","type":0,"val":"id","end":""},{"old":"/v2/user_details/id/:detailsId","type":1,"val":"detailsId","end":""}],
    types: placeholder as Registry['user_detail.get_by_id']['types'],
  },
  'user_detail.search': {
    methods: ["POST"],
    pattern: '/v2/user_details/search',
    tokens: [{"old":"/v2/user_details/search","type":0,"val":"v2","end":""},{"old":"/v2/user_details/search","type":0,"val":"user_details","end":""},{"old":"/v2/user_details/search","type":0,"val":"search","end":""}],
    types: placeholder as Registry['user_detail.search']['types'],
  },
  'user_detail.get_my_details': {
    methods: ["GET","HEAD"],
    pattern: '/v2/user_details/me',
    tokens: [{"old":"/v2/user_details/me","type":0,"val":"v2","end":""},{"old":"/v2/user_details/me","type":0,"val":"user_details","end":""},{"old":"/v2/user_details/me","type":0,"val":"me","end":""}],
    types: placeholder as Registry['user_detail.get_my_details']['types'],
  },
  'user_detail.update_as_customer': {
    methods: ["POST"],
    pattern: '/v2/user_details',
    tokens: [{"old":"/v2/user_details","type":0,"val":"v2","end":""},{"old":"/v2/user_details","type":0,"val":"user_details","end":""}],
    types: placeholder as Registry['user_detail.update_as_customer']['types'],
  },
  'user_detail.update_as_employee': {
    methods: ["POST"],
    pattern: '/v2/employee/user_details/:detailsId',
    tokens: [{"old":"/v2/employee/user_details/:detailsId","type":0,"val":"v2","end":""},{"old":"/v2/employee/user_details/:detailsId","type":0,"val":"employee","end":""},{"old":"/v2/employee/user_details/:detailsId","type":0,"val":"user_details","end":""},{"old":"/v2/employee/user_details/:detailsId","type":1,"val":"detailsId","end":""}],
    types: placeholder as Registry['user_detail.update_as_employee']['types'],
  },
  'customer_items.get_customer_items': {
    methods: ["GET","HEAD"],
    pattern: '/v2/customer_items',
    tokens: [{"old":"/v2/customer_items","type":0,"val":"v2","end":""},{"old":"/v2/customer_items","type":0,"val":"customer_items","end":""}],
    types: placeholder as Registry['customer_items.get_customer_items']['types'],
  },
  'signatures.send_signature_link': {
    methods: ["POST"],
    pattern: '/signatures/send/:detailsId',
    tokens: [{"old":"/signatures/send/:detailsId","type":0,"val":"signatures","end":""},{"old":"/signatures/send/:detailsId","type":0,"val":"send","end":""},{"old":"/signatures/send/:detailsId","type":1,"val":"detailsId","end":""}],
    types: placeholder as Registry['signatures.send_signature_link']['types'],
  },
  'signatures.send_signature_link_as_customer': {
    methods: ["POST"],
    pattern: '/signatures/me/send',
    tokens: [{"old":"/signatures/me/send","type":0,"val":"signatures","end":""},{"old":"/signatures/me/send","type":0,"val":"me","end":""},{"old":"/signatures/me/send","type":0,"val":"send","end":""}],
    types: placeholder as Registry['signatures.send_signature_link_as_customer']['types'],
  },
  'signatures.has_valid_signature': {
    methods: ["GET","HEAD"],
    pattern: '/signatures/valid/:detailsId',
    tokens: [{"old":"/signatures/valid/:detailsId","type":0,"val":"signatures","end":""},{"old":"/signatures/valid/:detailsId","type":0,"val":"valid","end":""},{"old":"/signatures/valid/:detailsId","type":1,"val":"detailsId","end":""}],
    types: placeholder as Registry['signatures.has_valid_signature']['types'],
  },
  'signatures.get_signature': {
    methods: ["GET","HEAD"],
    pattern: '/signatures/get/:detailsId',
    tokens: [{"old":"/signatures/get/:detailsId","type":0,"val":"signatures","end":""},{"old":"/signatures/get/:detailsId","type":0,"val":"get","end":""},{"old":"/signatures/get/:detailsId","type":1,"val":"detailsId","end":""}],
    types: placeholder as Registry['signatures.get_signature']['types'],
  },
  'signatures.sign': {
    methods: ["POST"],
    pattern: '/signatures/sign/:detailsId',
    tokens: [{"old":"/signatures/sign/:detailsId","type":0,"val":"signatures","end":""},{"old":"/signatures/sign/:detailsId","type":0,"val":"sign","end":""},{"old":"/signatures/sign/:detailsId","type":1,"val":"detailsId","end":""}],
    types: placeholder as Registry['signatures.sign']['types'],
  },
  'unique_ids.get_token': {
    methods: ["GET","HEAD"],
    pattern: '/unique_ids/token',
    tokens: [{"old":"/unique_ids/token","type":0,"val":"unique_ids","end":""},{"old":"/unique_ids/token","type":0,"val":"token","end":""}],
    types: placeholder as Registry['unique_ids.get_token']['types'],
  },
  'unique_ids.download_unique_id_pdf': {
    methods: ["GET","HEAD"],
    pattern: '/unique_ids/download_pdf/:token',
    tokens: [{"old":"/unique_ids/download_pdf/:token","type":0,"val":"unique_ids","end":""},{"old":"/unique_ids/download_pdf/:token","type":0,"val":"download_pdf","end":""},{"old":"/unique_ids/download_pdf/:token","type":1,"val":"token","end":""}],
    types: placeholder as Registry['unique_ids.download_unique_id_pdf']['types'],
  },
  'user_provisioning.create_users': {
    methods: ["POST"],
    pattern: '/users/create',
    tokens: [{"old":"/users/create","type":0,"val":"users","end":""},{"old":"/users/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['user_provisioning.create_users']['types'],
  },
  'unique_items.add': {
    methods: ["POST"],
    pattern: '/unique_items/add',
    tokens: [{"old":"/unique_items/add","type":0,"val":"unique_items","end":""},{"old":"/unique_items/add","type":0,"val":"add","end":""}],
    types: placeholder as Registry['unique_items.add']['types'],
  },
  'order_history.get_my_order': {
    methods: ["GET","HEAD"],
    pattern: '/order_history/me/:orderId',
    tokens: [{"old":"/order_history/me/:orderId","type":0,"val":"order_history","end":""},{"old":"/order_history/me/:orderId","type":0,"val":"me","end":""},{"old":"/order_history/me/:orderId","type":1,"val":"orderId","end":""}],
    types: placeholder as Registry['order_history.get_my_order']['types'],
  },
  'order_history.get_my_orders': {
    methods: ["GET","HEAD"],
    pattern: '/order_history/me',
    tokens: [{"old":"/order_history/me","type":0,"val":"order_history","end":""},{"old":"/order_history/me","type":0,"val":"me","end":""}],
    types: placeholder as Registry['order_history.get_my_orders']['types'],
  },
  'checkout.initialize_checkout': {
    methods: ["POST"],
    pattern: '/checkout',
    tokens: [{"old":"/checkout","type":0,"val":"checkout","end":""}],
    types: placeholder as Registry['checkout.initialize_checkout']['types'],
  },
  'kustom_checkout.initialize_checkout': {
    methods: ["POST"],
    pattern: '/v2/checkout',
    tokens: [{"old":"/v2/checkout","type":0,"val":"v2","end":""},{"old":"/v2/checkout","type":0,"val":"checkout","end":""}],
    types: placeholder as Registry['kustom_checkout.initialize_checkout']['types'],
  },
  'kustom_checkout.get_snippet': {
    methods: ["GET","HEAD"],
    pattern: '/v2/checkout/snippet/:orderId',
    tokens: [{"old":"/v2/checkout/snippet/:orderId","type":0,"val":"v2","end":""},{"old":"/v2/checkout/snippet/:orderId","type":0,"val":"checkout","end":""},{"old":"/v2/checkout/snippet/:orderId","type":0,"val":"snippet","end":""},{"old":"/v2/checkout/snippet/:orderId","type":1,"val":"orderId","end":""}],
    types: placeholder as Registry['kustom_checkout.get_snippet']['types'],
  },
  'kustom_checkout.receive_push': {
    methods: ["POST"],
    pattern: '/v2/checkout/push',
    tokens: [{"old":"/v2/checkout/push","type":0,"val":"v2","end":""},{"old":"/v2/checkout/push","type":0,"val":"checkout","end":""},{"old":"/v2/checkout/push","type":0,"val":"push","end":""}],
    types: placeholder as Registry['kustom_checkout.receive_push']['types'],
  },
  'checkout.confirm_checkout': {
    methods: ["POST"],
    pattern: '/checkout/confirm/:orderId',
    tokens: [{"old":"/checkout/confirm/:orderId","type":0,"val":"checkout","end":""},{"old":"/checkout/confirm/:orderId","type":0,"val":"confirm","end":""},{"old":"/checkout/confirm/:orderId","type":1,"val":"orderId","end":""}],
    types: placeholder as Registry['checkout.confirm_checkout']['types'],
  },
  'checkout.handle_vipps_callback': {
    methods: ["POST"],
    pattern: '/checkout/vipps/callback',
    tokens: [{"old":"/checkout/vipps/callback","type":0,"val":"checkout","end":""},{"old":"/checkout/vipps/callback","type":0,"val":"vipps","end":""},{"old":"/checkout/vipps/callback","type":0,"val":"callback","end":""}],
    types: placeholder as Registry['checkout.handle_vipps_callback']['types'],
  },
  'checkout.poll_payment': {
    methods: ["GET","HEAD"],
    pattern: '/checkout/poll/:orderId',
    tokens: [{"old":"/checkout/poll/:orderId","type":0,"val":"checkout","end":""},{"old":"/checkout/poll/:orderId","type":0,"val":"poll","end":""},{"old":"/checkout/poll/:orderId","type":1,"val":"orderId","end":""}],
    types: placeholder as Registry['checkout.poll_payment']['types'],
  },
  'subjects.get_branch_subjects': {
    methods: ["GET","HEAD"],
    pattern: '/subjects/:branchId',
    tokens: [{"old":"/subjects/:branchId","type":0,"val":"subjects","end":""},{"old":"/subjects/:branchId","type":1,"val":"branchId","end":""}],
    types: placeholder as Registry['subjects.get_branch_subjects']['types'],
  },
  'branch_items.get_branch_items': {
    methods: ["GET","HEAD"],
    pattern: '/branch_items/:branchId',
    tokens: [{"old":"/branch_items/:branchId","type":0,"val":"branch_items","end":""},{"old":"/branch_items/:branchId","type":1,"val":"branchId","end":""}],
    types: placeholder as Registry['branch_items.get_branch_items']['types'],
  },
  'branch_items.set_branch_items': {
    methods: ["POST"],
    pattern: '/branch_items',
    tokens: [{"old":"/branch_items","type":0,"val":"branch_items","end":""}],
    types: placeholder as Registry['branch_items.set_branch_items']['types'],
  },
  'postal.lookup_postal_code': {
    methods: ["GET","HEAD"],
    pattern: '/postal/lookup/postal_code/:postalCode',
    tokens: [{"old":"/postal/lookup/postal_code/:postalCode","type":0,"val":"postal","end":""},{"old":"/postal/lookup/postal_code/:postalCode","type":0,"val":"lookup","end":""},{"old":"/postal/lookup/postal_code/:postalCode","type":0,"val":"postal_code","end":""},{"old":"/postal/lookup/postal_code/:postalCode","type":1,"val":"postalCode","end":""}],
    types: placeholder as Registry['postal.lookup_postal_code']['types'],
  },
  'companies.get_companies': {
    methods: ["GET","HEAD"],
    pattern: '/v2/companies',
    tokens: [{"old":"/v2/companies","type":0,"val":"v2","end":""},{"old":"/v2/companies","type":0,"val":"companies","end":""}],
    types: placeholder as Registry['companies.get_companies']['types'],
  },
  'companies.add_company': {
    methods: ["POST"],
    pattern: '/v2/companies',
    tokens: [{"old":"/v2/companies","type":0,"val":"v2","end":""},{"old":"/v2/companies","type":0,"val":"companies","end":""}],
    types: placeholder as Registry['companies.add_company']['types'],
  },
  'companies.delete_company': {
    methods: ["DELETE"],
    pattern: '/v2/companies/:companyId',
    tokens: [{"old":"/v2/companies/:companyId","type":0,"val":"v2","end":""},{"old":"/v2/companies/:companyId","type":0,"val":"companies","end":""},{"old":"/v2/companies/:companyId","type":1,"val":"companyId","end":""}],
    types: placeholder as Registry['companies.delete_company']['types'],
  },
  'opening_hours.get': {
    methods: ["GET","HEAD"],
    pattern: '/opening_hours/branch/:branchId',
    tokens: [{"old":"/opening_hours/branch/:branchId","type":0,"val":"opening_hours","end":""},{"old":"/opening_hours/branch/:branchId","type":0,"val":"branch","end":""},{"old":"/opening_hours/branch/:branchId","type":1,"val":"branchId","end":""}],
    types: placeholder as Registry['opening_hours.get']['types'],
  },
  'opening_hours.add': {
    methods: ["POST"],
    pattern: '/opening_hours',
    tokens: [{"old":"/opening_hours","type":0,"val":"opening_hours","end":""}],
    types: placeholder as Registry['opening_hours.add']['types'],
  },
  'opening_hours.delete': {
    methods: ["DELETE"],
    pattern: '/opening_hours/:id',
    tokens: [{"old":"/opening_hours/:id","type":0,"val":"opening_hours","end":""},{"old":"/opening_hours/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['opening_hours.delete']['types'],
  },
  'items.get': {
    methods: ["GET","HEAD"],
    pattern: '/v2/items',
    tokens: [{"old":"/v2/items","type":0,"val":"v2","end":""},{"old":"/v2/items","type":0,"val":"items","end":""}],
    types: placeholder as Registry['items.get']['types'],
  },
  'items.get_buyback_items': {
    methods: ["GET","HEAD"],
    pattern: '/v2/items/buyback',
    tokens: [{"old":"/v2/items/buyback","type":0,"val":"v2","end":""},{"old":"/v2/items/buyback","type":0,"val":"items","end":""},{"old":"/v2/items/buyback","type":0,"val":"buyback","end":""}],
    types: placeholder as Registry['items.get_buyback_items']['types'],
  },
  'dispatch.get_email_templates': {
    methods: ["GET","HEAD"],
    pattern: '/dispatch/email_templates',
    tokens: [{"old":"/dispatch/email_templates","type":0,"val":"dispatch","end":""},{"old":"/dispatch/email_templates","type":0,"val":"email_templates","end":""}],
    types: placeholder as Registry['dispatch.get_email_templates']['types'],
  },
  'dispatch.create_dispatch': {
    methods: ["POST"],
    pattern: '/dispatch',
    tokens: [{"old":"/dispatch","type":0,"val":"dispatch","end":""}],
    types: placeholder as Registry['dispatch.create_dispatch']['types'],
  },
  'rapid_handout.handout': {
    methods: ["POST"],
    pattern: '/rapid-handout',
    tokens: [{"old":"/rapid-handout","type":0,"val":"rapid-handout","end":""}],
    types: placeholder as Registry['rapid_handout.handout']['types'],
  },
  'reports.get_customer_items_report': {
    methods: ["GET","HEAD"],
    pattern: '/reports/customer_items',
    tokens: [{"old":"/reports/customer_items","type":0,"val":"reports","end":""},{"old":"/reports/customer_items","type":0,"val":"customer_items","end":""}],
    types: placeholder as Registry['reports.get_customer_items_report']['types'],
  },
  'reports.get_orders_report': {
    methods: ["GET","HEAD"],
    pattern: '/reports/orders',
    tokens: [{"old":"/reports/orders","type":0,"val":"reports","end":""},{"old":"/reports/orders","type":0,"val":"orders","end":""}],
    types: placeholder as Registry['reports.get_orders_report']['types'],
  },
  'reports.get_payments_report': {
    methods: ["GET","HEAD"],
    pattern: '/reports/payments',
    tokens: [{"old":"/reports/payments","type":0,"val":"reports","end":""},{"old":"/reports/payments","type":0,"val":"payments","end":""}],
    types: placeholder as Registry['reports.get_payments_report']['types'],
  },
  'reports.get_user_details_report': {
    methods: ["GET","HEAD"],
    pattern: '/reports/user_details',
    tokens: [{"old":"/reports/user_details","type":0,"val":"reports","end":""},{"old":"/reports/user_details","type":0,"val":"user_details","end":""}],
    types: placeholder as Registry['reports.get_user_details_report']['types'],
  },
  'collection.branches.getId': {
    methods: ["GET","HEAD"],
    pattern: '/branches/:id',
    tokens: [{"old":"/branches/:id","type":0,"val":"branches","end":""},{"old":"/branches/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['collection.branches.getId']['types'],
  },
  'collection.branches.getAll': {
    methods: ["GET","HEAD"],
    pattern: '/branches',
    tokens: [{"old":"/branches","type":0,"val":"branches","end":""}],
    types: placeholder as Registry['collection.branches.getAll']['types'],
  },
  'collection.branches.post': {
    methods: ["POST"],
    pattern: '/branches',
    tokens: [{"old":"/branches","type":0,"val":"branches","end":""}],
    types: placeholder as Registry['collection.branches.post']['types'],
  },
  'collection.branches.patch': {
    methods: ["PATCH"],
    pattern: '/branches/:id',
    tokens: [{"old":"/branches/:id","type":0,"val":"branches","end":""},{"old":"/branches/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['collection.branches.patch']['types'],
  },
  'collection.branchitems.getId': {
    methods: ["GET","HEAD"],
    pattern: '/branchitems/:id',
    tokens: [{"old":"/branchitems/:id","type":0,"val":"branchitems","end":""},{"old":"/branchitems/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['collection.branchitems.getId']['types'],
  },
  'collection.branchitems.post': {
    methods: ["POST"],
    pattern: '/branchitems',
    tokens: [{"old":"/branchitems","type":0,"val":"branchitems","end":""}],
    types: placeholder as Registry['collection.branchitems.post']['types'],
  },
  'collection.branchitems.patch': {
    methods: ["PATCH"],
    pattern: '/branchitems/:id',
    tokens: [{"old":"/branchitems/:id","type":0,"val":"branchitems","end":""},{"old":"/branchitems/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['collection.branchitems.patch']['types'],
  },
  'collection.branchitems.getAll': {
    methods: ["GET","HEAD"],
    pattern: '/branchitems',
    tokens: [{"old":"/branchitems","type":0,"val":"branchitems","end":""}],
    types: placeholder as Registry['collection.branchitems.getAll']['types'],
  },
  'collection.branchitems.delete': {
    methods: ["DELETE"],
    pattern: '/branchitems/:id',
    tokens: [{"old":"/branchitems/:id","type":0,"val":"branchitems","end":""},{"old":"/branchitems/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['collection.branchitems.delete']['types'],
  },
  'collection.customeritems.getId': {
    methods: ["GET","HEAD"],
    pattern: '/customeritems/:id',
    tokens: [{"old":"/customeritems/:id","type":0,"val":"customeritems","end":""},{"old":"/customeritems/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['collection.customeritems.getId']['types'],
  },
  'collection.customeritems.patch': {
    methods: ["PATCH"],
    pattern: '/customeritems/:id',
    tokens: [{"old":"/customeritems/:id","type":0,"val":"customeritems","end":""},{"old":"/customeritems/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['collection.customeritems.patch']['types'],
  },
  'collection.customeritems.post': {
    methods: ["POST"],
    pattern: '/customeritems',
    tokens: [{"old":"/customeritems","type":0,"val":"customeritems","end":""}],
    types: placeholder as Registry['collection.customeritems.post']['types'],
  },
  'collection.customeritems.operation.generate-report.post': {
    methods: ["POST"],
    pattern: '/customeritems/generate-report',
    tokens: [{"old":"/customeritems/generate-report","type":0,"val":"customeritems","end":""},{"old":"/customeritems/generate-report","type":0,"val":"generate-report","end":""}],
    types: placeholder as Registry['collection.customeritems.operation.generate-report.post']['types'],
  },
  'collection.customeritems.getAll': {
    methods: ["GET","HEAD"],
    pattern: '/customeritems',
    tokens: [{"old":"/customeritems","type":0,"val":"customeritems","end":""}],
    types: placeholder as Registry['collection.customeritems.getAll']['types'],
  },
  'collection.deliveries.post': {
    methods: ["POST"],
    pattern: '/deliveries',
    tokens: [{"old":"/deliveries","type":0,"val":"deliveries","end":""}],
    types: placeholder as Registry['collection.deliveries.post']['types'],
  },
  'collection.deliveries.getAll': {
    methods: ["GET","HEAD"],
    pattern: '/deliveries',
    tokens: [{"old":"/deliveries","type":0,"val":"deliveries","end":""}],
    types: placeholder as Registry['collection.deliveries.getAll']['types'],
  },
  'collection.deliveries.getId': {
    methods: ["GET","HEAD"],
    pattern: '/deliveries/:id',
    tokens: [{"old":"/deliveries/:id","type":0,"val":"deliveries","end":""},{"old":"/deliveries/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['collection.deliveries.getId']['types'],
  },
  'collection.deliveries.patch': {
    methods: ["PATCH"],
    pattern: '/deliveries/:id',
    tokens: [{"old":"/deliveries/:id","type":0,"val":"deliveries","end":""},{"old":"/deliveries/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['collection.deliveries.patch']['types'],
  },
  'collection.deliveries.delete': {
    methods: ["DELETE"],
    pattern: '/deliveries/:id',
    tokens: [{"old":"/deliveries/:id","type":0,"val":"deliveries","end":""},{"old":"/deliveries/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['collection.deliveries.delete']['types'],
  },
  'collection.items.getId': {
    methods: ["GET","HEAD"],
    pattern: '/items/:id',
    tokens: [{"old":"/items/:id","type":0,"val":"items","end":""},{"old":"/items/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['collection.items.getId']['types'],
  },
  'collection.items.getAll': {
    methods: ["GET","HEAD"],
    pattern: '/items',
    tokens: [{"old":"/items","type":0,"val":"items","end":""}],
    types: placeholder as Registry['collection.items.getAll']['types'],
  },
  'collection.items.post': {
    methods: ["POST"],
    pattern: '/items',
    tokens: [{"old":"/items","type":0,"val":"items","end":""}],
    types: placeholder as Registry['collection.items.post']['types'],
  },
  'collection.items.patch': {
    methods: ["PATCH"],
    pattern: '/items/:id',
    tokens: [{"old":"/items/:id","type":0,"val":"items","end":""},{"old":"/items/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['collection.items.patch']['types'],
  },
  'collection.orders.post': {
    methods: ["POST"],
    pattern: '/orders',
    tokens: [{"old":"/orders","type":0,"val":"orders","end":""}],
    types: placeholder as Registry['collection.orders.post']['types'],
  },
  'collection.orders.delete': {
    methods: ["DELETE"],
    pattern: '/orders/:id',
    tokens: [{"old":"/orders/:id","type":0,"val":"orders","end":""},{"old":"/orders/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['collection.orders.delete']['types'],
  },
  'collection.orders.patch': {
    methods: ["PATCH"],
    pattern: '/orders/:id',
    tokens: [{"old":"/orders/:id","type":0,"val":"orders","end":""},{"old":"/orders/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['collection.orders.patch']['types'],
  },
  'collection.orders.operation.place.patch': {
    methods: ["PATCH"],
    pattern: '/orders/:id/place',
    tokens: [{"old":"/orders/:id/place","type":0,"val":"orders","end":""},{"old":"/orders/:id/place","type":1,"val":"id","end":""},{"old":"/orders/:id/place","type":0,"val":"place","end":""}],
    types: placeholder as Registry['collection.orders.operation.place.patch']['types'],
  },
  'collection.orders.operation.confirm.patch': {
    methods: ["PATCH"],
    pattern: '/orders/:id/confirm',
    tokens: [{"old":"/orders/:id/confirm","type":0,"val":"orders","end":""},{"old":"/orders/:id/confirm","type":1,"val":"id","end":""},{"old":"/orders/:id/confirm","type":0,"val":"confirm","end":""}],
    types: placeholder as Registry['collection.orders.operation.confirm.patch']['types'],
  },
  'collection.orders.getId': {
    methods: ["GET","HEAD"],
    pattern: '/orders/:id',
    tokens: [{"old":"/orders/:id","type":0,"val":"orders","end":""},{"old":"/orders/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['collection.orders.getId']['types'],
  },
  'collection.orders.operation.get_customer_orders.getId': {
    methods: ["GET","HEAD"],
    pattern: '/orders/:id/get_customer_orders',
    tokens: [{"old":"/orders/:id/get_customer_orders","type":0,"val":"orders","end":""},{"old":"/orders/:id/get_customer_orders","type":1,"val":"id","end":""},{"old":"/orders/:id/get_customer_orders","type":0,"val":"get_customer_orders","end":""}],
    types: placeholder as Registry['collection.orders.operation.get_customer_orders.getId']['types'],
  },
  'collection.orders.getAll': {
    methods: ["GET","HEAD"],
    pattern: '/orders',
    tokens: [{"old":"/orders","type":0,"val":"orders","end":""}],
    types: placeholder as Registry['collection.orders.getAll']['types'],
  },
  'collection.payments.post': {
    methods: ["POST"],
    pattern: '/payments',
    tokens: [{"old":"/payments","type":0,"val":"payments","end":""}],
    types: placeholder as Registry['collection.payments.post']['types'],
  },
  'collection.payments.getAll': {
    methods: ["GET","HEAD"],
    pattern: '/payments',
    tokens: [{"old":"/payments","type":0,"val":"payments","end":""}],
    types: placeholder as Registry['collection.payments.getAll']['types'],
  },
  'collection.payments.getId': {
    methods: ["GET","HEAD"],
    pattern: '/payments/:id',
    tokens: [{"old":"/payments/:id","type":0,"val":"payments","end":""},{"old":"/payments/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['collection.payments.getId']['types'],
  },
  'collection.payments.delete': {
    methods: ["DELETE"],
    pattern: '/payments/:id',
    tokens: [{"old":"/payments/:id","type":0,"val":"payments","end":""},{"old":"/payments/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['collection.payments.delete']['types'],
  },
  'collection.userdetails.getId': {
    methods: ["GET","HEAD"],
    pattern: '/userdetails/:id',
    tokens: [{"old":"/userdetails/:id","type":0,"val":"userdetails","end":""},{"old":"/userdetails/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['collection.userdetails.getId']['types'],
  },
  'collection.userdetails.operation.valid.getId': {
    methods: ["GET","HEAD"],
    pattern: '/userdetails/:id/valid',
    tokens: [{"old":"/userdetails/:id/valid","type":0,"val":"userdetails","end":""},{"old":"/userdetails/:id/valid","type":1,"val":"id","end":""},{"old":"/userdetails/:id/valid","type":0,"val":"valid","end":""}],
    types: placeholder as Registry['collection.userdetails.operation.valid.getId']['types'],
  },
  'collection.userdetails.operation.permission.getId': {
    methods: ["GET","HEAD"],
    pattern: '/userdetails/:id/permission',
    tokens: [{"old":"/userdetails/:id/permission","type":0,"val":"userdetails","end":""},{"old":"/userdetails/:id/permission","type":1,"val":"id","end":""},{"old":"/userdetails/:id/permission","type":0,"val":"permission","end":""}],
    types: placeholder as Registry['collection.userdetails.operation.permission.getId']['types'],
  },
  'collection.userdetails.patch': {
    methods: ["PATCH"],
    pattern: '/userdetails/:id',
    tokens: [{"old":"/userdetails/:id","type":0,"val":"userdetails","end":""},{"old":"/userdetails/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['collection.userdetails.patch']['types'],
  },
  'collection.userdetails.delete': {
    methods: ["DELETE"],
    pattern: '/userdetails/:id',
    tokens: [{"old":"/userdetails/:id","type":0,"val":"userdetails","end":""},{"old":"/userdetails/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['collection.userdetails.delete']['types'],
  },
  'collection.userdetails.getAll': {
    methods: ["GET","HEAD"],
    pattern: '/userdetails',
    tokens: [{"old":"/userdetails","type":0,"val":"userdetails","end":""}],
    types: placeholder as Registry['collection.userdetails.getAll']['types'],
  },
  'collection.messages.post': {
    methods: ["POST"],
    pattern: '/messages',
    tokens: [{"old":"/messages","type":0,"val":"messages","end":""}],
    types: placeholder as Registry['collection.messages.post']['types'],
  },
  'collection.messages.operation.sendgrid-events.post': {
    methods: ["POST"],
    pattern: '/messages/sendgrid-events',
    tokens: [{"old":"/messages/sendgrid-events","type":0,"val":"messages","end":""},{"old":"/messages/sendgrid-events","type":0,"val":"sendgrid-events","end":""}],
    types: placeholder as Registry['collection.messages.operation.sendgrid-events.post']['types'],
  },
  'collection.messages.operation.twilio-sms-events.post': {
    methods: ["POST"],
    pattern: '/messages/twilio-sms-events',
    tokens: [{"old":"/messages/twilio-sms-events","type":0,"val":"messages","end":""},{"old":"/messages/twilio-sms-events","type":0,"val":"twilio-sms-events","end":""}],
    types: placeholder as Registry['collection.messages.operation.twilio-sms-events.post']['types'],
  },
  'collection.messages.getAll': {
    methods: ["GET","HEAD"],
    pattern: '/messages',
    tokens: [{"old":"/messages","type":0,"val":"messages","end":""}],
    types: placeholder as Registry['collection.messages.getAll']['types'],
  },
  'collection.messages.getId': {
    methods: ["GET","HEAD"],
    pattern: '/messages/:id',
    tokens: [{"old":"/messages/:id","type":0,"val":"messages","end":""},{"old":"/messages/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['collection.messages.getId']['types'],
  },
  'collection.messages.delete': {
    methods: ["DELETE"],
    pattern: '/messages/:id',
    tokens: [{"old":"/messages/:id","type":0,"val":"messages","end":""},{"old":"/messages/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['collection.messages.delete']['types'],
  },
  'collection.invoices.getId': {
    methods: ["GET","HEAD"],
    pattern: '/invoices/:id',
    tokens: [{"old":"/invoices/:id","type":0,"val":"invoices","end":""},{"old":"/invoices/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['collection.invoices.getId']['types'],
  },
  'collection.invoices.getAll': {
    methods: ["GET","HEAD"],
    pattern: '/invoices',
    tokens: [{"old":"/invoices","type":0,"val":"invoices","end":""}],
    types: placeholder as Registry['collection.invoices.getAll']['types'],
  },
  'collection.invoices.post': {
    methods: ["POST"],
    pattern: '/invoices',
    tokens: [{"old":"/invoices","type":0,"val":"invoices","end":""}],
    types: placeholder as Registry['collection.invoices.post']['types'],
  },
  'collection.invoices.patch': {
    methods: ["PATCH"],
    pattern: '/invoices/:id',
    tokens: [{"old":"/invoices/:id","type":0,"val":"invoices","end":""},{"old":"/invoices/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['collection.invoices.patch']['types'],
  },
  'collection.companies.getAll': {
    methods: ["GET","HEAD"],
    pattern: '/companies',
    tokens: [{"old":"/companies","type":0,"val":"companies","end":""}],
    types: placeholder as Registry['collection.companies.getAll']['types'],
  },
  'collection.companies.getId': {
    methods: ["GET","HEAD"],
    pattern: '/companies/:id',
    tokens: [{"old":"/companies/:id","type":0,"val":"companies","end":""},{"old":"/companies/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['collection.companies.getId']['types'],
  },
  'collection.companies.post': {
    methods: ["POST"],
    pattern: '/companies',
    tokens: [{"old":"/companies","type":0,"val":"companies","end":""}],
    types: placeholder as Registry['collection.companies.post']['types'],
  },
  'collection.companies.patch': {
    methods: ["PATCH"],
    pattern: '/companies/:id',
    tokens: [{"old":"/companies/:id","type":0,"val":"companies","end":""},{"old":"/companies/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['collection.companies.patch']['types'],
  },
  'collection.companies.delete': {
    methods: ["DELETE"],
    pattern: '/companies/:id',
    tokens: [{"old":"/companies/:id","type":0,"val":"companies","end":""},{"old":"/companies/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['collection.companies.delete']['types'],
  },
  'collection.uniqueitems.post': {
    methods: ["POST"],
    pattern: '/uniqueitems',
    tokens: [{"old":"/uniqueitems","type":0,"val":"uniqueitems","end":""}],
    types: placeholder as Registry['collection.uniqueitems.post']['types'],
  },
  'collection.uniqueitems.getId': {
    methods: ["GET","HEAD"],
    pattern: '/uniqueitems/:id',
    tokens: [{"old":"/uniqueitems/:id","type":0,"val":"uniqueitems","end":""},{"old":"/uniqueitems/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['collection.uniqueitems.getId']['types'],
  },
  'collection.uniqueitems.operation.active.getId': {
    methods: ["GET","HEAD"],
    pattern: '/uniqueitems/:id/active',
    tokens: [{"old":"/uniqueitems/:id/active","type":0,"val":"uniqueitems","end":""},{"old":"/uniqueitems/:id/active","type":1,"val":"id","end":""},{"old":"/uniqueitems/:id/active","type":0,"val":"active","end":""}],
    types: placeholder as Registry['collection.uniqueitems.operation.active.getId']['types'],
  },
  'collection.uniqueitems.getAll': {
    methods: ["GET","HEAD"],
    pattern: '/uniqueitems',
    tokens: [{"old":"/uniqueitems","type":0,"val":"uniqueitems","end":""}],
    types: placeholder as Registry['collection.uniqueitems.getAll']['types'],
  },
} as const satisfies Record<string, AdonisEndpoint>

export { routes }

export const registry = {
  routes,
  $tree: {} as ApiDefinition,
}

declare module '@tuyau/core/types' {
  export interface UserRegistry {
    routes: typeof routes
    $tree: ApiDefinition
  }
}
