/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class BookHandoverSchema extends BaseModel {
  static $columns = ['blid', 'createdAt', 'dischargesReceiverObligationId', 'dischargesSenderObligationId', 'fromUserDetailId', 'id', 'itemId', 'occurredAt', 'orderId', 'toUserDetailId', 'updatedAt'] as const
  $columns = BookHandoverSchema.$columns
  @column()
  declare blid: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare dischargesReceiverObligationId: number | null
  @column()
  declare dischargesSenderObligationId: number | null
  @column()
  declare fromUserDetailId: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare itemId: string
  @column.dateTime()
  declare occurredAt: DateTime
  @column()
  declare orderId: string | null
  @column()
  declare toUserDetailId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BranchItemSchema extends BaseModel {
  static $columns = ['branchId', 'buy', 'buyAtBranch', 'categories', 'createdAt', 'id', 'itemId', 'partlyPayment', 'partlyPaymentAtBranch', 'rent', 'rentAtBranch', 'updatedAt'] as const
  $columns = BranchItemSchema.$columns
  @column()
  declare branchId: string
  @column()
  declare buy: boolean
  @column()
  declare buyAtBranch: boolean
  @column()
  declare categories: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare itemId: string
  @column()
  declare partlyPayment: boolean
  @column()
  declare partlyPaymentAtBranch: boolean
  @column()
  declare rent: boolean
  @column()
  declare rentAtBranch: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BranchPeriodSchema extends BaseModel {
  static $columns = ['branchId', 'date', 'id', 'kind', 'maxNumberOfPeriods', 'percentage', 'percentageBuyout', 'percentageUpFront', 'periodType', 'price'] as const
  $columns = BranchPeriodSchema.$columns
  @column()
  declare branchId: string
  @column.dateTime()
  declare date: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare kind: string
  @column()
  declare maxNumberOfPeriods: number | null
  @column()
  declare percentage: number | null
  @column()
  declare percentageBuyout: number | null
  @column()
  declare percentageUpFront: number | null
  @column()
  declare periodType: string
  @column()
  declare price: number | null
}

export class BranchSubjectBookSchema extends BaseModel {
  static $columns = ['branchSubjectId', 'buy', 'buyAtBranch', 'createdAt', 'id', 'itemId', 'partlyPayment', 'partlyPaymentAtBranch', 'rent', 'rentAtBranch', 'updatedAt'] as const
  $columns = BranchSubjectBookSchema.$columns
  @column()
  declare branchSubjectId: number
  @column()
  declare buy: boolean
  @column()
  declare buyAtBranch: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare itemId: string
  @column()
  declare partlyPayment: boolean
  @column()
  declare partlyPaymentAtBranch: boolean
  @column()
  declare rent: boolean
  @column()
  declare rentAtBranch: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BranchSubjectSchema extends BaseModel {
  static $columns = ['branchId', 'createdAt', 'externalName', 'id', 'name', 'updatedAt'] as const
  $columns = BranchSubjectSchema.$columns
  @column()
  declare branchId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare externalName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BranchSchema extends BaseModel {
  static $columns = ['active', 'address', 'branchItemsLiveOnline', 'buyoutPercentage', 'childLabel', 'createdAt', 'deliveryAtBranch', 'deliveryByMail', 'id', 'localName', 'logo', 'name', 'parentBranchId', 'paymentResponsible', 'region', 'responsibleForDelivery', 'sellPercentage', 'type', 'updatedAt'] as const
  $columns = BranchSchema.$columns
  @column()
  declare active: boolean
  @column()
  declare address: string | null
  @column()
  declare branchItemsLiveOnline: boolean
  @column()
  declare buyoutPercentage: number
  @column()
  declare childLabel: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare deliveryAtBranch: boolean
  @column()
  declare deliveryByMail: boolean
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare localName: string | null
  @column()
  declare logo: string | null
  @column()
  declare name: string
  @column()
  declare parentBranchId: string | null
  @column()
  declare paymentResponsible: boolean
  @column()
  declare region: string
  @column()
  declare responsibleForDelivery: boolean
  @column()
  declare sellPercentage: number
  @column()
  declare type: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CompanySchema extends BaseModel {
  static $columns = ['address', 'createdAt', 'customerNumber', 'email', 'id', 'name', 'organizationNumber', 'phone', 'postCity', 'postCode', 'updatedAt'] as const
  $columns = CompanySchema.$columns
  @column()
  declare address: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare customerNumber: string
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare organizationNumber: string
  @column()
  declare phone: string
  @column()
  declare postCity: string
  @column()
  declare postCode: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class EditableTextSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'text', 'updatedAt'] as const
  $columns = EditableTextSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare text: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class EmailVerificationSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'updatedAt', 'userDetailId'] as const
  $columns = EmailVerificationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userDetailId: string
}

export class ItemSchema extends BaseModel {
  static $columns = ['active', 'buyback', 'createdAt', 'discount', 'distributor', 'id', 'isbn', 'price', 'priceHistory', 'publisher', 'subject', 'title', 'updatedAt', 'weight', 'year'] as const
  $columns = ItemSchema.$columns
  @column()
  declare active: boolean
  @column()
  declare buyback: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare discount: number
  @column()
  declare distributor: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isbn: bigint | number
  @column()
  declare price: number
  @column()
  declare priceHistory: any
  @column()
  declare publisher: string
  @column()
  declare subject: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare weight: number | null
  @column()
  declare year: number
}

export class MatchObligationSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'itemId', 'matchId', 'receiverParticipantId', 'senderParticipantId', 'updatedAt'] as const
  $columns = MatchObligationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare itemId: string
  @column()
  declare matchId: number
  @column()
  declare receiverParticipantId: number
  @column()
  declare senderParticipantId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MatchParticipantSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'matchId', 'updatedAt', 'userDetailId'] as const
  $columns = MatchParticipantSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare matchId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userDetailId: string | null
}

export class MatchRoundSchema extends BaseModel {
  static $columns = ['branches', 'createdAt', 'deadline', 'excludedCustomerIds', 'generatedAt', 'id', 'includeCustomerItemsFromOtherBranches', 'meetingDate', 'name', 'standFrom', 'standLocation', 'standTo', 'status', 'updatedAt', 'userMatchLocations', 'userMeetingFrom', 'userMeetingTo'] as const
  $columns = MatchRoundSchema.$columns
  @column()
  declare branches: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.date()
  declare deadline: DateTime
  @column()
  declare excludedCustomerIds: any
  @column.dateTime()
  declare generatedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare includeCustomerItemsFromOtherBranches: boolean
  @column.date()
  declare meetingDate: DateTime
  @column()
  declare name: string
  @column()
  declare standFrom: string
  @column()
  declare standLocation: string
  @column()
  declare standTo: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userMatchLocations: any
  @column()
  declare userMeetingFrom: string
  @column()
  declare userMeetingTo: string
}

export class MatchSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'meetingLocation', 'meetingTime', 'roundId', 'updatedAt'] as const
  $columns = MatchSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare meetingLocation: string
  @column.dateTime()
  declare meetingTime: DateTime | null
  @column()
  declare roundId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MessageEventSchema extends BaseModel {
  static $columns = ['createdAt', 'errorCode', 'event', 'id', 'messageId', 'occurredAt', 'payload', 'providerEventId', 'reason', 'source', 'updatedAt'] as const
  $columns = MessageEventSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare errorCode: string | null
  @column()
  declare event: string
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare messageId: string
  @column.dateTime()
  declare occurredAt: DateTime
  @column()
  declare payload: any | null
  @column()
  declare providerEventId: string | null
  @column()
  declare reason: string | null
  @column()
  declare source: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MessageSchema extends BaseModel {
  static $columns = ['channel', 'createdAt', 'id', 'messageType', 'providerMessageId', 'recipient', 'regardingCustomerDetailsId', 'sendoutId', 'smsBody', 'status', 'statusDetail', 'subject', 'templateData', 'templateId', 'updatedAt'] as const
  $columns = MessageSchema.$columns
  @column()
  declare channel: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare messageType: string
  @column()
  declare providerMessageId: string | null
  @column()
  declare recipient: string
  @column()
  declare regardingCustomerDetailsId: string | null
  @column()
  declare sendoutId: number | null
  @column()
  declare smsBody: string | null
  @column()
  declare status: string
  @column()
  declare statusDetail: string | null
  @column()
  declare subject: string | null
  @column()
  declare templateData: any | null
  @column()
  declare templateId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OpeningHourSchema extends BaseModel {
  static $columns = ['branchId', 'createdAt', 'from', 'id', 'to', 'updatedAt'] as const
  $columns = OpeningHourSchema.$columns
  @column()
  declare branchId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare from: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare to: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PasswordResetSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'tokenHash', 'updatedAt', 'userDetailId'] as const
  $columns = PasswordResetSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenHash: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userDetailId: string
}

export class QuestionAndAnswerSchema extends BaseModel {
  static $columns = ['answer', 'createdAt', 'id', 'position', 'question', 'updatedAt'] as const
  $columns = QuestionAndAnswerSchema.$columns
  @column()
  declare answer: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare position: number
  @column()
  declare question: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}

export class RememberMeTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'hash', 'id', 'tokenableId', 'updatedAt'] as const
  $columns = RememberMeTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenableId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SendoutSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'initiatedByDetailsId', 'kind', 'name', 'updatedAt'] as const
  $columns = SendoutSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare initiatedByDetailsId: string | null
  @column()
  declare kind: string
  @column()
  declare name: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SessionSchema extends BaseModel {
  static $columns = ['data', 'expiresAt', 'id', 'userId'] as const
  $columns = SessionSchema.$columns
  @column()
  declare data: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare userId: string | null
}

export class SignatureSchema extends BaseModel {
  static $columns = ['createdAt', 'customerDetailsId', 'id', 'image', 'signedByGuardian', 'signingName', 'updatedAt'] as const
  $columns = SignatureSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare customerDetailsId: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare image: Buffer
  @column()
  declare signedByGuardian: boolean
  @column()
  declare signingName: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UniqueItemSchema extends BaseModel {
  static $columns = ['blid', 'createdAt', 'id', 'itemId', 'updatedAt'] as const
  $columns = UniqueItemSchema.$columns
  @column()
  declare blid: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare itemId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['address', 'branchMembershipId', 'createdAt', 'dob', 'email', 'emailConfirmed', 'guardianEmail', 'guardianName', 'guardianPhone', 'id', 'lastActiveAt', 'localHashedPassword', 'name', 'permission', 'phone', 'postCity', 'postCode', 'taskConfirmDetails', 'taskSignAgreement', 'updatedAt', 'vippsUserId'] as const
  $columns = UserSchema.$columns
  @column()
  declare address: string
  @column()
  declare branchMembershipId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.date()
  declare dob: DateTime | null
  @column()
  declare email: string
  @column()
  declare emailConfirmed: boolean
  @column()
  declare guardianEmail: string | null
  @column()
  declare guardianName: string | null
  @column()
  declare guardianPhone: string | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastActiveAt: DateTime | null
  @column()
  declare localHashedPassword: string | null
  @column()
  declare name: string
  @column()
  declare permission: string
  @column()
  declare phone: string | null
  @column()
  declare postCity: string
  @column()
  declare postCode: string
  @column()
  declare taskConfirmDetails: boolean
  @column()
  declare taskSignAgreement: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vippsUserId: string | null
}

export class WaitingListCustomerSchema extends BaseModel {
  static $columns = ['branchId', 'createdAt', 'id', 'itemId', 'name', 'phoneNumber', 'updatedAt'] as const
  $columns = WaitingListCustomerSchema.$columns
  @column()
  declare branchId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare itemId: string
  @column()
  declare name: string
  @column()
  declare phoneNumber: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
