/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class BookHandoverSchema extends BaseModel {
  static $columns = ['blid', 'createdAt', 'dischargesReceiverObligationId', 'dischargesSenderObligationId', 'fromUserId', 'id', 'itemId', 'occurredAt', 'orderId', 'toUserId', 'updatedAt'] as const
  $columns = BookHandoverSchema.$columns
  @column()
  declare blid: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dischargesReceiverObligationId: number | null
  @column()
  declare dischargesSenderObligationId: number | null
  @column()
  declare fromUserId: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare itemId: string
  @column.dateTime()
  declare occurredAt: DateTime
  @column()
  declare orderId: string | null
  @column()
  declare toUserId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class BranchPeriodSchema extends BaseModel {
  static $columns = ['branchId', 'date', 'id', 'kind', 'maxNumberOfPeriods', 'percentage', 'percentageBuyout', 'percentageUpFront', 'periodType', 'price'] as const
  $columns = BranchPeriodSchema.$columns
  @column()
  declare branchId: string
  @column.date()
  declare date: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare kind: string
  @column()
  declare maxNumberOfPeriods: number | null
  @column()
  declare percentage: number | null
  @column()
  declare percentageBuyout: number | null
  @column()
  declare percentageUpFront: number | null
  @column()
  declare periodType: string
  @column()
  declare price: number | null
}

export class BranchSubjectBookSchema extends BaseModel {
  static $columns = ['branchSubjectId', 'buy', 'buyAtBranch', 'createdAt', 'id', 'itemId', 'partlyPayment', 'partlyPaymentAtBranch', 'rent', 'rentAtBranch', 'updatedAt'] as const
  $columns = BranchSubjectBookSchema.$columns
  @column()
  declare branchSubjectId: number
  @column()
  declare buy: boolean
  @column()
  declare buyAtBranch: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare itemId: string
  @column()
  declare partlyPayment: boolean
  @column()
  declare partlyPaymentAtBranch: boolean
  @column()
  declare rent: boolean
  @column()
  declare rentAtBranch: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class BranchSubjectSchema extends BaseModel {
  static $columns = ['branchId', 'createdAt', 'externalName', 'id', 'name', 'updatedAt'] as const
  $columns = BranchSubjectSchema.$columns
  @column()
  declare branchId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare externalName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class BranchSchema extends BaseModel {
  static $columns = ['address', 'buyoutPercentageOverride', 'childLabel', 'createdAt', 'deliveryAtBranchOverride', 'deliveryByMailOverride', 'id', 'localName', 'name', 'parentBranchId', 'paymentResponsibleOverride', 'responsibleForDeliveryOverride', 'sellPercentageOverride', 'updatedAt', 'visibilityOverride'] as const
  $columns = BranchSchema.$columns
  @column()
  declare address: string | null
  @column()
  declare buyoutPercentageOverride: number | null
  @column()
  declare childLabel: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare deliveryAtBranchOverride: boolean | null
  @column()
  declare deliveryByMailOverride: boolean | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare localName: string | null
  @column()
  declare name: string
  @column()
  declare parentBranchId: string | null
  @column()
  declare paymentResponsibleOverride: boolean | null
  @column()
  declare responsibleForDeliveryOverride: boolean | null
  @column()
  declare sellPercentageOverride: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare visibilityOverride: string | null
}

export class CompanySchema extends BaseModel {
  static $columns = ['address', 'createdAt', 'customerNumber', 'email', 'id', 'name', 'organizationNumber', 'phone', 'postCode', 'updatedAt'] as const
  $columns = CompanySchema.$columns
  @column()
  declare address: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customerNumber: string
  @column()
  declare email: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare organizationNumber: string
  @column()
  declare phone: string | null
  @column()
  declare postCode: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CustomerItemPeriodExtendSchema extends BaseModel {
  static $columns = ['createdAt', 'customerItemId', 'id', 'periodFrom', 'periodTo', 'periodType'] as const
  $columns = CustomerItemPeriodExtendSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customerItemId: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare periodFrom: DateTime
  @column.date()
  declare periodTo: DateTime
  @column()
  declare periodType: string
}

export class CustomerItemSchema extends BaseModel {
  static $columns = ['amountLeftToPay', 'blid', 'boughtBackAt', 'boughtOutAt', 'buyback', 'buybackOrderId', 'buyout', 'buyoutOrderId', 'cancel', 'cancelOrderId', 'cancelledAt', 'createdAt', 'customerId', 'deadline', 'handedOutAt', 'handoutBranchId', 'handoutEmployeeId', 'id', 'itemId', 'returnBranchId', 'returnEmployeeId', 'returned', 'returnedAt', 'type', 'updatedAt'] as const
  $columns = CustomerItemSchema.$columns
  @column()
  declare amountLeftToPay: number | null
  @column()
  declare blid: string | null
  @column.dateTime()
  declare boughtBackAt: DateTime | null
  @column.dateTime()
  declare boughtOutAt: DateTime | null
  @column()
  declare buyback: boolean
  @column()
  declare buybackOrderId: string | null
  @column()
  declare buyout: boolean
  @column()
  declare buyoutOrderId: string | null
  @column()
  declare cancel: boolean
  @column()
  declare cancelOrderId: string | null
  @column.dateTime()
  declare cancelledAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customerId: string | null
  @column.date()
  declare deadline: DateTime
  @column.dateTime()
  declare handedOutAt: DateTime
  @column()
  declare handoutBranchId: string
  @column()
  declare handoutEmployeeId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare itemId: string
  @column()
  declare returnBranchId: string | null
  @column()
  declare returnEmployeeId: string | null
  @column()
  declare returned: boolean
  @column.dateTime()
  declare returnedAt: DateTime | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class DeliverySchema extends BaseModel {
  static $columns = ['amount', 'branchId', 'bringAmount', 'createdAt', 'estimatedDelivery', 'facilityAddress', 'facilityPostalCode', 'fromPostalCode', 'id', 'method', 'orderId', 'product', 'shipmentAddress', 'shipmentName', 'shipmentPostalCode', 'toPostalCode', 'trackingNumber', 'updatedAt'] as const
  $columns = DeliverySchema.$columns
  @column()
  declare amount: number
  @column()
  declare branchId: string | null
  @column()
  declare bringAmount: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare estimatedDelivery: DateTime | null
  @column()
  declare facilityAddress: string | null
  @column()
  declare facilityPostalCode: string | null
  @column()
  declare fromPostalCode: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare method: string
  @column()
  declare orderId: string
  @column()
  declare product: string | null
  @column()
  declare shipmentAddress: string | null
  @column()
  declare shipmentName: string | null
  @column()
  declare shipmentPostalCode: string | null
  @column()
  declare toPostalCode: string | null
  @column()
  declare trackingNumber: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class EditableTextSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'text', 'updatedAt'] as const
  $columns = EditableTextSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare text: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class EmailVerificationSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'updatedAt', 'userId'] as const
  $columns = EmailVerificationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class InvoiceLineSchema extends BaseModel {
  static $columns = ['cancelled', 'customerItemId', 'customerItemType', 'discount', 'gross', 'id', 'invoiceId', 'itemId', 'net', 'numberOfItems', 'position', 'productNumber', 'title', 'unit', 'vat'] as const
  $columns = InvoiceLineSchema.$columns
  @column()
  declare cancelled: boolean
  @column()
  declare customerItemId: string | null
  @column()
  declare customerItemType: string | null
  @column()
  declare discount: number
  @column()
  declare gross: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare invoiceId: string
  @column()
  declare itemId: string | null
  @column()
  declare net: number
  @column()
  declare numberOfItems: number
  @column()
  declare position: number
  @column()
  declare productNumber: number | null
  @column()
  declare title: string
  @column()
  declare unit: number
  @column()
  declare vat: number
}

export class InvoiceSchema extends BaseModel {
  static $columns = ['branchId', 'comment', 'createdAt', 'customerAddress', 'customerCountry', 'customerDob', 'customerEmail', 'customerId', 'customerName', 'customerNumber', 'customerOrganizationNumber', 'customerPhone', 'customerPostCode', 'dueDate', 'feeDiscount', 'feeGross', 'feeNet', 'feeUnit', 'feeVat', 'id', 'invoiceNumber', 'ourReference', 'reference', 'status', 'totalDiscount', 'totalGross', 'totalIncludingFee', 'totalNet', 'totalVat', 'type', 'updatedAt'] as const
  $columns = InvoiceSchema.$columns
  @column()
  declare branchId: string | null
  @column()
  declare comment: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customerAddress: string | null
  @column()
  declare customerCountry: string | null
  @column.date()
  declare customerDob: DateTime | null
  @column()
  declare customerEmail: string | null
  @column()
  declare customerId: string | null
  @column()
  declare customerName: string | null
  @column()
  declare customerNumber: string
  @column()
  declare customerOrganizationNumber: string | null
  @column()
  declare customerPhone: string | null
  @column()
  declare customerPostCode: string | null
  @column.date()
  declare dueDate: DateTime
  @column()
  declare feeDiscount: number | null
  @column()
  declare feeGross: number | null
  @column()
  declare feeNet: number | null
  @column()
  declare feeUnit: number | null
  @column()
  declare feeVat: number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare invoiceNumber: string
  @column()
  declare ourReference: string | null
  @column()
  declare reference: string
  @column()
  declare status: string
  @column()
  declare totalDiscount: number
  @column()
  declare totalGross: number
  @column()
  declare totalIncludingFee: number
  @column()
  declare totalNet: number
  @column()
  declare totalVat: number
  @column()
  declare type: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ItemSchema extends BaseModel {
  static $columns = ['active', 'buyback', 'createdAt', 'discount', 'distributor', 'id', 'isbn', 'price', 'priceHistory', 'publisher', 'subject', 'title', 'updatedAt', 'weight', 'year'] as const
  $columns = ItemSchema.$columns
  @column()
  declare active: boolean
  @column()
  declare buyback: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare discount: number
  @column()
  declare distributor: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isbn: bigint | number | null
  @column()
  declare price: number
  @column()
  declare priceHistory: any
  @column()
  declare publisher: string
  @column()
  declare subject: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare weight: number | null
  @column()
  declare year: number
}

export class MatchObligationSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'itemId', 'matchId', 'receiverParticipantId', 'senderParticipantId', 'updatedAt'] as const
  $columns = MatchObligationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare itemId: string
  @column()
  declare matchId: number
  @column()
  declare receiverParticipantId: number
  @column()
  declare senderParticipantId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class MatchParticipantSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'matchId', 'updatedAt', 'userId'] as const
  $columns = MatchParticipantSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare matchId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string | null
}

export class MatchRoundStandBranchSchema extends BaseModel {
  static $columns = ['branchId', 'roundId'] as const
  $columns = MatchRoundStandBranchSchema.$columns
  @column()
  declare branchId: string
  @column({ isPrimary: true })
  declare roundId: number
}

export class MatchRoundStandCustomerSchema extends BaseModel {
  static $columns = ['customerId', 'roundId'] as const
  $columns = MatchRoundStandCustomerSchema.$columns
  @column()
  declare customerId: string
  @column({ isPrimary: true })
  declare roundId: number
}

export class MatchRoundSchema extends BaseModel {
  static $columns = ['branchId', 'createdAt', 'deadline', 'generatedAt', 'id', 'meetingDate', 'name', 'standFrom', 'standLocation', 'standTo', 'status', 'updatedAt', 'userMatchLocations', 'userMeetingFrom', 'userMeetingTo'] as const
  $columns = MatchRoundSchema.$columns
  @column()
  declare branchId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare deadline: DateTime
  @column.dateTime()
  declare generatedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column.date()
  declare meetingDate: DateTime
  @column()
  declare name: string
  @column()
  declare standFrom: string
  @column()
  declare standLocation: string
  @column()
  declare standTo: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userMatchLocations: any
  @column()
  declare userMeetingFrom: string
  @column()
  declare userMeetingTo: string
}

export class MatchSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'meetingLocation', 'meetingTime', 'roundId', 'updatedAt'] as const
  $columns = MatchSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare meetingLocation: string
  @column.dateTime()
  declare meetingTime: DateTime | null
  @column()
  declare roundId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class MessageEventSchema extends BaseModel {
  static $columns = ['createdAt', 'errorCode', 'event', 'id', 'messageId', 'occurredAt', 'payload', 'providerEventId', 'reason', 'source', 'updatedAt'] as const
  $columns = MessageEventSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare errorCode: string | null
  @column()
  declare event: string
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare messageId: string
  @column.dateTime()
  declare occurredAt: DateTime
  @column()
  declare payload: any | null
  @column()
  declare providerEventId: string | null
  @column()
  declare reason: string | null
  @column()
  declare source: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class MessageSchema extends BaseModel {
  static $columns = ['channel', 'createdAt', 'customerId', 'id', 'messageType', 'providerMessageId', 'recipient', 'sendoutId', 'smsBody', 'status', 'statusDetail', 'subject', 'templateData', 'templateId', 'updatedAt'] as const
  $columns = MessageSchema.$columns
  @column()
  declare channel: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customerId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare messageType: string
  @column()
  declare providerMessageId: string | null
  @column()
  declare recipient: string
  @column()
  declare sendoutId: number | null
  @column()
  declare smsBody: string | null
  @column()
  declare status: string
  @column()
  declare statusDetail: string | null
  @column()
  declare subject: string | null
  @column()
  declare templateData: any | null
  @column()
  declare templateId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class OpeningHourSchema extends BaseModel {
  static $columns = ['branchId', 'closesAt', 'createdAt', 'id', 'opensAt', 'updatedAt'] as const
  $columns = OpeningHourSchema.$columns
  @column()
  declare branchId: string
  @column.dateTime()
  declare closesAt: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare opensAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class OrderItemSchema extends BaseModel {
  static $columns = ['amount', 'amountLeftToPay', 'blid', 'buybackAmount', 'customerItemId', 'delivered', 'handout', 'id', 'itemId', 'movedFromOrderId', 'movedToOrderId', 'numberOfPeriods', 'orderId', 'periodFrom', 'periodTo', 'periodType', 'position', 'type', 'unitPrice'] as const
  $columns = OrderItemSchema.$columns
  @column()
  declare amount: number
  @column()
  declare amountLeftToPay: number | null
  @column()
  declare blid: string | null
  @column()
  declare buybackAmount: number | null
  @column()
  declare customerItemId: string | null
  @column()
  declare delivered: boolean
  @column()
  declare handout: boolean
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare itemId: string
  @column()
  declare movedFromOrderId: string | null
  @column()
  declare movedToOrderId: string | null
  @column()
  declare numberOfPeriods: number | null
  @column()
  declare orderId: string
  @column.dateTime()
  declare periodFrom: DateTime | null
  @column.date()
  declare periodTo: DateTime | null
  @column()
  declare periodType: string | null
  @column()
  declare position: number
  @column()
  declare type: string
  @column()
  declare unitPrice: number
}

export class OrderSchema extends BaseModel {
  static $columns = ['amount', 'branchId', 'byCustomer', 'checkoutState', 'createdAt', 'customerId', 'employeeId', 'id', 'notifyByEmail', 'placed', 'updatedAt'] as const
  $columns = OrderSchema.$columns
  @column()
  declare amount: number
  @column()
  declare branchId: string
  @column()
  declare byCustomer: boolean
  @column()
  declare checkoutState: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customerId: string | null
  @column()
  declare employeeId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare notifyByEmail: boolean
  @column()
  declare placed: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PaymentSchema extends BaseModel {
  static $columns = ['amount', 'confirmed', 'createdAt', 'id', 'method', 'orderId', 'updatedAt'] as const
  $columns = PaymentSchema.$columns
  @column()
  declare amount: number
  @column()
  declare confirmed: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare method: string
  @column()
  declare orderId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class QuestionAndAnswerSchema extends BaseModel {
  static $columns = ['answer', 'createdAt', 'id', 'position', 'question', 'updatedAt'] as const
  $columns = QuestionAndAnswerSchema.$columns
  @column()
  declare answer: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare position: number
  @column()
  declare question: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}

export class RememberMeTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'hash', 'id', 'tokenableId', 'updatedAt'] as const
  $columns = RememberMeTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenableId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SendoutSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'initiatedById', 'kind', 'name', 'updatedAt'] as const
  $columns = SendoutSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare initiatedById: string | null
  @column()
  declare kind: string
  @column()
  declare name: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SessionSchema extends BaseModel {
  static $columns = ['data', 'expiresAt', 'id', 'userId'] as const
  $columns = SessionSchema.$columns
  @column()
  declare data: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare userId: string | null
}

export class SignatureLinkSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'tokenEncrypted', 'tokenHash', 'userId'] as const
  $columns = SignatureLinkSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenEncrypted: string
  @column()
  declare tokenHash: string
  @column()
  declare userId: string
}

export class SignatureSchema extends BaseModel {
  static $columns = ['createdAt', 'customerId', 'id', 'image', 'signedByGuardian', 'signingName', 'updatedAt'] as const
  $columns = SignatureSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customerId: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare image: Buffer
  @column()
  declare signedByGuardian: boolean
  @column()
  declare signingName: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SmsCodeSchema extends BaseModel {
  static $columns = ['attempts', 'codeHash', 'createdAt', 'expiresAt', 'id', 'phone', 'purpose', 'userId'] as const
  $columns = SmsCodeSchema.$columns
  @column()
  declare attempts: number
  @column()
  declare codeHash: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare phone: string
  @column()
  declare purpose: string
  @column()
  declare userId: string | null
}

export class UniqueItemSchema extends BaseModel {
  static $columns = ['blid', 'createdAt', 'id', 'itemId', 'updatedAt'] as const
  $columns = UniqueItemSchema.$columns
  @column()
  declare blid: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare itemId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserSchema extends BaseModel {
  static $columns = ['address', 'branchMembershipId', 'createdAt', 'dob', 'email', 'emailConfirmed', 'guardianEmail', 'guardianName', 'guardianPhone', 'id', 'lastActiveAt', 'name', 'permission', 'phone', 'postCode', 'taskConfirmDetails', 'taskSignAgreement', 'updatedAt', 'vippsUserId'] as const
  $columns = UserSchema.$columns
  @column()
  declare address: string | null
  @column()
  declare branchMembershipId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare dob: DateTime | null
  @column()
  declare email: string
  @column()
  declare emailConfirmed: boolean
  @column()
  declare guardianEmail: string | null
  @column()
  declare guardianName: string | null
  @column()
  declare guardianPhone: string | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastActiveAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare permission: string
  @column()
  declare phone: string | null
  @column()
  declare postCode: string | null
  @column()
  declare taskConfirmDetails: boolean
  @column()
  declare taskSignAgreement: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare vippsUserId: string | null
}

export class WaitingListCustomerSchema extends BaseModel {
  static $columns = ['branchId', 'createdAt', 'id', 'itemId', 'name', 'phone', 'updatedAt'] as const
  $columns = WaitingListCustomerSchema.$columns
  @column()
  declare branchId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare itemId: string
  @column()
  declare name: string
  @column()
  declare phone: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}
