/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as offentligRouteRouteImport } from './routes/(offentlig)/route'
import { Route as HealthRouteImport } from './routes/health'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as administrasjonAdminRouteRouteImport } from './routes/(administrasjon)/admin/route'
import { Route as legacyWelcomeRouteImport } from './routes/(legacy)/welcome'
import { Route as offentligHandlekurvRouteImport } from './routes/(offentlig)/handlekurv'
import { Route as offentligInfoRouteRouteImport } from './routes/(offentlig)/info/route'
import { Route as offentligItemsRouteImport } from './routes/(offentlig)/items'
import { Route as offentligOppgaverRouteImport } from './routes/(offentlig)/oppgaver'
import { Route as offentligOrderHistoryRouteImport } from './routes/(offentlig)/order-history'
import { Route as offentligOverleveringerRouteRouteImport } from './routes/(offentlig)/overleveringer/route'
import { Route as offentligSjekkRouteImport } from './routes/(offentlig)/sjekk'
import { Route as offentligUserSettingsRouteImport } from './routes/(offentlig)/user-settings'
import { Route as administrasjonAdminIndexRouteImport } from './routes/(administrasjon)/admin/index'
import { Route as administrasjonAdminBlidRouteImport } from './routes/(administrasjon)/admin/blid'
import { Route as administrasjonAdminFakturaRouteImport } from './routes/(administrasjon)/admin/faktura'
import { Route as administrasjonAdminHandlekurvRouteImport } from './routes/(administrasjon)/admin/handlekurv'
import { Route as administrasjonAdminHurtiginnsamlingRouteImport } from './routes/(administrasjon)/admin/hurtiginnsamling'
import { Route as administrasjonAdminHurtigutdelingRouteImport } from './routes/(administrasjon)/admin/hurtigutdeling'
import { Route as administrasjonAdminOrdreoversiktRouteImport } from './routes/(administrasjon)/admin/ordreoversikt'
import { Route as administrasjonAdminOverleveringerRouteRouteImport } from './routes/(administrasjon)/admin/overleveringer/route'
import { Route as administrasjonAdminScannerRouteImport } from './routes/(administrasjon)/admin/scanner'
import { Route as administrasjonAdminUserSettingsRouteImport } from './routes/(administrasjon)/admin/user-settings'
import { Route as administrasjonAdminVentelisteRouteImport } from './routes/(administrasjon)/admin/venteliste'
import { Route as legacyAuthMenuRouteImport } from './routes/(legacy)/auth/menu'
import { Route as legacyAuthSuccessRouteImport } from './routes/(legacy)/auth/success'
import { Route as legacyDatabaseCompaniesRouteImport } from './routes/(legacy)/database.companies'
import { Route as legacyUEditRouteImport } from './routes/(legacy)/u.edit'
import { Route as offentligAuthFailureRouteImport } from './routes/(offentlig)/auth/failure'
import { Route as offentligAuthForgotRouteImport } from './routes/(offentlig)/auth/forgot'
import { Route as offentligAuthLoginRouteImport } from './routes/(offentlig)/auth/login'
import { Route as offentligAuthLogoutRouteImport } from './routes/(offentlig)/auth/logout'
import { Route as offentligAuthRegisterRouteImport } from './routes/(offentlig)/auth/register'
import { Route as offentligAuthTokenRouteImport } from './routes/(offentlig)/auth/token'
import { Route as offentligBestillingIndexRouteImport } from './routes/(offentlig)/bestilling/index'
import { Route as offentligBestillingBranchIdRouteImport } from './routes/(offentlig)/bestilling/$branchId'
import { Route as offentligInfoAboutRouteImport } from './routes/(offentlig)/info/about'
import { Route as offentligInfoBranchRouteRouteImport } from './routes/(offentlig)/info/branch/route'
import { Route as offentligInfoBuybackRouteImport } from './routes/(offentlig)/info/buyback'
import { Route as offentligInfoCompaniesRouteImport } from './routes/(offentlig)/info/companies'
import { Route as offentligInfoContactRouteImport } from './routes/(offentlig)/info/contact'
import { Route as offentligInfoFaqRouteImport } from './routes/(offentlig)/info/faq'
import { Route as offentligInfoGeneralRouteImport } from './routes/(offentlig)/info/general'
import { Route as offentligInfoPoliciesRouteRouteImport } from './routes/(offentlig)/info/policies/route'
import { Route as offentligInfoPupilsRouteImport } from './routes/(offentlig)/info/pupils'
import { Route as offentligKasseIndexRouteImport } from './routes/(offentlig)/kasse/index'
import { Route as offentligKasseBekreftRouteImport } from './routes/(offentlig)/kasse/bekreft'
import { Route as offentligOverleveringerIndexRouteImport } from './routes/(offentlig)/overleveringer/index'
import { Route as offentligOverleveringerMatchIdRouteImport } from './routes/(offentlig)/overleveringer/$matchId'
import { Route as offentligSigneringUserDetailIdRouteImport } from './routes/(offentlig)/signering.$userDetailId'
import { Route as administrasjonAdminDatabaseBokerRouteImport } from './routes/(administrasjon)/admin/database/boker'
import { Route as administrasjonAdminDatabaseBrukereRouteImport } from './routes/(administrasjon)/admin/database/brukere'
import { Route as administrasjonAdminDatabaseDynamisk_innholdRouteImport } from './routes/(administrasjon)/admin/database/dynamisk_innhold'
import { Route as administrasjonAdminDatabaseFilialerRouteImport } from './routes/(administrasjon)/admin/database/filialer'
import { Route as administrasjonAdminDatabaseRapporterRouteImport } from './routes/(administrasjon)/admin/database/rapporter'
import { Route as administrasjonAdminDatabaseSelskapRouteImport } from './routes/(administrasjon)/admin/database/selskap'
import { Route as administrasjonAdminDatabaseUnik_idRouteImport } from './routes/(administrasjon)/admin/database/unik_id'
import { Route as administrasjonAdminKommunikasjonPaminnelserRouteImport } from './routes/(administrasjon)/admin/kommunikasjon/paminnelser'
import { Route as administrasjonAdminKommunikasjonUtsendelserRouteImport } from './routes/(administrasjon)/admin/kommunikasjon/utsendelser'
import { Route as administrasjonAdminOverleveringerIndexRouteImport } from './routes/(administrasjon)/admin/overleveringer/index'
import { Route as administrasjonAdminOverleveringerMatchIdRouteImport } from './routes/(administrasjon)/admin/overleveringer/$matchId'
import { Route as legacyAuthLoginForgotRouteImport } from './routes/(legacy)/auth/login.forgot'
import { Route as legacyAuthRegisterDetailRouteImport } from './routes/(legacy)/auth/register.detail'
import { Route as legacyAuthSocialFailureRouteImport } from './routes/(legacy)/auth/social.failure'
import { Route as legacyDatabaseBranchesEditRouteImport } from './routes/(legacy)/database.branches.edit'
import { Route as offentligAuthPermissionDeniedRouteImport } from './routes/(offentlig)/auth/permission.denied'
import { Route as offentligAuthResetIdRouteImport } from './routes/(offentlig)/auth/reset.$id'
import { Route as offentligInfoBranchBranchIdRouteImport } from './routes/(offentlig)/info/branch/$branchId'
import { Route as offentligInfoPoliciesConditionsRouteImport } from './routes/(offentlig)/info/policies/conditions'
import { Route as offentligInfoPoliciesPrivacyRouteImport } from './routes/(offentlig)/info/policies/privacy'
import { Route as offentligInfoPoliciesTermsRouteImport } from './routes/(offentlig)/info/policies/terms'
import { Route as offentligKasseBetalingIndexRouteImport } from './routes/(offentlig)/kasse/betaling/index'
import { Route as offentligKasseBetalingStatusRouteImport } from './routes/(offentlig)/kasse/betaling/status'
import { Route as offentligAuthEmailVerifyVerificationIdRouteImport } from './routes/(offentlig)/auth/email.verify.$verificationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const offentligRouteRoute = offentligRouteRouteImport.update({
  id: '/(offentlig)',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const administrasjonAdminRouteRoute =
  administrasjonAdminRouteRouteImport.update({
    id: '/(administrasjon)/admin',
    path: '/admin',
    getParentRoute: () => rootRouteImport,
  } as any)
const legacyWelcomeRoute = legacyWelcomeRouteImport.update({
  id: '/(legacy)/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const offentligHandlekurvRoute = offentligHandlekurvRouteImport.update({
  id: '/handlekurv',
  path: '/handlekurv',
  getParentRoute: () => offentligRouteRoute,
} as any)
const offentligInfoRouteRoute = offentligInfoRouteRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => offentligRouteRoute,
} as any)
const offentligItemsRoute = offentligItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => offentligRouteRoute,
} as any)
const offentligOppgaverRoute = offentligOppgaverRouteImport.update({
  id: '/oppgaver',
  path: '/oppgaver',
  getParentRoute: () => offentligRouteRoute,
} as any)
const offentligOrderHistoryRoute = offentligOrderHistoryRouteImport.update({
  id: '/order-history',
  path: '/order-history',
  getParentRoute: () => offentligRouteRoute,
} as any)
const offentligOverleveringerRouteRoute =
  offentligOverleveringerRouteRouteImport.update({
    id: '/overleveringer',
    path: '/overleveringer',
    getParentRoute: () => offentligRouteRoute,
  } as any)
const offentligSjekkRoute = offentligSjekkRouteImport.update({
  id: '/sjekk',
  path: '/sjekk',
  getParentRoute: () => offentligRouteRoute,
} as any)
const offentligUserSettingsRoute = offentligUserSettingsRouteImport.update({
  id: '/user-settings',
  path: '/user-settings',
  getParentRoute: () => offentligRouteRoute,
} as any)
const administrasjonAdminIndexRoute =
  administrasjonAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => administrasjonAdminRouteRoute,
  } as any)
const administrasjonAdminBlidRoute = administrasjonAdminBlidRouteImport.update({
  id: '/blid',
  path: '/blid',
  getParentRoute: () => administrasjonAdminRouteRoute,
} as any)
const administrasjonAdminFakturaRoute =
  administrasjonAdminFakturaRouteImport.update({
    id: '/faktura',
    path: '/faktura',
    getParentRoute: () => administrasjonAdminRouteRoute,
  } as any)
const administrasjonAdminHandlekurvRoute =
  administrasjonAdminHandlekurvRouteImport.update({
    id: '/handlekurv',
    path: '/handlekurv',
    getParentRoute: () => administrasjonAdminRouteRoute,
  } as any)
const administrasjonAdminHurtiginnsamlingRoute =
  administrasjonAdminHurtiginnsamlingRouteImport.update({
    id: '/hurtiginnsamling',
    path: '/hurtiginnsamling',
    getParentRoute: () => administrasjonAdminRouteRoute,
  } as any)
const administrasjonAdminHurtigutdelingRoute =
  administrasjonAdminHurtigutdelingRouteImport.update({
    id: '/hurtigutdeling',
    path: '/hurtigutdeling',
    getParentRoute: () => administrasjonAdminRouteRoute,
  } as any)
const administrasjonAdminOrdreoversiktRoute =
  administrasjonAdminOrdreoversiktRouteImport.update({
    id: '/ordreoversikt',
    path: '/ordreoversikt',
    getParentRoute: () => administrasjonAdminRouteRoute,
  } as any)
const administrasjonAdminOverleveringerRouteRoute =
  administrasjonAdminOverleveringerRouteRouteImport.update({
    id: '/overleveringer',
    path: '/overleveringer',
    getParentRoute: () => administrasjonAdminRouteRoute,
  } as any)
const administrasjonAdminScannerRoute =
  administrasjonAdminScannerRouteImport.update({
    id: '/scanner',
    path: '/scanner',
    getParentRoute: () => administrasjonAdminRouteRoute,
  } as any)
const administrasjonAdminUserSettingsRoute =
  administrasjonAdminUserSettingsRouteImport.update({
    id: '/user-settings',
    path: '/user-settings',
    getParentRoute: () => administrasjonAdminRouteRoute,
  } as any)
const administrasjonAdminVentelisteRoute =
  administrasjonAdminVentelisteRouteImport.update({
    id: '/venteliste',
    path: '/venteliste',
    getParentRoute: () => administrasjonAdminRouteRoute,
  } as any)
const legacyAuthMenuRoute = legacyAuthMenuRouteImport.update({
  id: '/(legacy)/auth/menu',
  path: '/auth/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const legacyAuthSuccessRoute = legacyAuthSuccessRouteImport.update({
  id: '/(legacy)/auth/success',
  path: '/auth/success',
  getParentRoute: () => rootRouteImport,
} as any)
const legacyDatabaseCompaniesRoute = legacyDatabaseCompaniesRouteImport.update({
  id: '/(legacy)/database/companies',
  path: '/database/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const legacyUEditRoute = legacyUEditRouteImport.update({
  id: '/(legacy)/u/edit',
  path: '/u/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const offentligAuthFailureRoute = offentligAuthFailureRouteImport.update({
  id: '/auth/failure',
  path: '/auth/failure',
  getParentRoute: () => offentligRouteRoute,
} as any)
const offentligAuthForgotRoute = offentligAuthForgotRouteImport.update({
  id: '/auth/forgot',
  path: '/auth/forgot',
  getParentRoute: () => offentligRouteRoute,
} as any)
const offentligAuthLoginRoute = offentligAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => offentligRouteRoute,
} as any)
const offentligAuthLogoutRoute = offentligAuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => offentligRouteRoute,
} as any)
const offentligAuthRegisterRoute = offentligAuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => offentligRouteRoute,
} as any)
const offentligAuthTokenRoute = offentligAuthTokenRouteImport.update({
  id: '/auth/token',
  path: '/auth/token',
  getParentRoute: () => offentligRouteRoute,
} as any)
const offentligBestillingIndexRoute =
  offentligBestillingIndexRouteImport.update({
    id: '/bestilling/',
    path: '/bestilling/',
    getParentRoute: () => offentligRouteRoute,
  } as any)
const offentligBestillingBranchIdRoute =
  offentligBestillingBranchIdRouteImport.update({
    id: '/bestilling/$branchId',
    path: '/bestilling/$branchId',
    getParentRoute: () => offentligRouteRoute,
  } as any)
const offentligInfoAboutRoute = offentligInfoAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => offentligInfoRouteRoute,
} as any)
const offentligInfoBranchRouteRoute =
  offentligInfoBranchRouteRouteImport.update({
    id: '/branch',
    path: '/branch',
    getParentRoute: () => offentligInfoRouteRoute,
  } as any)
const offentligInfoBuybackRoute = offentligInfoBuybackRouteImport.update({
  id: '/buyback',
  path: '/buyback',
  getParentRoute: () => offentligInfoRouteRoute,
} as any)
const offentligInfoCompaniesRoute = offentligInfoCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => offentligInfoRouteRoute,
} as any)
const offentligInfoContactRoute = offentligInfoContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => offentligInfoRouteRoute,
} as any)
const offentligInfoFaqRoute = offentligInfoFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => offentligInfoRouteRoute,
} as any)
const offentligInfoGeneralRoute = offentligInfoGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => offentligInfoRouteRoute,
} as any)
const offentligInfoPoliciesRouteRoute =
  offentligInfoPoliciesRouteRouteImport.update({
    id: '/policies',
    path: '/policies',
    getParentRoute: () => offentligInfoRouteRoute,
  } as any)
const offentligInfoPupilsRoute = offentligInfoPupilsRouteImport.update({
  id: '/pupils',
  path: '/pupils',
  getParentRoute: () => offentligInfoRouteRoute,
} as any)
const offentligKasseIndexRoute = offentligKasseIndexRouteImport.update({
  id: '/kasse/',
  path: '/kasse/',
  getParentRoute: () => offentligRouteRoute,
} as any)
const offentligKasseBekreftRoute = offentligKasseBekreftRouteImport.update({
  id: '/kasse/bekreft',
  path: '/kasse/bekreft',
  getParentRoute: () => offentligRouteRoute,
} as any)
const offentligOverleveringerIndexRoute =
  offentligOverleveringerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => offentligOverleveringerRouteRoute,
  } as any)
const offentligOverleveringerMatchIdRoute =
  offentligOverleveringerMatchIdRouteImport.update({
    id: '/$matchId',
    path: '/$matchId',
    getParentRoute: () => offentligOverleveringerRouteRoute,
  } as any)
const offentligSigneringUserDetailIdRoute =
  offentligSigneringUserDetailIdRouteImport.update({
    id: '/signering/$userDetailId',
    path: '/signering/$userDetailId',
    getParentRoute: () => offentligRouteRoute,
  } as any)
const administrasjonAdminDatabaseBokerRoute =
  administrasjonAdminDatabaseBokerRouteImport.update({
    id: '/database/boker',
    path: '/database/boker',
    getParentRoute: () => administrasjonAdminRouteRoute,
  } as any)
const administrasjonAdminDatabaseBrukereRoute =
  administrasjonAdminDatabaseBrukereRouteImport.update({
    id: '/database/brukere',
    path: '/database/brukere',
    getParentRoute: () => administrasjonAdminRouteRoute,
  } as any)
const administrasjonAdminDatabaseDynamisk_innholdRoute =
  administrasjonAdminDatabaseDynamisk_innholdRouteImport.update({
    id: '/database/dynamisk_innhold',
    path: '/database/dynamisk_innhold',
    getParentRoute: () => administrasjonAdminRouteRoute,
  } as any)
const administrasjonAdminDatabaseFilialerRoute =
  administrasjonAdminDatabaseFilialerRouteImport.update({
    id: '/database/filialer',
    path: '/database/filialer',
    getParentRoute: () => administrasjonAdminRouteRoute,
  } as any)
const administrasjonAdminDatabaseRapporterRoute =
  administrasjonAdminDatabaseRapporterRouteImport.update({
    id: '/database/rapporter',
    path: '/database/rapporter',
    getParentRoute: () => administrasjonAdminRouteRoute,
  } as any)
const administrasjonAdminDatabaseSelskapRoute =
  administrasjonAdminDatabaseSelskapRouteImport.update({
    id: '/database/selskap',
    path: '/database/selskap',
    getParentRoute: () => administrasjonAdminRouteRoute,
  } as any)
const administrasjonAdminDatabaseUnik_idRoute =
  administrasjonAdminDatabaseUnik_idRouteImport.update({
    id: '/database/unik_id',
    path: '/database/unik_id',
    getParentRoute: () => administrasjonAdminRouteRoute,
  } as any)
const administrasjonAdminKommunikasjonPaminnelserRoute =
  administrasjonAdminKommunikasjonPaminnelserRouteImport.update({
    id: '/kommunikasjon/paminnelser',
    path: '/kommunikasjon/paminnelser',
    getParentRoute: () => administrasjonAdminRouteRoute,
  } as any)
const administrasjonAdminKommunikasjonUtsendelserRoute =
  administrasjonAdminKommunikasjonUtsendelserRouteImport.update({
    id: '/kommunikasjon/utsendelser',
    path: '/kommunikasjon/utsendelser',
    getParentRoute: () => administrasjonAdminRouteRoute,
  } as any)
const administrasjonAdminOverleveringerIndexRoute =
  administrasjonAdminOverleveringerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => administrasjonAdminOverleveringerRouteRoute,
  } as any)
const administrasjonAdminOverleveringerMatchIdRoute =
  administrasjonAdminOverleveringerMatchIdRouteImport.update({
    id: '/$matchId',
    path: '/$matchId',
    getParentRoute: () => administrasjonAdminOverleveringerRouteRoute,
  } as any)
const legacyAuthLoginForgotRoute = legacyAuthLoginForgotRouteImport.update({
  id: '/(legacy)/auth/login/forgot',
  path: '/auth/login/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const legacyAuthRegisterDetailRoute =
  legacyAuthRegisterDetailRouteImport.update({
    id: '/(legacy)/auth/register/detail',
    path: '/auth/register/detail',
    getParentRoute: () => rootRouteImport,
  } as any)
const legacyAuthSocialFailureRoute = legacyAuthSocialFailureRouteImport.update({
  id: '/(legacy)/auth/social/failure',
  path: '/auth/social/failure',
  getParentRoute: () => rootRouteImport,
} as any)
const legacyDatabaseBranchesEditRoute =
  legacyDatabaseBranchesEditRouteImport.update({
    id: '/(legacy)/database/branches/edit',
    path: '/database/branches/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const offentligAuthPermissionDeniedRoute =
  offentligAuthPermissionDeniedRouteImport.update({
    id: '/auth/permission/denied',
    path: '/auth/permission/denied',
    getParentRoute: () => offentligRouteRoute,
  } as any)
const offentligAuthResetIdRoute = offentligAuthResetIdRouteImport.update({
  id: '/auth/reset/$id',
  path: '/auth/reset/$id',
  getParentRoute: () => offentligRouteRoute,
} as any)
const offentligInfoBranchBranchIdRoute =
  offentligInfoBranchBranchIdRouteImport.update({
    id: '/$branchId',
    path: '/$branchId',
    getParentRoute: () => offentligInfoBranchRouteRoute,
  } as any)
const offentligInfoPoliciesConditionsRoute =
  offentligInfoPoliciesConditionsRouteImport.update({
    id: '/conditions',
    path: '/conditions',
    getParentRoute: () => offentligInfoPoliciesRouteRoute,
  } as any)
const offentligInfoPoliciesPrivacyRoute =
  offentligInfoPoliciesPrivacyRouteImport.update({
    id: '/privacy',
    path: '/privacy',
    getParentRoute: () => offentligInfoPoliciesRouteRoute,
  } as any)
const offentligInfoPoliciesTermsRoute =
  offentligInfoPoliciesTermsRouteImport.update({
    id: '/terms',
    path: '/terms',
    getParentRoute: () => offentligInfoPoliciesRouteRoute,
  } as any)
const offentligKasseBetalingIndexRoute =
  offentligKasseBetalingIndexRouteImport.update({
    id: '/kasse/betaling/',
    path: '/kasse/betaling/',
    getParentRoute: () => offentligRouteRoute,
  } as any)
const offentligKasseBetalingStatusRoute =
  offentligKasseBetalingStatusRouteImport.update({
    id: '/kasse/betaling/status',
    path: '/kasse/betaling/status',
    getParentRoute: () => offentligRouteRoute,
  } as any)
const offentligAuthEmailVerifyVerificationIdRoute =
  offentligAuthEmailVerifyVerificationIdRouteImport.update({
    id: '/auth/email/verify/$verificationId',
    path: '/auth/email/verify/$verificationId',
    getParentRoute: () => offentligRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof administrasjonAdminRouteRouteWithChildren
  '/info': typeof offentligInfoRouteRouteWithChildren
  '/overleveringer': typeof offentligOverleveringerRouteRouteWithChildren
  '/welcome': typeof legacyWelcomeRoute
  '/handlekurv': typeof offentligHandlekurvRoute
  '/items': typeof offentligItemsRoute
  '/oppgaver': typeof offentligOppgaverRoute
  '/order-history': typeof offentligOrderHistoryRoute
  '/sjekk': typeof offentligSjekkRoute
  '/user-settings': typeof offentligUserSettingsRoute
  '/admin/overleveringer': typeof administrasjonAdminOverleveringerRouteRouteWithChildren
  '/info/branch': typeof offentligInfoBranchRouteRouteWithChildren
  '/info/policies': typeof offentligInfoPoliciesRouteRouteWithChildren
  '/admin/blid': typeof administrasjonAdminBlidRoute
  '/admin/faktura': typeof administrasjonAdminFakturaRoute
  '/admin/handlekurv': typeof administrasjonAdminHandlekurvRoute
  '/admin/hurtiginnsamling': typeof administrasjonAdminHurtiginnsamlingRoute
  '/admin/hurtigutdeling': typeof administrasjonAdminHurtigutdelingRoute
  '/admin/ordreoversikt': typeof administrasjonAdminOrdreoversiktRoute
  '/admin/scanner': typeof administrasjonAdminScannerRoute
  '/admin/user-settings': typeof administrasjonAdminUserSettingsRoute
  '/admin/venteliste': typeof administrasjonAdminVentelisteRoute
  '/auth/menu': typeof legacyAuthMenuRoute
  '/auth/success': typeof legacyAuthSuccessRoute
  '/database/companies': typeof legacyDatabaseCompaniesRoute
  '/u/edit': typeof legacyUEditRoute
  '/auth/failure': typeof offentligAuthFailureRoute
  '/auth/forgot': typeof offentligAuthForgotRoute
  '/auth/login': typeof offentligAuthLoginRoute
  '/auth/logout': typeof offentligAuthLogoutRoute
  '/auth/register': typeof offentligAuthRegisterRoute
  '/auth/token': typeof offentligAuthTokenRoute
  '/bestilling/$branchId': typeof offentligBestillingBranchIdRoute
  '/info/about': typeof offentligInfoAboutRoute
  '/info/buyback': typeof offentligInfoBuybackRoute
  '/info/companies': typeof offentligInfoCompaniesRoute
  '/info/contact': typeof offentligInfoContactRoute
  '/info/faq': typeof offentligInfoFaqRoute
  '/info/general': typeof offentligInfoGeneralRoute
  '/info/pupils': typeof offentligInfoPupilsRoute
  '/kasse/bekreft': typeof offentligKasseBekreftRoute
  '/overleveringer/$matchId': typeof offentligOverleveringerMatchIdRoute
  '/signering/$userDetailId': typeof offentligSigneringUserDetailIdRoute
  '/admin/': typeof administrasjonAdminIndexRoute
  '/bestilling/': typeof offentligBestillingIndexRoute
  '/kasse/': typeof offentligKasseIndexRoute
  '/overleveringer/': typeof offentligOverleveringerIndexRoute
  '/admin/database/boker': typeof administrasjonAdminDatabaseBokerRoute
  '/admin/database/brukere': typeof administrasjonAdminDatabaseBrukereRoute
  '/admin/database/dynamisk_innhold': typeof administrasjonAdminDatabaseDynamisk_innholdRoute
  '/admin/database/filialer': typeof administrasjonAdminDatabaseFilialerRoute
  '/admin/database/rapporter': typeof administrasjonAdminDatabaseRapporterRoute
  '/admin/database/selskap': typeof administrasjonAdminDatabaseSelskapRoute
  '/admin/database/unik_id': typeof administrasjonAdminDatabaseUnik_idRoute
  '/admin/kommunikasjon/paminnelser': typeof administrasjonAdminKommunikasjonPaminnelserRoute
  '/admin/kommunikasjon/utsendelser': typeof administrasjonAdminKommunikasjonUtsendelserRoute
  '/admin/overleveringer/$matchId': typeof administrasjonAdminOverleveringerMatchIdRoute
  '/auth/login/forgot': typeof legacyAuthLoginForgotRoute
  '/auth/register/detail': typeof legacyAuthRegisterDetailRoute
  '/auth/social/failure': typeof legacyAuthSocialFailureRoute
  '/database/branches/edit': typeof legacyDatabaseBranchesEditRoute
  '/auth/permission/denied': typeof offentligAuthPermissionDeniedRoute
  '/auth/reset/$id': typeof offentligAuthResetIdRoute
  '/info/branch/$branchId': typeof offentligInfoBranchBranchIdRoute
  '/info/policies/conditions': typeof offentligInfoPoliciesConditionsRoute
  '/info/policies/privacy': typeof offentligInfoPoliciesPrivacyRoute
  '/info/policies/terms': typeof offentligInfoPoliciesTermsRoute
  '/kasse/betaling/status': typeof offentligKasseBetalingStatusRoute
  '/admin/overleveringer/': typeof administrasjonAdminOverleveringerIndexRoute
  '/kasse/betaling/': typeof offentligKasseBetalingIndexRoute
  '/auth/email/verify/$verificationId': typeof offentligAuthEmailVerifyVerificationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/info': typeof offentligInfoRouteRouteWithChildren
  '/welcome': typeof legacyWelcomeRoute
  '/handlekurv': typeof offentligHandlekurvRoute
  '/items': typeof offentligItemsRoute
  '/oppgaver': typeof offentligOppgaverRoute
  '/order-history': typeof offentligOrderHistoryRoute
  '/sjekk': typeof offentligSjekkRoute
  '/user-settings': typeof offentligUserSettingsRoute
  '/info/branch': typeof offentligInfoBranchRouteRouteWithChildren
  '/info/policies': typeof offentligInfoPoliciesRouteRouteWithChildren
  '/admin/blid': typeof administrasjonAdminBlidRoute
  '/admin/faktura': typeof administrasjonAdminFakturaRoute
  '/admin/handlekurv': typeof administrasjonAdminHandlekurvRoute
  '/admin/hurtiginnsamling': typeof administrasjonAdminHurtiginnsamlingRoute
  '/admin/hurtigutdeling': typeof administrasjonAdminHurtigutdelingRoute
  '/admin/ordreoversikt': typeof administrasjonAdminOrdreoversiktRoute
  '/admin/scanner': typeof administrasjonAdminScannerRoute
  '/admin/user-settings': typeof administrasjonAdminUserSettingsRoute
  '/admin/venteliste': typeof administrasjonAdminVentelisteRoute
  '/auth/menu': typeof legacyAuthMenuRoute
  '/auth/success': typeof legacyAuthSuccessRoute
  '/database/companies': typeof legacyDatabaseCompaniesRoute
  '/u/edit': typeof legacyUEditRoute
  '/auth/failure': typeof offentligAuthFailureRoute
  '/auth/forgot': typeof offentligAuthForgotRoute
  '/auth/login': typeof offentligAuthLoginRoute
  '/auth/logout': typeof offentligAuthLogoutRoute
  '/auth/register': typeof offentligAuthRegisterRoute
  '/auth/token': typeof offentligAuthTokenRoute
  '/bestilling/$branchId': typeof offentligBestillingBranchIdRoute
  '/info/about': typeof offentligInfoAboutRoute
  '/info/buyback': typeof offentligInfoBuybackRoute
  '/info/companies': typeof offentligInfoCompaniesRoute
  '/info/contact': typeof offentligInfoContactRoute
  '/info/faq': typeof offentligInfoFaqRoute
  '/info/general': typeof offentligInfoGeneralRoute
  '/info/pupils': typeof offentligInfoPupilsRoute
  '/kasse/bekreft': typeof offentligKasseBekreftRoute
  '/overleveringer/$matchId': typeof offentligOverleveringerMatchIdRoute
  '/signering/$userDetailId': typeof offentligSigneringUserDetailIdRoute
  '/admin': typeof administrasjonAdminIndexRoute
  '/bestilling': typeof offentligBestillingIndexRoute
  '/kasse': typeof offentligKasseIndexRoute
  '/overleveringer': typeof offentligOverleveringerIndexRoute
  '/admin/database/boker': typeof administrasjonAdminDatabaseBokerRoute
  '/admin/database/brukere': typeof administrasjonAdminDatabaseBrukereRoute
  '/admin/database/dynamisk_innhold': typeof administrasjonAdminDatabaseDynamisk_innholdRoute
  '/admin/database/filialer': typeof administrasjonAdminDatabaseFilialerRoute
  '/admin/database/rapporter': typeof administrasjonAdminDatabaseRapporterRoute
  '/admin/database/selskap': typeof administrasjonAdminDatabaseSelskapRoute
  '/admin/database/unik_id': typeof administrasjonAdminDatabaseUnik_idRoute
  '/admin/kommunikasjon/paminnelser': typeof administrasjonAdminKommunikasjonPaminnelserRoute
  '/admin/kommunikasjon/utsendelser': typeof administrasjonAdminKommunikasjonUtsendelserRoute
  '/admin/overleveringer/$matchId': typeof administrasjonAdminOverleveringerMatchIdRoute
  '/auth/login/forgot': typeof legacyAuthLoginForgotRoute
  '/auth/register/detail': typeof legacyAuthRegisterDetailRoute
  '/auth/social/failure': typeof legacyAuthSocialFailureRoute
  '/database/branches/edit': typeof legacyDatabaseBranchesEditRoute
  '/auth/permission/denied': typeof offentligAuthPermissionDeniedRoute
  '/auth/reset/$id': typeof offentligAuthResetIdRoute
  '/info/branch/$branchId': typeof offentligInfoBranchBranchIdRoute
  '/info/policies/conditions': typeof offentligInfoPoliciesConditionsRoute
  '/info/policies/privacy': typeof offentligInfoPoliciesPrivacyRoute
  '/info/policies/terms': typeof offentligInfoPoliciesTermsRoute
  '/kasse/betaling/status': typeof offentligKasseBetalingStatusRoute
  '/admin/overleveringer': typeof administrasjonAdminOverleveringerIndexRoute
  '/kasse/betaling': typeof offentligKasseBetalingIndexRoute
  '/auth/email/verify/$verificationId': typeof offentligAuthEmailVerifyVerificationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(offentlig)': typeof offentligRouteRouteWithChildren
  '/health': typeof HealthRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/(administrasjon)/admin': typeof administrasjonAdminRouteRouteWithChildren
  '/(offentlig)/info': typeof offentligInfoRouteRouteWithChildren
  '/(offentlig)/overleveringer': typeof offentligOverleveringerRouteRouteWithChildren
  '/(legacy)/welcome': typeof legacyWelcomeRoute
  '/(offentlig)/handlekurv': typeof offentligHandlekurvRoute
  '/(offentlig)/items': typeof offentligItemsRoute
  '/(offentlig)/oppgaver': typeof offentligOppgaverRoute
  '/(offentlig)/order-history': typeof offentligOrderHistoryRoute
  '/(offentlig)/sjekk': typeof offentligSjekkRoute
  '/(offentlig)/user-settings': typeof offentligUserSettingsRoute
  '/(administrasjon)/admin/overleveringer': typeof administrasjonAdminOverleveringerRouteRouteWithChildren
  '/(offentlig)/info/branch': typeof offentligInfoBranchRouteRouteWithChildren
  '/(offentlig)/info/policies': typeof offentligInfoPoliciesRouteRouteWithChildren
  '/(administrasjon)/admin/blid': typeof administrasjonAdminBlidRoute
  '/(administrasjon)/admin/faktura': typeof administrasjonAdminFakturaRoute
  '/(administrasjon)/admin/handlekurv': typeof administrasjonAdminHandlekurvRoute
  '/(administrasjon)/admin/hurtiginnsamling': typeof administrasjonAdminHurtiginnsamlingRoute
  '/(administrasjon)/admin/hurtigutdeling': typeof administrasjonAdminHurtigutdelingRoute
  '/(administrasjon)/admin/ordreoversikt': typeof administrasjonAdminOrdreoversiktRoute
  '/(administrasjon)/admin/scanner': typeof administrasjonAdminScannerRoute
  '/(administrasjon)/admin/user-settings': typeof administrasjonAdminUserSettingsRoute
  '/(administrasjon)/admin/venteliste': typeof administrasjonAdminVentelisteRoute
  '/(legacy)/auth/menu': typeof legacyAuthMenuRoute
  '/(legacy)/auth/success': typeof legacyAuthSuccessRoute
  '/(legacy)/database/companies': typeof legacyDatabaseCompaniesRoute
  '/(legacy)/u/edit': typeof legacyUEditRoute
  '/(offentlig)/auth/failure': typeof offentligAuthFailureRoute
  '/(offentlig)/auth/forgot': typeof offentligAuthForgotRoute
  '/(offentlig)/auth/login': typeof offentligAuthLoginRoute
  '/(offentlig)/auth/logout': typeof offentligAuthLogoutRoute
  '/(offentlig)/auth/register': typeof offentligAuthRegisterRoute
  '/(offentlig)/auth/token': typeof offentligAuthTokenRoute
  '/(offentlig)/bestilling/$branchId': typeof offentligBestillingBranchIdRoute
  '/(offentlig)/info/about': typeof offentligInfoAboutRoute
  '/(offentlig)/info/buyback': typeof offentligInfoBuybackRoute
  '/(offentlig)/info/companies': typeof offentligInfoCompaniesRoute
  '/(offentlig)/info/contact': typeof offentligInfoContactRoute
  '/(offentlig)/info/faq': typeof offentligInfoFaqRoute
  '/(offentlig)/info/general': typeof offentligInfoGeneralRoute
  '/(offentlig)/info/pupils': typeof offentligInfoPupilsRoute
  '/(offentlig)/kasse/bekreft': typeof offentligKasseBekreftRoute
  '/(offentlig)/overleveringer/$matchId': typeof offentligOverleveringerMatchIdRoute
  '/(offentlig)/signering/$userDetailId': typeof offentligSigneringUserDetailIdRoute
  '/(administrasjon)/admin/': typeof administrasjonAdminIndexRoute
  '/(offentlig)/bestilling/': typeof offentligBestillingIndexRoute
  '/(offentlig)/kasse/': typeof offentligKasseIndexRoute
  '/(offentlig)/overleveringer/': typeof offentligOverleveringerIndexRoute
  '/(administrasjon)/admin/database/boker': typeof administrasjonAdminDatabaseBokerRoute
  '/(administrasjon)/admin/database/brukere': typeof administrasjonAdminDatabaseBrukereRoute
  '/(administrasjon)/admin/database/dynamisk_innhold': typeof administrasjonAdminDatabaseDynamisk_innholdRoute
  '/(administrasjon)/admin/database/filialer': typeof administrasjonAdminDatabaseFilialerRoute
  '/(administrasjon)/admin/database/rapporter': typeof administrasjonAdminDatabaseRapporterRoute
  '/(administrasjon)/admin/database/selskap': typeof administrasjonAdminDatabaseSelskapRoute
  '/(administrasjon)/admin/database/unik_id': typeof administrasjonAdminDatabaseUnik_idRoute
  '/(administrasjon)/admin/kommunikasjon/paminnelser': typeof administrasjonAdminKommunikasjonPaminnelserRoute
  '/(administrasjon)/admin/kommunikasjon/utsendelser': typeof administrasjonAdminKommunikasjonUtsendelserRoute
  '/(administrasjon)/admin/overleveringer/$matchId': typeof administrasjonAdminOverleveringerMatchIdRoute
  '/(legacy)/auth/login/forgot': typeof legacyAuthLoginForgotRoute
  '/(legacy)/auth/register/detail': typeof legacyAuthRegisterDetailRoute
  '/(legacy)/auth/social/failure': typeof legacyAuthSocialFailureRoute
  '/(legacy)/database/branches/edit': typeof legacyDatabaseBranchesEditRoute
  '/(offentlig)/auth/permission/denied': typeof offentligAuthPermissionDeniedRoute
  '/(offentlig)/auth/reset/$id': typeof offentligAuthResetIdRoute
  '/(offentlig)/info/branch/$branchId': typeof offentligInfoBranchBranchIdRoute
  '/(offentlig)/info/policies/conditions': typeof offentligInfoPoliciesConditionsRoute
  '/(offentlig)/info/policies/privacy': typeof offentligInfoPoliciesPrivacyRoute
  '/(offentlig)/info/policies/terms': typeof offentligInfoPoliciesTermsRoute
  '/(offentlig)/kasse/betaling/status': typeof offentligKasseBetalingStatusRoute
  '/(administrasjon)/admin/overleveringer/': typeof administrasjonAdminOverleveringerIndexRoute
  '/(offentlig)/kasse/betaling/': typeof offentligKasseBetalingIndexRoute
  '/(offentlig)/auth/email/verify/$verificationId': typeof offentligAuthEmailVerifyVerificationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin'
    | '/info'
    | '/overleveringer'
    | '/welcome'
    | '/handlekurv'
    | '/items'
    | '/oppgaver'
    | '/order-history'
    | '/sjekk'
    | '/user-settings'
    | '/admin/overleveringer'
    | '/info/branch'
    | '/info/policies'
    | '/admin/blid'
    | '/admin/faktura'
    | '/admin/handlekurv'
    | '/admin/hurtiginnsamling'
    | '/admin/hurtigutdeling'
    | '/admin/ordreoversikt'
    | '/admin/scanner'
    | '/admin/user-settings'
    | '/admin/venteliste'
    | '/auth/menu'
    | '/auth/success'
    | '/database/companies'
    | '/u/edit'
    | '/auth/failure'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/register'
    | '/auth/token'
    | '/bestilling/$branchId'
    | '/info/about'
    | '/info/buyback'
    | '/info/companies'
    | '/info/contact'
    | '/info/faq'
    | '/info/general'
    | '/info/pupils'
    | '/kasse/bekreft'
    | '/overleveringer/$matchId'
    | '/signering/$userDetailId'
    | '/admin/'
    | '/bestilling/'
    | '/kasse/'
    | '/overleveringer/'
    | '/admin/database/boker'
    | '/admin/database/brukere'
    | '/admin/database/dynamisk_innhold'
    | '/admin/database/filialer'
    | '/admin/database/rapporter'
    | '/admin/database/selskap'
    | '/admin/database/unik_id'
    | '/admin/kommunikasjon/paminnelser'
    | '/admin/kommunikasjon/utsendelser'
    | '/admin/overleveringer/$matchId'
    | '/auth/login/forgot'
    | '/auth/register/detail'
    | '/auth/social/failure'
    | '/database/branches/edit'
    | '/auth/permission/denied'
    | '/auth/reset/$id'
    | '/info/branch/$branchId'
    | '/info/policies/conditions'
    | '/info/policies/privacy'
    | '/info/policies/terms'
    | '/kasse/betaling/status'
    | '/admin/overleveringer/'
    | '/kasse/betaling/'
    | '/auth/email/verify/$verificationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/info'
    | '/welcome'
    | '/handlekurv'
    | '/items'
    | '/oppgaver'
    | '/order-history'
    | '/sjekk'
    | '/user-settings'
    | '/info/branch'
    | '/info/policies'
    | '/admin/blid'
    | '/admin/faktura'
    | '/admin/handlekurv'
    | '/admin/hurtiginnsamling'
    | '/admin/hurtigutdeling'
    | '/admin/ordreoversikt'
    | '/admin/scanner'
    | '/admin/user-settings'
    | '/admin/venteliste'
    | '/auth/menu'
    | '/auth/success'
    | '/database/companies'
    | '/u/edit'
    | '/auth/failure'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/register'
    | '/auth/token'
    | '/bestilling/$branchId'
    | '/info/about'
    | '/info/buyback'
    | '/info/companies'
    | '/info/contact'
    | '/info/faq'
    | '/info/general'
    | '/info/pupils'
    | '/kasse/bekreft'
    | '/overleveringer/$matchId'
    | '/signering/$userDetailId'
    | '/admin'
    | '/bestilling'
    | '/kasse'
    | '/overleveringer'
    | '/admin/database/boker'
    | '/admin/database/brukere'
    | '/admin/database/dynamisk_innhold'
    | '/admin/database/filialer'
    | '/admin/database/rapporter'
    | '/admin/database/selskap'
    | '/admin/database/unik_id'
    | '/admin/kommunikasjon/paminnelser'
    | '/admin/kommunikasjon/utsendelser'
    | '/admin/overleveringer/$matchId'
    | '/auth/login/forgot'
    | '/auth/register/detail'
    | '/auth/social/failure'
    | '/database/branches/edit'
    | '/auth/permission/denied'
    | '/auth/reset/$id'
    | '/info/branch/$branchId'
    | '/info/policies/conditions'
    | '/info/policies/privacy'
    | '/info/policies/terms'
    | '/kasse/betaling/status'
    | '/admin/overleveringer'
    | '/kasse/betaling'
    | '/auth/email/verify/$verificationId'
  id:
    | '__root__'
    | '/'
    | '/(offentlig)'
    | '/health'
    | '/llms.txt'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/(administrasjon)/admin'
    | '/(offentlig)/info'
    | '/(offentlig)/overleveringer'
    | '/(legacy)/welcome'
    | '/(offentlig)/handlekurv'
    | '/(offentlig)/items'
    | '/(offentlig)/oppgaver'
    | '/(offentlig)/order-history'
    | '/(offentlig)/sjekk'
    | '/(offentlig)/user-settings'
    | '/(administrasjon)/admin/overleveringer'
    | '/(offentlig)/info/branch'
    | '/(offentlig)/info/policies'
    | '/(administrasjon)/admin/blid'
    | '/(administrasjon)/admin/faktura'
    | '/(administrasjon)/admin/handlekurv'
    | '/(administrasjon)/admin/hurtiginnsamling'
    | '/(administrasjon)/admin/hurtigutdeling'
    | '/(administrasjon)/admin/ordreoversikt'
    | '/(administrasjon)/admin/scanner'
    | '/(administrasjon)/admin/user-settings'
    | '/(administrasjon)/admin/venteliste'
    | '/(legacy)/auth/menu'
    | '/(legacy)/auth/success'
    | '/(legacy)/database/companies'
    | '/(legacy)/u/edit'
    | '/(offentlig)/auth/failure'
    | '/(offentlig)/auth/forgot'
    | '/(offentlig)/auth/login'
    | '/(offentlig)/auth/logout'
    | '/(offentlig)/auth/register'
    | '/(offentlig)/auth/token'
    | '/(offentlig)/bestilling/$branchId'
    | '/(offentlig)/info/about'
    | '/(offentlig)/info/buyback'
    | '/(offentlig)/info/companies'
    | '/(offentlig)/info/contact'
    | '/(offentlig)/info/faq'
    | '/(offentlig)/info/general'
    | '/(offentlig)/info/pupils'
    | '/(offentlig)/kasse/bekreft'
    | '/(offentlig)/overleveringer/$matchId'
    | '/(offentlig)/signering/$userDetailId'
    | '/(administrasjon)/admin/'
    | '/(offentlig)/bestilling/'
    | '/(offentlig)/kasse/'
    | '/(offentlig)/overleveringer/'
    | '/(administrasjon)/admin/database/boker'
    | '/(administrasjon)/admin/database/brukere'
    | '/(administrasjon)/admin/database/dynamisk_innhold'
    | '/(administrasjon)/admin/database/filialer'
    | '/(administrasjon)/admin/database/rapporter'
    | '/(administrasjon)/admin/database/selskap'
    | '/(administrasjon)/admin/database/unik_id'
    | '/(administrasjon)/admin/kommunikasjon/paminnelser'
    | '/(administrasjon)/admin/kommunikasjon/utsendelser'
    | '/(administrasjon)/admin/overleveringer/$matchId'
    | '/(legacy)/auth/login/forgot'
    | '/(legacy)/auth/register/detail'
    | '/(legacy)/auth/social/failure'
    | '/(legacy)/database/branches/edit'
    | '/(offentlig)/auth/permission/denied'
    | '/(offentlig)/auth/reset/$id'
    | '/(offentlig)/info/branch/$branchId'
    | '/(offentlig)/info/policies/conditions'
    | '/(offentlig)/info/policies/privacy'
    | '/(offentlig)/info/policies/terms'
    | '/(offentlig)/kasse/betaling/status'
    | '/(administrasjon)/admin/overleveringer/'
    | '/(offentlig)/kasse/betaling/'
    | '/(offentlig)/auth/email/verify/$verificationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  offentligRouteRoute: typeof offentligRouteRouteWithChildren
  HealthRoute: typeof HealthRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  administrasjonAdminRouteRoute: typeof administrasjonAdminRouteRouteWithChildren
  legacyWelcomeRoute: typeof legacyWelcomeRoute
  legacyAuthMenuRoute: typeof legacyAuthMenuRoute
  legacyAuthSuccessRoute: typeof legacyAuthSuccessRoute
  legacyDatabaseCompaniesRoute: typeof legacyDatabaseCompaniesRoute
  legacyUEditRoute: typeof legacyUEditRoute
  legacyAuthLoginForgotRoute: typeof legacyAuthLoginForgotRoute
  legacyAuthRegisterDetailRoute: typeof legacyAuthRegisterDetailRoute
  legacyAuthSocialFailureRoute: typeof legacyAuthSocialFailureRoute
  legacyDatabaseBranchesEditRoute: typeof legacyDatabaseBranchesEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(offentlig)': {
      id: '/(offentlig)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof offentligRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(administrasjon)/admin': {
      id: '/(administrasjon)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof administrasjonAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legacy)/welcome': {
      id: '/(legacy)/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof legacyWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(offentlig)/handlekurv': {
      id: '/(offentlig)/handlekurv'
      path: '/handlekurv'
      fullPath: '/handlekurv'
      preLoaderRoute: typeof offentligHandlekurvRouteImport
      parentRoute: typeof offentligRouteRoute
    }
    '/(offentlig)/info': {
      id: '/(offentlig)/info'
      path: '/info'
      fullPath: '/info'
      preLoaderRoute: typeof offentligInfoRouteRouteImport
      parentRoute: typeof offentligRouteRoute
    }
    '/(offentlig)/items': {
      id: '/(offentlig)/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof offentligItemsRouteImport
      parentRoute: typeof offentligRouteRoute
    }
    '/(offentlig)/oppgaver': {
      id: '/(offentlig)/oppgaver'
      path: '/oppgaver'
      fullPath: '/oppgaver'
      preLoaderRoute: typeof offentligOppgaverRouteImport
      parentRoute: typeof offentligRouteRoute
    }
    '/(offentlig)/order-history': {
      id: '/(offentlig)/order-history'
      path: '/order-history'
      fullPath: '/order-history'
      preLoaderRoute: typeof offentligOrderHistoryRouteImport
      parentRoute: typeof offentligRouteRoute
    }
    '/(offentlig)/overleveringer': {
      id: '/(offentlig)/overleveringer'
      path: '/overleveringer'
      fullPath: '/overleveringer'
      preLoaderRoute: typeof offentligOverleveringerRouteRouteImport
      parentRoute: typeof offentligRouteRoute
    }
    '/(offentlig)/sjekk': {
      id: '/(offentlig)/sjekk'
      path: '/sjekk'
      fullPath: '/sjekk'
      preLoaderRoute: typeof offentligSjekkRouteImport
      parentRoute: typeof offentligRouteRoute
    }
    '/(offentlig)/user-settings': {
      id: '/(offentlig)/user-settings'
      path: '/user-settings'
      fullPath: '/user-settings'
      preLoaderRoute: typeof offentligUserSettingsRouteImport
      parentRoute: typeof offentligRouteRoute
    }
    '/(administrasjon)/admin/': {
      id: '/(administrasjon)/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof administrasjonAdminIndexRouteImport
      parentRoute: typeof administrasjonAdminRouteRoute
    }
    '/(administrasjon)/admin/blid': {
      id: '/(administrasjon)/admin/blid'
      path: '/blid'
      fullPath: '/admin/blid'
      preLoaderRoute: typeof administrasjonAdminBlidRouteImport
      parentRoute: typeof administrasjonAdminRouteRoute
    }
    '/(administrasjon)/admin/faktura': {
      id: '/(administrasjon)/admin/faktura'
      path: '/faktura'
      fullPath: '/admin/faktura'
      preLoaderRoute: typeof administrasjonAdminFakturaRouteImport
      parentRoute: typeof administrasjonAdminRouteRoute
    }
    '/(administrasjon)/admin/handlekurv': {
      id: '/(administrasjon)/admin/handlekurv'
      path: '/handlekurv'
      fullPath: '/admin/handlekurv'
      preLoaderRoute: typeof administrasjonAdminHandlekurvRouteImport
      parentRoute: typeof administrasjonAdminRouteRoute
    }
    '/(administrasjon)/admin/hurtiginnsamling': {
      id: '/(administrasjon)/admin/hurtiginnsamling'
      path: '/hurtiginnsamling'
      fullPath: '/admin/hurtiginnsamling'
      preLoaderRoute: typeof administrasjonAdminHurtiginnsamlingRouteImport
      parentRoute: typeof administrasjonAdminRouteRoute
    }
    '/(administrasjon)/admin/hurtigutdeling': {
      id: '/(administrasjon)/admin/hurtigutdeling'
      path: '/hurtigutdeling'
      fullPath: '/admin/hurtigutdeling'
      preLoaderRoute: typeof administrasjonAdminHurtigutdelingRouteImport
      parentRoute: typeof administrasjonAdminRouteRoute
    }
    '/(administrasjon)/admin/ordreoversikt': {
      id: '/(administrasjon)/admin/ordreoversikt'
      path: '/ordreoversikt'
      fullPath: '/admin/ordreoversikt'
      preLoaderRoute: typeof administrasjonAdminOrdreoversiktRouteImport
      parentRoute: typeof administrasjonAdminRouteRoute
    }
    '/(administrasjon)/admin/overleveringer': {
      id: '/(administrasjon)/admin/overleveringer'
      path: '/overleveringer'
      fullPath: '/admin/overleveringer'
      preLoaderRoute: typeof administrasjonAdminOverleveringerRouteRouteImport
      parentRoute: typeof administrasjonAdminRouteRoute
    }
    '/(administrasjon)/admin/scanner': {
      id: '/(administrasjon)/admin/scanner'
      path: '/scanner'
      fullPath: '/admin/scanner'
      preLoaderRoute: typeof administrasjonAdminScannerRouteImport
      parentRoute: typeof administrasjonAdminRouteRoute
    }
    '/(administrasjon)/admin/user-settings': {
      id: '/(administrasjon)/admin/user-settings'
      path: '/user-settings'
      fullPath: '/admin/user-settings'
      preLoaderRoute: typeof administrasjonAdminUserSettingsRouteImport
      parentRoute: typeof administrasjonAdminRouteRoute
    }
    '/(administrasjon)/admin/venteliste': {
      id: '/(administrasjon)/admin/venteliste'
      path: '/venteliste'
      fullPath: '/admin/venteliste'
      preLoaderRoute: typeof administrasjonAdminVentelisteRouteImport
      parentRoute: typeof administrasjonAdminRouteRoute
    }
    '/(legacy)/auth/menu': {
      id: '/(legacy)/auth/menu'
      path: '/auth/menu'
      fullPath: '/auth/menu'
      preLoaderRoute: typeof legacyAuthMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legacy)/auth/success': {
      id: '/(legacy)/auth/success'
      path: '/auth/success'
      fullPath: '/auth/success'
      preLoaderRoute: typeof legacyAuthSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legacy)/database/companies': {
      id: '/(legacy)/database/companies'
      path: '/database/companies'
      fullPath: '/database/companies'
      preLoaderRoute: typeof legacyDatabaseCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legacy)/u/edit': {
      id: '/(legacy)/u/edit'
      path: '/u/edit'
      fullPath: '/u/edit'
      preLoaderRoute: typeof legacyUEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(offentlig)/auth/failure': {
      id: '/(offentlig)/auth/failure'
      path: '/auth/failure'
      fullPath: '/auth/failure'
      preLoaderRoute: typeof offentligAuthFailureRouteImport
      parentRoute: typeof offentligRouteRoute
    }
    '/(offentlig)/auth/forgot': {
      id: '/(offentlig)/auth/forgot'
      path: '/auth/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof offentligAuthForgotRouteImport
      parentRoute: typeof offentligRouteRoute
    }
    '/(offentlig)/auth/login': {
      id: '/(offentlig)/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof offentligAuthLoginRouteImport
      parentRoute: typeof offentligRouteRoute
    }
    '/(offentlig)/auth/logout': {
      id: '/(offentlig)/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof offentligAuthLogoutRouteImport
      parentRoute: typeof offentligRouteRoute
    }
    '/(offentlig)/auth/register': {
      id: '/(offentlig)/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof offentligAuthRegisterRouteImport
      parentRoute: typeof offentligRouteRoute
    }
    '/(offentlig)/auth/token': {
      id: '/(offentlig)/auth/token'
      path: '/auth/token'
      fullPath: '/auth/token'
      preLoaderRoute: typeof offentligAuthTokenRouteImport
      parentRoute: typeof offentligRouteRoute
    }
    '/(offentlig)/bestilling/': {
      id: '/(offentlig)/bestilling/'
      path: '/bestilling'
      fullPath: '/bestilling/'
      preLoaderRoute: typeof offentligBestillingIndexRouteImport
      parentRoute: typeof offentligRouteRoute
    }
    '/(offentlig)/bestilling/$branchId': {
      id: '/(offentlig)/bestilling/$branchId'
      path: '/bestilling/$branchId'
      fullPath: '/bestilling/$branchId'
      preLoaderRoute: typeof offentligBestillingBranchIdRouteImport
      parentRoute: typeof offentligRouteRoute
    }
    '/(offentlig)/info/about': {
      id: '/(offentlig)/info/about'
      path: '/about'
      fullPath: '/info/about'
      preLoaderRoute: typeof offentligInfoAboutRouteImport
      parentRoute: typeof offentligInfoRouteRoute
    }
    '/(offentlig)/info/branch': {
      id: '/(offentlig)/info/branch'
      path: '/branch'
      fullPath: '/info/branch'
      preLoaderRoute: typeof offentligInfoBranchRouteRouteImport
      parentRoute: typeof offentligInfoRouteRoute
    }
    '/(offentlig)/info/buyback': {
      id: '/(offentlig)/info/buyback'
      path: '/buyback'
      fullPath: '/info/buyback'
      preLoaderRoute: typeof offentligInfoBuybackRouteImport
      parentRoute: typeof offentligInfoRouteRoute
    }
    '/(offentlig)/info/companies': {
      id: '/(offentlig)/info/companies'
      path: '/companies'
      fullPath: '/info/companies'
      preLoaderRoute: typeof offentligInfoCompaniesRouteImport
      parentRoute: typeof offentligInfoRouteRoute
    }
    '/(offentlig)/info/contact': {
      id: '/(offentlig)/info/contact'
      path: '/contact'
      fullPath: '/info/contact'
      preLoaderRoute: typeof offentligInfoContactRouteImport
      parentRoute: typeof offentligInfoRouteRoute
    }
    '/(offentlig)/info/faq': {
      id: '/(offentlig)/info/faq'
      path: '/faq'
      fullPath: '/info/faq'
      preLoaderRoute: typeof offentligInfoFaqRouteImport
      parentRoute: typeof offentligInfoRouteRoute
    }
    '/(offentlig)/info/general': {
      id: '/(offentlig)/info/general'
      path: '/general'
      fullPath: '/info/general'
      preLoaderRoute: typeof offentligInfoGeneralRouteImport
      parentRoute: typeof offentligInfoRouteRoute
    }
    '/(offentlig)/info/policies': {
      id: '/(offentlig)/info/policies'
      path: '/policies'
      fullPath: '/info/policies'
      preLoaderRoute: typeof offentligInfoPoliciesRouteRouteImport
      parentRoute: typeof offentligInfoRouteRoute
    }
    '/(offentlig)/info/pupils': {
      id: '/(offentlig)/info/pupils'
      path: '/pupils'
      fullPath: '/info/pupils'
      preLoaderRoute: typeof offentligInfoPupilsRouteImport
      parentRoute: typeof offentligInfoRouteRoute
    }
    '/(offentlig)/kasse/': {
      id: '/(offentlig)/kasse/'
      path: '/kasse'
      fullPath: '/kasse/'
      preLoaderRoute: typeof offentligKasseIndexRouteImport
      parentRoute: typeof offentligRouteRoute
    }
    '/(offentlig)/kasse/bekreft': {
      id: '/(offentlig)/kasse/bekreft'
      path: '/kasse/bekreft'
      fullPath: '/kasse/bekreft'
      preLoaderRoute: typeof offentligKasseBekreftRouteImport
      parentRoute: typeof offentligRouteRoute
    }
    '/(offentlig)/overleveringer/': {
      id: '/(offentlig)/overleveringer/'
      path: '/'
      fullPath: '/overleveringer/'
      preLoaderRoute: typeof offentligOverleveringerIndexRouteImport
      parentRoute: typeof offentligOverleveringerRouteRoute
    }
    '/(offentlig)/overleveringer/$matchId': {
      id: '/(offentlig)/overleveringer/$matchId'
      path: '/$matchId'
      fullPath: '/overleveringer/$matchId'
      preLoaderRoute: typeof offentligOverleveringerMatchIdRouteImport
      parentRoute: typeof offentligOverleveringerRouteRoute
    }
    '/(offentlig)/signering/$userDetailId': {
      id: '/(offentlig)/signering/$userDetailId'
      path: '/signering/$userDetailId'
      fullPath: '/signering/$userDetailId'
      preLoaderRoute: typeof offentligSigneringUserDetailIdRouteImport
      parentRoute: typeof offentligRouteRoute
    }
    '/(administrasjon)/admin/database/boker': {
      id: '/(administrasjon)/admin/database/boker'
      path: '/database/boker'
      fullPath: '/admin/database/boker'
      preLoaderRoute: typeof administrasjonAdminDatabaseBokerRouteImport
      parentRoute: typeof administrasjonAdminRouteRoute
    }
    '/(administrasjon)/admin/database/brukere': {
      id: '/(administrasjon)/admin/database/brukere'
      path: '/database/brukere'
      fullPath: '/admin/database/brukere'
      preLoaderRoute: typeof administrasjonAdminDatabaseBrukereRouteImport
      parentRoute: typeof administrasjonAdminRouteRoute
    }
    '/(administrasjon)/admin/database/dynamisk_innhold': {
      id: '/(administrasjon)/admin/database/dynamisk_innhold'
      path: '/database/dynamisk_innhold'
      fullPath: '/admin/database/dynamisk_innhold'
      preLoaderRoute: typeof administrasjonAdminDatabaseDynamisk_innholdRouteImport
      parentRoute: typeof administrasjonAdminRouteRoute
    }
    '/(administrasjon)/admin/database/filialer': {
      id: '/(administrasjon)/admin/database/filialer'
      path: '/database/filialer'
      fullPath: '/admin/database/filialer'
      preLoaderRoute: typeof administrasjonAdminDatabaseFilialerRouteImport
      parentRoute: typeof administrasjonAdminRouteRoute
    }
    '/(administrasjon)/admin/database/rapporter': {
      id: '/(administrasjon)/admin/database/rapporter'
      path: '/database/rapporter'
      fullPath: '/admin/database/rapporter'
      preLoaderRoute: typeof administrasjonAdminDatabaseRapporterRouteImport
      parentRoute: typeof administrasjonAdminRouteRoute
    }
    '/(administrasjon)/admin/database/selskap': {
      id: '/(administrasjon)/admin/database/selskap'
      path: '/database/selskap'
      fullPath: '/admin/database/selskap'
      preLoaderRoute: typeof administrasjonAdminDatabaseSelskapRouteImport
      parentRoute: typeof administrasjonAdminRouteRoute
    }
    '/(administrasjon)/admin/database/unik_id': {
      id: '/(administrasjon)/admin/database/unik_id'
      path: '/database/unik_id'
      fullPath: '/admin/database/unik_id'
      preLoaderRoute: typeof administrasjonAdminDatabaseUnik_idRouteImport
      parentRoute: typeof administrasjonAdminRouteRoute
    }
    '/(administrasjon)/admin/kommunikasjon/paminnelser': {
      id: '/(administrasjon)/admin/kommunikasjon/paminnelser'
      path: '/kommunikasjon/paminnelser'
      fullPath: '/admin/kommunikasjon/paminnelser'
      preLoaderRoute: typeof administrasjonAdminKommunikasjonPaminnelserRouteImport
      parentRoute: typeof administrasjonAdminRouteRoute
    }
    '/(administrasjon)/admin/kommunikasjon/utsendelser': {
      id: '/(administrasjon)/admin/kommunikasjon/utsendelser'
      path: '/kommunikasjon/utsendelser'
      fullPath: '/admin/kommunikasjon/utsendelser'
      preLoaderRoute: typeof administrasjonAdminKommunikasjonUtsendelserRouteImport
      parentRoute: typeof administrasjonAdminRouteRoute
    }
    '/(administrasjon)/admin/overleveringer/': {
      id: '/(administrasjon)/admin/overleveringer/'
      path: '/'
      fullPath: '/admin/overleveringer/'
      preLoaderRoute: typeof administrasjonAdminOverleveringerIndexRouteImport
      parentRoute: typeof administrasjonAdminOverleveringerRouteRoute
    }
    '/(administrasjon)/admin/overleveringer/$matchId': {
      id: '/(administrasjon)/admin/overleveringer/$matchId'
      path: '/$matchId'
      fullPath: '/admin/overleveringer/$matchId'
      preLoaderRoute: typeof administrasjonAdminOverleveringerMatchIdRouteImport
      parentRoute: typeof administrasjonAdminOverleveringerRouteRoute
    }
    '/(legacy)/auth/login/forgot': {
      id: '/(legacy)/auth/login/forgot'
      path: '/auth/login/forgot'
      fullPath: '/auth/login/forgot'
      preLoaderRoute: typeof legacyAuthLoginForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legacy)/auth/register/detail': {
      id: '/(legacy)/auth/register/detail'
      path: '/auth/register/detail'
      fullPath: '/auth/register/detail'
      preLoaderRoute: typeof legacyAuthRegisterDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legacy)/auth/social/failure': {
      id: '/(legacy)/auth/social/failure'
      path: '/auth/social/failure'
      fullPath: '/auth/social/failure'
      preLoaderRoute: typeof legacyAuthSocialFailureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legacy)/database/branches/edit': {
      id: '/(legacy)/database/branches/edit'
      path: '/database/branches/edit'
      fullPath: '/database/branches/edit'
      preLoaderRoute: typeof legacyDatabaseBranchesEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(offentlig)/auth/permission/denied': {
      id: '/(offentlig)/auth/permission/denied'
      path: '/auth/permission/denied'
      fullPath: '/auth/permission/denied'
      preLoaderRoute: typeof offentligAuthPermissionDeniedRouteImport
      parentRoute: typeof offentligRouteRoute
    }
    '/(offentlig)/auth/reset/$id': {
      id: '/(offentlig)/auth/reset/$id'
      path: '/auth/reset/$id'
      fullPath: '/auth/reset/$id'
      preLoaderRoute: typeof offentligAuthResetIdRouteImport
      parentRoute: typeof offentligRouteRoute
    }
    '/(offentlig)/info/branch/$branchId': {
      id: '/(offentlig)/info/branch/$branchId'
      path: '/$branchId'
      fullPath: '/info/branch/$branchId'
      preLoaderRoute: typeof offentligInfoBranchBranchIdRouteImport
      parentRoute: typeof offentligInfoBranchRouteRoute
    }
    '/(offentlig)/info/policies/conditions': {
      id: '/(offentlig)/info/policies/conditions'
      path: '/conditions'
      fullPath: '/info/policies/conditions'
      preLoaderRoute: typeof offentligInfoPoliciesConditionsRouteImport
      parentRoute: typeof offentligInfoPoliciesRouteRoute
    }
    '/(offentlig)/info/policies/privacy': {
      id: '/(offentlig)/info/policies/privacy'
      path: '/privacy'
      fullPath: '/info/policies/privacy'
      preLoaderRoute: typeof offentligInfoPoliciesPrivacyRouteImport
      parentRoute: typeof offentligInfoPoliciesRouteRoute
    }
    '/(offentlig)/info/policies/terms': {
      id: '/(offentlig)/info/policies/terms'
      path: '/terms'
      fullPath: '/info/policies/terms'
      preLoaderRoute: typeof offentligInfoPoliciesTermsRouteImport
      parentRoute: typeof offentligInfoPoliciesRouteRoute
    }
    '/(offentlig)/kasse/betaling/': {
      id: '/(offentlig)/kasse/betaling/'
      path: '/kasse/betaling'
      fullPath: '/kasse/betaling/'
      preLoaderRoute: typeof offentligKasseBetalingIndexRouteImport
      parentRoute: typeof offentligRouteRoute
    }
    '/(offentlig)/kasse/betaling/status': {
      id: '/(offentlig)/kasse/betaling/status'
      path: '/kasse/betaling/status'
      fullPath: '/kasse/betaling/status'
      preLoaderRoute: typeof offentligKasseBetalingStatusRouteImport
      parentRoute: typeof offentligRouteRoute
    }
    '/(offentlig)/auth/email/verify/$verificationId': {
      id: '/(offentlig)/auth/email/verify/$verificationId'
      path: '/auth/email/verify/$verificationId'
      fullPath: '/auth/email/verify/$verificationId'
      preLoaderRoute: typeof offentligAuthEmailVerifyVerificationIdRouteImport
      parentRoute: typeof offentligRouteRoute
    }
  }
}

interface offentligInfoBranchRouteRouteChildren {
  offentligInfoBranchBranchIdRoute: typeof offentligInfoBranchBranchIdRoute
}

const offentligInfoBranchRouteRouteChildren: offentligInfoBranchRouteRouteChildren =
  {
    offentligInfoBranchBranchIdRoute: offentligInfoBranchBranchIdRoute,
  }

const offentligInfoBranchRouteRouteWithChildren =
  offentligInfoBranchRouteRoute._addFileChildren(
    offentligInfoBranchRouteRouteChildren,
  )

interface offentligInfoPoliciesRouteRouteChildren {
  offentligInfoPoliciesConditionsRoute: typeof offentligInfoPoliciesConditionsRoute
  offentligInfoPoliciesPrivacyRoute: typeof offentligInfoPoliciesPrivacyRoute
  offentligInfoPoliciesTermsRoute: typeof offentligInfoPoliciesTermsRoute
}

const offentligInfoPoliciesRouteRouteChildren: offentligInfoPoliciesRouteRouteChildren =
  {
    offentligInfoPoliciesConditionsRoute: offentligInfoPoliciesConditionsRoute,
    offentligInfoPoliciesPrivacyRoute: offentligInfoPoliciesPrivacyRoute,
    offentligInfoPoliciesTermsRoute: offentligInfoPoliciesTermsRoute,
  }

const offentligInfoPoliciesRouteRouteWithChildren =
  offentligInfoPoliciesRouteRoute._addFileChildren(
    offentligInfoPoliciesRouteRouteChildren,
  )

interface offentligInfoRouteRouteChildren {
  offentligInfoBranchRouteRoute: typeof offentligInfoBranchRouteRouteWithChildren
  offentligInfoPoliciesRouteRoute: typeof offentligInfoPoliciesRouteRouteWithChildren
  offentligInfoAboutRoute: typeof offentligInfoAboutRoute
  offentligInfoBuybackRoute: typeof offentligInfoBuybackRoute
  offentligInfoCompaniesRoute: typeof offentligInfoCompaniesRoute
  offentligInfoContactRoute: typeof offentligInfoContactRoute
  offentligInfoFaqRoute: typeof offentligInfoFaqRoute
  offentligInfoGeneralRoute: typeof offentligInfoGeneralRoute
  offentligInfoPupilsRoute: typeof offentligInfoPupilsRoute
}

const offentligInfoRouteRouteChildren: offentligInfoRouteRouteChildren = {
  offentligInfoBranchRouteRoute: offentligInfoBranchRouteRouteWithChildren,
  offentligInfoPoliciesRouteRoute: offentligInfoPoliciesRouteRouteWithChildren,
  offentligInfoAboutRoute: offentligInfoAboutRoute,
  offentligInfoBuybackRoute: offentligInfoBuybackRoute,
  offentligInfoCompaniesRoute: offentligInfoCompaniesRoute,
  offentligInfoContactRoute: offentligInfoContactRoute,
  offentligInfoFaqRoute: offentligInfoFaqRoute,
  offentligInfoGeneralRoute: offentligInfoGeneralRoute,
  offentligInfoPupilsRoute: offentligInfoPupilsRoute,
}

const offentligInfoRouteRouteWithChildren =
  offentligInfoRouteRoute._addFileChildren(offentligInfoRouteRouteChildren)

interface offentligOverleveringerRouteRouteChildren {
  offentligOverleveringerMatchIdRoute: typeof offentligOverleveringerMatchIdRoute
  offentligOverleveringerIndexRoute: typeof offentligOverleveringerIndexRoute
}

const offentligOverleveringerRouteRouteChildren: offentligOverleveringerRouteRouteChildren =
  {
    offentligOverleveringerMatchIdRoute: offentligOverleveringerMatchIdRoute,
    offentligOverleveringerIndexRoute: offentligOverleveringerIndexRoute,
  }

const offentligOverleveringerRouteRouteWithChildren =
  offentligOverleveringerRouteRoute._addFileChildren(
    offentligOverleveringerRouteRouteChildren,
  )

interface offentligRouteRouteChildren {
  offentligInfoRouteRoute: typeof offentligInfoRouteRouteWithChildren
  offentligOverleveringerRouteRoute: typeof offentligOverleveringerRouteRouteWithChildren
  offentligHandlekurvRoute: typeof offentligHandlekurvRoute
  offentligItemsRoute: typeof offentligItemsRoute
  offentligOppgaverRoute: typeof offentligOppgaverRoute
  offentligOrderHistoryRoute: typeof offentligOrderHistoryRoute
  offentligSjekkRoute: typeof offentligSjekkRoute
  offentligUserSettingsRoute: typeof offentligUserSettingsRoute
  offentligAuthFailureRoute: typeof offentligAuthFailureRoute
  offentligAuthForgotRoute: typeof offentligAuthForgotRoute
  offentligAuthLoginRoute: typeof offentligAuthLoginRoute
  offentligAuthLogoutRoute: typeof offentligAuthLogoutRoute
  offentligAuthRegisterRoute: typeof offentligAuthRegisterRoute
  offentligAuthTokenRoute: typeof offentligAuthTokenRoute
  offentligBestillingBranchIdRoute: typeof offentligBestillingBranchIdRoute
  offentligKasseBekreftRoute: typeof offentligKasseBekreftRoute
  offentligSigneringUserDetailIdRoute: typeof offentligSigneringUserDetailIdRoute
  offentligBestillingIndexRoute: typeof offentligBestillingIndexRoute
  offentligKasseIndexRoute: typeof offentligKasseIndexRoute
  offentligAuthPermissionDeniedRoute: typeof offentligAuthPermissionDeniedRoute
  offentligAuthResetIdRoute: typeof offentligAuthResetIdRoute
  offentligKasseBetalingStatusRoute: typeof offentligKasseBetalingStatusRoute
  offentligKasseBetalingIndexRoute: typeof offentligKasseBetalingIndexRoute
  offentligAuthEmailVerifyVerificationIdRoute: typeof offentligAuthEmailVerifyVerificationIdRoute
}

const offentligRouteRouteChildren: offentligRouteRouteChildren = {
  offentligInfoRouteRoute: offentligInfoRouteRouteWithChildren,
  offentligOverleveringerRouteRoute:
    offentligOverleveringerRouteRouteWithChildren,
  offentligHandlekurvRoute: offentligHandlekurvRoute,
  offentligItemsRoute: offentligItemsRoute,
  offentligOppgaverRoute: offentligOppgaverRoute,
  offentligOrderHistoryRoute: offentligOrderHistoryRoute,
  offentligSjekkRoute: offentligSjekkRoute,
  offentligUserSettingsRoute: offentligUserSettingsRoute,
  offentligAuthFailureRoute: offentligAuthFailureRoute,
  offentligAuthForgotRoute: offentligAuthForgotRoute,
  offentligAuthLoginRoute: offentligAuthLoginRoute,
  offentligAuthLogoutRoute: offentligAuthLogoutRoute,
  offentligAuthRegisterRoute: offentligAuthRegisterRoute,
  offentligAuthTokenRoute: offentligAuthTokenRoute,
  offentligBestillingBranchIdRoute: offentligBestillingBranchIdRoute,
  offentligKasseBekreftRoute: offentligKasseBekreftRoute,
  offentligSigneringUserDetailIdRoute: offentligSigneringUserDetailIdRoute,
  offentligBestillingIndexRoute: offentligBestillingIndexRoute,
  offentligKasseIndexRoute: offentligKasseIndexRoute,
  offentligAuthPermissionDeniedRoute: offentligAuthPermissionDeniedRoute,
  offentligAuthResetIdRoute: offentligAuthResetIdRoute,
  offentligKasseBetalingStatusRoute: offentligKasseBetalingStatusRoute,
  offentligKasseBetalingIndexRoute: offentligKasseBetalingIndexRoute,
  offentligAuthEmailVerifyVerificationIdRoute:
    offentligAuthEmailVerifyVerificationIdRoute,
}

const offentligRouteRouteWithChildren = offentligRouteRoute._addFileChildren(
  offentligRouteRouteChildren,
)

interface administrasjonAdminOverleveringerRouteRouteChildren {
  administrasjonAdminOverleveringerMatchIdRoute: typeof administrasjonAdminOverleveringerMatchIdRoute
  administrasjonAdminOverleveringerIndexRoute: typeof administrasjonAdminOverleveringerIndexRoute
}

const administrasjonAdminOverleveringerRouteRouteChildren: administrasjonAdminOverleveringerRouteRouteChildren =
  {
    administrasjonAdminOverleveringerMatchIdRoute:
      administrasjonAdminOverleveringerMatchIdRoute,
    administrasjonAdminOverleveringerIndexRoute:
      administrasjonAdminOverleveringerIndexRoute,
  }

const administrasjonAdminOverleveringerRouteRouteWithChildren =
  administrasjonAdminOverleveringerRouteRoute._addFileChildren(
    administrasjonAdminOverleveringerRouteRouteChildren,
  )

interface administrasjonAdminRouteRouteChildren {
  administrasjonAdminOverleveringerRouteRoute: typeof administrasjonAdminOverleveringerRouteRouteWithChildren
  administrasjonAdminBlidRoute: typeof administrasjonAdminBlidRoute
  administrasjonAdminFakturaRoute: typeof administrasjonAdminFakturaRoute
  administrasjonAdminHandlekurvRoute: typeof administrasjonAdminHandlekurvRoute
  administrasjonAdminHurtiginnsamlingRoute: typeof administrasjonAdminHurtiginnsamlingRoute
  administrasjonAdminHurtigutdelingRoute: typeof administrasjonAdminHurtigutdelingRoute
  administrasjonAdminOrdreoversiktRoute: typeof administrasjonAdminOrdreoversiktRoute
  administrasjonAdminScannerRoute: typeof administrasjonAdminScannerRoute
  administrasjonAdminUserSettingsRoute: typeof administrasjonAdminUserSettingsRoute
  administrasjonAdminVentelisteRoute: typeof administrasjonAdminVentelisteRoute
  administrasjonAdminIndexRoute: typeof administrasjonAdminIndexRoute
  administrasjonAdminDatabaseBokerRoute: typeof administrasjonAdminDatabaseBokerRoute
  administrasjonAdminDatabaseBrukereRoute: typeof administrasjonAdminDatabaseBrukereRoute
  administrasjonAdminDatabaseDynamisk_innholdRoute: typeof administrasjonAdminDatabaseDynamisk_innholdRoute
  administrasjonAdminDatabaseFilialerRoute: typeof administrasjonAdminDatabaseFilialerRoute
  administrasjonAdminDatabaseRapporterRoute: typeof administrasjonAdminDatabaseRapporterRoute
  administrasjonAdminDatabaseSelskapRoute: typeof administrasjonAdminDatabaseSelskapRoute
  administrasjonAdminDatabaseUnik_idRoute: typeof administrasjonAdminDatabaseUnik_idRoute
  administrasjonAdminKommunikasjonPaminnelserRoute: typeof administrasjonAdminKommunikasjonPaminnelserRoute
  administrasjonAdminKommunikasjonUtsendelserRoute: typeof administrasjonAdminKommunikasjonUtsendelserRoute
}

const administrasjonAdminRouteRouteChildren: administrasjonAdminRouteRouteChildren =
  {
    administrasjonAdminOverleveringerRouteRoute:
      administrasjonAdminOverleveringerRouteRouteWithChildren,
    administrasjonAdminBlidRoute: administrasjonAdminBlidRoute,
    administrasjonAdminFakturaRoute: administrasjonAdminFakturaRoute,
    administrasjonAdminHandlekurvRoute: administrasjonAdminHandlekurvRoute,
    administrasjonAdminHurtiginnsamlingRoute:
      administrasjonAdminHurtiginnsamlingRoute,
    administrasjonAdminHurtigutdelingRoute:
      administrasjonAdminHurtigutdelingRoute,
    administrasjonAdminOrdreoversiktRoute:
      administrasjonAdminOrdreoversiktRoute,
    administrasjonAdminScannerRoute: administrasjonAdminScannerRoute,
    administrasjonAdminUserSettingsRoute: administrasjonAdminUserSettingsRoute,
    administrasjonAdminVentelisteRoute: administrasjonAdminVentelisteRoute,
    administrasjonAdminIndexRoute: administrasjonAdminIndexRoute,
    administrasjonAdminDatabaseBokerRoute:
      administrasjonAdminDatabaseBokerRoute,
    administrasjonAdminDatabaseBrukereRoute:
      administrasjonAdminDatabaseBrukereRoute,
    administrasjonAdminDatabaseDynamisk_innholdRoute:
      administrasjonAdminDatabaseDynamisk_innholdRoute,
    administrasjonAdminDatabaseFilialerRoute:
      administrasjonAdminDatabaseFilialerRoute,
    administrasjonAdminDatabaseRapporterRoute:
      administrasjonAdminDatabaseRapporterRoute,
    administrasjonAdminDatabaseSelskapRoute:
      administrasjonAdminDatabaseSelskapRoute,
    administrasjonAdminDatabaseUnik_idRoute:
      administrasjonAdminDatabaseUnik_idRoute,
    administrasjonAdminKommunikasjonPaminnelserRoute:
      administrasjonAdminKommunikasjonPaminnelserRoute,
    administrasjonAdminKommunikasjonUtsendelserRoute:
      administrasjonAdminKommunikasjonUtsendelserRoute,
  }

const administrasjonAdminRouteRouteWithChildren =
  administrasjonAdminRouteRoute._addFileChildren(
    administrasjonAdminRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  offentligRouteRoute: offentligRouteRouteWithChildren,
  HealthRoute: HealthRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  administrasjonAdminRouteRoute: administrasjonAdminRouteRouteWithChildren,
  legacyWelcomeRoute: legacyWelcomeRoute,
  legacyAuthMenuRoute: legacyAuthMenuRoute,
  legacyAuthSuccessRoute: legacyAuthSuccessRoute,
  legacyDatabaseCompaniesRoute: legacyDatabaseCompaniesRoute,
  legacyUEditRoute: legacyUEditRoute,
  legacyAuthLoginForgotRoute: legacyAuthLoginForgotRoute,
  legacyAuthRegisterDetailRoute: legacyAuthRegisterDetailRoute,
  legacyAuthSocialFailureRoute: legacyAuthSocialFailureRoute,
  legacyDatabaseBranchesEditRoute: legacyDatabaseBranchesEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
